"use client";

import { useMemo, useState } from "react";

export type Batch251300Kind =
  | "html-tag-stripper"
  | "html-table-generator"
  | "html-table-to-csv"
  | "csv-to-html-table"
  | "css-specificity-calculator"
  | "css-clamp-calculator"
  | "css-box-shadow-generator"
  | "css-border-radius-generator"
  | "css-flexbox-generator"
  | "css-grid-generator"
  | "ipv4-to-integer"
  | "integer-to-ipv4"
  | "ipv6-compressor"
  | "ipv6-expander"
  | "mac-address-validator"
  | "domain-name-parser"
  | "port-number-lookup"
  | "http-header-parser"
  | "cookie-parser"
  | "csp-generator"
  | "reading-time-calculator"
  | "speaking-time-calculator"
  | "word-frequency-counter"
  | "character-frequency-counter"
  | "invisible-character-detector"
  | "unicode-character-inspector"
  | "unicode-escape-converter"
  | "diacritic-remover"
  | "add-line-numbers"
  | "remove-line-numbers"
  | "prime-number-checker"
  | "prime-factorization-calculator"
  | "percentage-error-calculator"
  | "permutation-calculator"
  | "combination-calculator"
  | "probability-calculator"
  | "z-score-calculator"
  | "weighted-average-calculator"
  | "geometric-mean-calculator"
  | "harmonic-mean-calculator"
  | "triangle-calculator"
  | "circle-calculator"
  | "rectangle-calculator"
  | "cylinder-volume-calculator"
  | "sphere-volume-calculator"
  | "cone-volume-calculator"
  | "ohms-law-calculator"
  | "voltage-divider-calculator"
  | "resistor-color-code-calculator"
  | "led-resistor-calculator";

type ResultItem = { label: string; value: string; note?: string };
type Field = { key: string; label: string; type?: "number" | "input" | "textarea" | "select"; placeholder?: string; defaultValue?: string; options?: {label:string;value:string}[] };
type ToolConfig = { fields: Field[]; button?: string; note?: string };
type ToolResult = { output?: string; summary?: ResultItem[] };

const inputClass = "w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none transition focus:border-primary";
const textareaClass = "min-h-48 w-full rounded-lg border bg-background px-3 py-2 font-mono text-sm outline-none transition focus:border-primary";
const buttonClass = "rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90";
const secondaryButtonClass = "rounded-lg border bg-background px-4 py-2 text-sm font-medium hover:bg-muted";

const S=(...pairs:[string,string][]):ResultItem[]=>pairs.map(([label,value])=>({label,value}));
const num=(v:string,label:string)=>{const n=Number(v);if(!Number.isFinite(n))throw new Error(`${label} must be a valid number.`);return n;};
const pos=(v:string,label:string)=>{const n=num(v,label);if(n<=0)throw new Error(`${label} must be greater than zero.`);return n;};
const whole=(v:string,label:string)=>{const n=num(v,label);if(!Number.isSafeInteger(n))throw new Error(`${label} must be a safe whole number.`);return n;};
const fmt=(n:number,d=6)=>Number.isFinite(n)?new Intl.NumberFormat(undefined,{maximumFractionDigits:d}).format(n):String(n);
const escapeHtml=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
const csvCell=(s:string)=>/[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],field="",q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch==='"'&&text[i+1]==='"'){field+='"';i++;}else if(ch==='"')q=false;else field+=ch;}else if(ch==='"')q=true;else if(ch===','){row.push(field);field="";}else if(ch==='\n'){row.push(field);rows.push(row);row=[];field="";}else if(ch==='\r'){}else field+=ch;}if(q)throw new Error("CSV contains an unclosed quoted field.");if(field!==""||row.length){row.push(field);rows.push(row);}return rows;}
const listNums=(s:string,label:string)=>{const a=s.split(/[,\n]/).map(x=>x.trim()).filter(Boolean).map(Number);if(!a.length||a.some(x=>!Number.isFinite(x)))throw new Error(`${label} must contain valid numbers separated by commas or new lines.`);return a;};

const CONFIG:Record<Batch251300Kind,ToolConfig> = {
  "html-tag-stripper":{fields:[{key:"html",label:"HTML",type:"textarea",placeholder:"<p>Hello <strong>world</strong></p>"}],button:"Strip Tags"},
  "html-table-generator":{fields:[{key:"data",label:"Rows",type:"textarea",placeholder:"Name,Age\nAda,36\nGrace,40"},{key:"delimiter",label:"Delimiter",type:"select",defaultValue:",",options:[{label:"Comma",value:","},{label:"Tab",value:"\\t"},{label:"Pipe",value:"|"}]},{key:"header",label:"First row",type:"select",defaultValue:"header",options:[{label:"Header row",value:"header"},{label:"Regular row",value:"body"}]}],button:"Generate HTML"},
  "html-table-to-csv":{fields:[{key:"html",label:"HTML containing a table",type:"textarea",placeholder:"<table><tr><th>Name</th><th>Age</th></tr><tr><td>Ada</td><td>36</td></tr></table>"}],button:"Convert to CSV"},
  "csv-to-html-table":{fields:[{key:"csv",label:"CSV",type:"textarea",placeholder:"Name,Age\nAda,36\nGrace,40"},{key:"header",label:"First row",type:"select",defaultValue:"header",options:[{label:"Header row",value:"header"},{label:"Regular row",value:"body"}]}],button:"Convert to HTML"},
  "css-specificity-calculator":{fields:[{key:"selectors",label:"CSS selector(s)",type:"textarea",placeholder:"#app .card:hover > h2\nnav ul li.active a"}],button:"Calculate Specificity"},
  "css-clamp-calculator":{fields:[{key:"minSize",label:"Minimum size (px)",type:"number",placeholder:"16",defaultValue:"16"},{key:"maxSize",label:"Maximum size (px)",type:"number",placeholder:"32",defaultValue:"32"},{key:"minViewport",label:"Minimum viewport (px)",type:"number",placeholder:"320",defaultValue:"320"},{key:"maxViewport",label:"Maximum viewport (px)",type:"number",placeholder:"1200",defaultValue:"1200"},{key:"root",label:"Root font size (px)",type:"number",placeholder:"16",defaultValue:"16"}],button:"Generate clamp()"},
  "css-box-shadow-generator":{fields:[{key:"x",label:"X offset (px)",type:"number",defaultValue:"0"},{key:"y",label:"Y offset (px)",type:"number",defaultValue:"8"},{key:"blur",label:"Blur (px)",type:"number",defaultValue:"24"},{key:"spread",label:"Spread (px)",type:"number",defaultValue:"0"},{key:"color",label:"Color",type:"input",defaultValue:"0, 0, 0"},{key:"opacity",label:"Opacity (0–1)",type:"number",defaultValue:"0.18"},{key:"inset",label:"Shadow type",type:"select",defaultValue:"outset",options:[{label:"Outset",value:"outset"},{label:"Inset",value:"inset"}]}],button:"Generate CSS"},
  "css-border-radius-generator":{fields:[{key:"tl",label:"Top left (px)",type:"number",defaultValue:"16"},{key:"tr",label:"Top right (px)",type:"number",defaultValue:"16"},{key:"br",label:"Bottom right (px)",type:"number",defaultValue:"16"},{key:"bl",label:"Bottom left (px)",type:"number",defaultValue:"16"}],button:"Generate CSS"},
  "css-flexbox-generator":{fields:[{key:"direction",label:"Direction",type:"select",defaultValue:"row",options:[{label:"Row",value:"row"},{label:"Column",value:"column"},{label:"Row reverse",value:"row-reverse"},{label:"Column reverse",value:"column-reverse"}]},{key:"justify",label:"Justify content",type:"select",defaultValue:"flex-start",options:[{label:"Start",value:"flex-start"},{label:"Center",value:"center"},{label:"End",value:"flex-end"},{label:"Space between",value:"space-between"},{label:"Space around",value:"space-around"},{label:"Space evenly",value:"space-evenly"}]},{key:"align",label:"Align items",type:"select",defaultValue:"stretch",options:[{label:"Stretch",value:"stretch"},{label:"Start",value:"flex-start"},{label:"Center",value:"center"},{label:"End",value:"flex-end"},{label:"Baseline",value:"baseline"}]},{key:"wrap",label:"Wrap",type:"select",defaultValue:"nowrap",options:[{label:"No wrap",value:"nowrap"},{label:"Wrap",value:"wrap"},{label:"Wrap reverse",value:"wrap-reverse"}]},{key:"gap",label:"Gap (px)",type:"number",defaultValue:"16"}],button:"Generate CSS"},
  "css-grid-generator":{fields:[{key:"mode",label:"Columns",type:"select",defaultValue:"auto",options:[{label:"Responsive auto-fit",value:"auto"},{label:"Fixed column count",value:"fixed"}]},{key:"columns",label:"Fixed columns",type:"number",defaultValue:"3"},{key:"min",label:"Minimum column width (px)",type:"number",defaultValue:"240"},{key:"gap",label:"Gap (px)",type:"number",defaultValue:"16"}],button:"Generate CSS"},
  "ipv4-to-integer":{fields:[{key:"ip",label:"IPv4 address",type:"input",placeholder:"192.168.1.1"}],button:"Convert"},
  "integer-to-ipv4":{fields:[{key:"value",label:"Unsigned integer (0–4294967295)",type:"input",placeholder:"3232235777"}],button:"Convert"},
  "ipv6-compressor":{fields:[{key:"ip",label:"IPv6 address",type:"input",placeholder:"2001:0db8:0000:0000:0000:ff00:0042:8329"}],button:"Compress"},
  "ipv6-expander":{fields:[{key:"ip",label:"IPv6 address",type:"input",placeholder:"2001:db8::ff00:42:8329"}],button:"Expand"},
  "mac-address-validator":{fields:[{key:"mac",label:"MAC address",type:"input",placeholder:"00:1A:2B:3C:4D:5E"}],button:"Validate"},
  "domain-name-parser":{fields:[{key:"domain",label:"URL or hostname",type:"input",placeholder:"https://docs.example.com/path?q=1"}],button:"Parse Domain",note:"Registrable-domain output is a simple last-two-label estimate and does not use the Public Suffix List."},
  "port-number-lookup":{fields:[{key:"port",label:"Port number",type:"number",placeholder:"443"}],button:"Look Up Port"},
  "http-header-parser":{fields:[{key:"headers",label:"Raw HTTP headers",type:"textarea",placeholder:"Content-Type: application/json\nCache-Control: no-cache\nX-Request-ID: abc123"}],button:"Parse Headers"},
  "cookie-parser":{fields:[{key:"cookie",label:"Cookie header",type:"textarea",placeholder:"session=abc123; theme=dark; loggedIn=true"}],button:"Parse Cookies"},
  "csp-generator":{fields:[{key:"defaultSrc",label:"default-src",type:"input",defaultValue:"'self'"},{key:"scriptSrc",label:"script-src",type:"input",defaultValue:"'self'"},{key:"styleSrc",label:"style-src",type:"input",defaultValue:"'self'"},{key:"imgSrc",label:"img-src",type:"input",defaultValue:"'self' data: https:"},{key:"connectSrc",label:"connect-src",type:"input",defaultValue:"'self'"},{key:"fontSrc",label:"font-src",type:"input",defaultValue:"'self' data:"},{key:"objectSrc",label:"object-src",type:"input",defaultValue:"'none'"}],button:"Generate CSP",note:"Treat this as a starter policy. Test CSP carefully on your own site before enforcing it in production."},
  "reading-time-calculator":{fields:[{key:"text",label:"Text",type:"textarea",placeholder:"Paste an article or document here…"},{key:"wpm",label:"Reading speed (words per minute)",type:"number",defaultValue:"225"}],button:"Calculate"},
  "speaking-time-calculator":{fields:[{key:"text",label:"Script",type:"textarea",placeholder:"Paste a speech, presentation, or script here…"},{key:"wpm",label:"Speaking speed (words per minute)",type:"number",defaultValue:"130"}],button:"Calculate"},
  "word-frequency-counter":{fields:[{key:"text",label:"Text",type:"textarea",placeholder:"Paste text to count word frequencies…"},{key:"limit",label:"Number of words to show",type:"number",defaultValue:"25"}],button:"Count Words"},
  "character-frequency-counter":{fields:[{key:"text",label:"Text",type:"textarea",placeholder:"Paste text to count characters…"},{key:"whitespace",label:"Whitespace",type:"select",defaultValue:"ignore",options:[{label:"Ignore whitespace",value:"ignore"},{label:"Include whitespace",value:"include"}]}],button:"Count Characters"},
  "invisible-character-detector":{fields:[{key:"text",label:"Text",type:"textarea",placeholder:"Paste text that may contain invisible characters…"}],button:"Detect Invisible Characters"},
  "unicode-character-inspector":{fields:[{key:"text",label:"Text",type:"textarea",placeholder:"Aé🙂"}],button:"Inspect Characters"},
  "unicode-escape-converter":{fields:[{key:"text",label:"Text or escapes",type:"textarea",placeholder:"Hello 🙂 or \\u0048\\u0065\\u006c\\u006c\\u006f"},{key:"mode",label:"Mode",type:"select",defaultValue:"encode",options:[{label:"Text → Unicode escapes",value:"encode"},{label:"Unicode escapes → Text",value:"decode"}]}],button:"Convert"},
  "diacritic-remover":{fields:[{key:"text",label:"Text",type:"textarea",placeholder:"Crème brûlée — São Paulo — naïve"}],button:"Remove Diacritics"},
  "add-line-numbers":{fields:[{key:"text",label:"Text",type:"textarea",placeholder:"First line\nSecond line\nThird line"},{key:"start",label:"Starting number",type:"number",defaultValue:"1"}],button:"Add Line Numbers"},
  "remove-line-numbers":{fields:[{key:"text",label:"Numbered text",type:"textarea",placeholder:"1. First line\n2. Second line\n3. Third line"}],button:"Remove Line Numbers"},
  "prime-number-checker":{fields:[{key:"n",label:"Whole number",type:"input",placeholder:"104729"}],button:"Check Prime"},
  "prime-factorization-calculator":{fields:[{key:"n",label:"Positive whole number",type:"input",placeholder:"360"}],button:"Factorize"},
  "percentage-error-calculator":{fields:[{key:"observed",label:"Observed / experimental value",type:"number",placeholder:"98"},{key:"true",label:"True / accepted value",type:"number",placeholder:"100"}],button:"Calculate"},
  "permutation-calculator":{fields:[{key:"n",label:"n (total items)",type:"input",placeholder:"10"},{key:"r",label:"r (selected items)",type:"input",placeholder:"3"}],button:"Calculate nPr"},
  "combination-calculator":{fields:[{key:"n",label:"n (total items)",type:"input",placeholder:"10"},{key:"r",label:"r (selected items)",type:"input",placeholder:"3"}],button:"Calculate nCr"},
  "probability-calculator":{fields:[{key:"fav",label:"Favorable outcomes",type:"number",placeholder:"3"},{key:"total",label:"Total possible outcomes",type:"number",placeholder:"10"}],button:"Calculate Probability"},
  "z-score-calculator":{fields:[{key:"x",label:"Value (x)",type:"number",placeholder:"85"},{key:"mean",label:"Mean (μ)",type:"number",placeholder:"70"},{key:"sd",label:"Standard deviation (σ)",type:"number",placeholder:"10"}],button:"Calculate Z-score"},
  "weighted-average-calculator":{fields:[{key:"values",label:"Values (comma-separated)",type:"input",placeholder:"80, 90, 70"},{key:"weights",label:"Weights (comma-separated)",type:"input",placeholder:"0.2, 0.5, 0.3"}],button:"Calculate"},
  "geometric-mean-calculator":{fields:[{key:"values",label:"Positive values (comma-separated)",type:"input",placeholder:"2, 8, 32"}],button:"Calculate"},
  "harmonic-mean-calculator":{fields:[{key:"values",label:"Non-zero values (comma-separated)",type:"input",placeholder:"1, 2, 4"}],button:"Calculate"},
  "triangle-calculator":{fields:[{key:"a",label:"Side a",type:"number",placeholder:"3"},{key:"b",label:"Side b",type:"number",placeholder:"4"},{key:"c",label:"Side c",type:"number",placeholder:"5"}],button:"Calculate"},
  "circle-calculator":{fields:[{key:"r",label:"Radius",type:"number",placeholder:"10"}],button:"Calculate"},
  "rectangle-calculator":{fields:[{key:"l",label:"Length",type:"number",placeholder:"12"},{key:"w",label:"Width",type:"number",placeholder:"8"}],button:"Calculate"},
  "cylinder-volume-calculator":{fields:[{key:"r",label:"Radius",type:"number",placeholder:"5"},{key:"h",label:"Height",type:"number",placeholder:"12"}],button:"Calculate"},
  "sphere-volume-calculator":{fields:[{key:"r",label:"Radius",type:"number",placeholder:"5"}],button:"Calculate"},
  "cone-volume-calculator":{fields:[{key:"r",label:"Radius",type:"number",placeholder:"5"},{key:"h",label:"Height",type:"number",placeholder:"12"}],button:"Calculate"},
  "ohms-law-calculator":{fields:[{key:"mode",label:"Calculate",type:"select",defaultValue:"voltage",options:[{label:"Voltage (V = I × R)",value:"voltage"},{label:"Current (I = V ÷ R)",value:"current"},{label:"Resistance (R = V ÷ I)",value:"resistance"},{label:"Power (P = V × I)",value:"power"}]},{key:"a",label:"First value",type:"number",placeholder:"2"},{key:"b",label:"Second value",type:"number",placeholder:"100"}],button:"Calculate",note:"For Voltage enter current (A) then resistance (Ω). For Current enter voltage (V) then resistance (Ω). For Resistance enter voltage (V) then current (A). For Power enter voltage (V) then current (A)."},
  "voltage-divider-calculator":{fields:[{key:"vin",label:"Input voltage (V)",type:"number",placeholder:"12"},{key:"r1",label:"R1 (Ω)",type:"number",placeholder:"1000"},{key:"r2",label:"R2 (Ω)",type:"number",placeholder:"2000"}],button:"Calculate"},
  "resistor-color-code-calculator":{fields:[{key:"b1",label:"Band 1",type:"select",defaultValue:"brown",options:[]},{key:"b2",label:"Band 2",type:"select",defaultValue:"black",options:[]},{key:"mult",label:"Multiplier",type:"select",defaultValue:"red",options:[]},{key:"tol",label:"Tolerance",type:"select",defaultValue:"gold",options:[]}],button:"Decode Resistor"},
  "led-resistor-calculator":{fields:[{key:"supply",label:"Supply voltage (V)",type:"number",placeholder:"5"},{key:"forward",label:"LED forward voltage (V each)",type:"number",placeholder:"2"},{key:"count",label:"LEDs in series",type:"number",defaultValue:"1"},{key:"current",label:"Desired LED current (mA)",type:"number",placeholder:"20"}],button:"Calculate"},
};

const colorValues:{name:string;digit?:number;mult:number;tol?:number}[]=[
{name:"black",digit:0,mult:1},{name:"brown",digit:1,mult:10,tol:1},{name:"red",digit:2,mult:100,tol:2},{name:"orange",digit:3,mult:1000},{name:"yellow",digit:4,mult:10000},{name:"green",digit:5,mult:100000,tol:.5},{name:"blue",digit:6,mult:1000000,tol:.25},{name:"violet",digit:7,mult:10000000,tol:.1},{name:"gray",digit:8,mult:100000000,tol:.05},{name:"white",digit:9,mult:1000000000},{name:"gold",mult:.1,tol:5},{name:"silver",mult:.01,tol:10}
];
const digitOptions=colorValues.filter(c=>c.digit!==undefined).map(c=>({label:c.name[0].toUpperCase()+c.name.slice(1),value:c.name}));
const multOptions=colorValues.map(c=>({label:`${c.name[0].toUpperCase()+c.name.slice(1)} (×${c.mult})`,value:c.name}));
const tolOptions=colorValues.filter(c=>c.tol!==undefined).map(c=>({label:`${c.name[0].toUpperCase()+c.name.slice(1)} (±${c.tol}%)`,value:c.name}));
CONFIG["resistor-color-code-calculator"].fields[0].options=digitOptions;
CONFIG["resistor-color-code-calculator"].fields[1].options=digitOptions;
CONFIG["resistor-color-code-calculator"].fields[2].options=multOptions;
CONFIG["resistor-color-code-calculator"].fields[3].options=tolOptions;

function ipv4Parts(ip:string){const p=ip.trim().split('.');if(p.length!==4)throw new Error("Enter an IPv4 address with four octets.");const nums=p.map(x=>Number(x));if(nums.some((x,i)=>!/^\d+$/.test(p[i])||!Number.isInteger(x)||x<0||x>255))throw new Error("Each IPv4 octet must be a whole number from 0 to 255.");return nums;}
function expandIPv6(ip:string){ip=ip.trim().toLowerCase();if(!ip||ip.includes('.')||!/^[0-9a-f:]+$/.test(ip))throw new Error("Enter a hexadecimal IPv6 address without an embedded IPv4 suffix.");if((ip.match(/::/g)||[]).length>1)throw new Error("IPv6 address contains more than one :: compression marker.");let parts:string[];if(ip.includes('::')){const [l,r]=ip.split('::');const left=l?l.split(':'):[];const right=r?r.split(':'):[];if(left.some(x=>!x||x.length>4)||right.some(x=>!x||x.length>4))throw new Error("IPv6 groups must contain 1 to 4 hexadecimal digits.");const missing=8-left.length-right.length;if(missing<1)throw new Error("Invalid :: compression in IPv6 address.");parts=[...left,...Array(missing).fill('0'),...right];}else{parts=ip.split(':');if(parts.length!==8)throw new Error("An uncompressed IPv6 address must contain eight groups.");}
if(parts.length!==8||parts.some(x=>!/^[0-9a-f]{1,4}$/.test(x)))throw new Error("Invalid IPv6 address.");return parts.map(x=>x.padStart(4,'0'));}
function compressIPv6(ip:string){const ex=expandIPv6(ip).map(x=>x.replace(/^0+(?=[0-9a-f])/,'')||'0');let bestStart=-1,bestLen=0;for(let i=0;i<ex.length;){if(ex[i]!=='0'){i++;continue;}let j=i;while(j<ex.length&&ex[j]==='0')j++;if(j-i>bestLen){bestStart=i;bestLen=j-i;}i=j;}if(bestLen<2)return ex.join(':');const left=ex.slice(0,bestStart).join(':');const right=ex.slice(bestStart+bestLen).join(':');return `${left}::${right}`.replace(/^:::/,'::').replace(/:::$/,'::');}
function bigFact(n:number){let r=1n;for(let i=2n;i<=BigInt(n);i++)r*=i;return r;}
function gcdBig(a:bigint,b:bigint){while(b){[a,b]=[b,a%b];}return a<0n?-a:a;}
function codePointName(cp:number){if(cp===32)return "SPACE";if(cp===9)return "TAB";if(cp===10)return "LINE FEED";if(cp===13)return "CARRIAGE RETURN";if(cp===160)return "NO-BREAK SPACE";if(cp===0x200b)return "ZERO WIDTH SPACE";if(cp===0x200c)return "ZERO WIDTH NON-JOINER";if(cp===0x200d)return "ZERO WIDTH JOINER";if(cp===0xfeff)return "ZERO WIDTH NO-BREAK SPACE / BOM";return "Unicode character";}
function runTool(kind:Batch251300Kind,v:Record<string,string>):ToolResult{
 switch(kind){
 case "html-tag-stripper":{let h=v.html||"";h=h.replace(/<\s*br\s*\/?\s*>/gi,"\n").replace(/<\/(p|div|li|tr|h[1-6]|section|article)>/gi,"\n");const doc=new DOMParser().parseFromString(h,"text/html");const out=(doc.body.textContent||"").replace(/\n{3,}/g,"\n\n").trim();return{output:out,summary:S(["Output characters",String(out.length)])};}
 case "html-table-generator":{const delim=v.delimiter==='\\t'?'\t':v.delimiter||',';const rows=(v.data||'').split(/\r?\n/).filter(Boolean).map(r=>r.split(delim));if(!rows.length)throw new Error("Enter at least one row.");const tag=(i:number)=>i===0&&v.header==='header'?'th':'td';const body=rows.map((r,i)=>`  <tr>\n${r.map(c=>`    <${tag(i)}>${escapeHtml(c.trim())}</${tag(i)}>`).join('\n')}\n  </tr>`).join('\n');return{output:`<table>\n${body}\n</table>`,summary:S(["Rows",String(rows.length)],["Columns",String(Math.max(...rows.map(r=>r.length)))])};}
 case "html-table-to-csv":{const doc=new DOMParser().parseFromString(v.html||'',"text/html");const table=doc.querySelector('table');if(!table)throw new Error("No HTML table was found.");const rows=Array.from(table.querySelectorAll('tr')).map(tr=>Array.from(tr.querySelectorAll('th,td')).map(td=>(td.textContent||'').trim()));return{output:rows.map(r=>r.map(csvCell).join(',')).join('\n'),summary:S(["Rows",String(rows.length)],["Columns",String(Math.max(0,...rows.map(r=>r.length)))])};}
 case "csv-to-html-table":{const rows=parseCsv(v.csv||'');if(!rows.length)throw new Error("Enter CSV data.");const body=rows.map((r,i)=>{const tag=i===0&&v.header==='header'?'th':'td';return`  <tr>\n${r.map(c=>`    <${tag}>${escapeHtml(c)}</${tag}>`).join('\n')}\n  </tr>`}).join('\n');return{output:`<table>\n${body}\n</table>`,summary:S(["Rows",String(rows.length)],["Columns",String(Math.max(...rows.map(r=>r.length)))])};}
 case "css-specificity-calculator":{const sels=(v.selectors||'').split(/\n|,(?![^\[]*\])/).map(s=>s.trim()).filter(Boolean);if(!sels.length)throw new Error("Enter at least one selector.");const lines=sels.map(sel=>{const clean=sel.replace(/:where\([^)]*\)/g,'');const ids=(clean.match(/#[\w-]+/g)||[]).length;const classes=(clean.match(/\.[\w-]+/g)||[]).length+(clean.match(/\[[^\]]+\]/g)||[]).length+(clean.match(/:(?!:)[\w-]+(?:\([^)]*\))?/g)||[]).length;const pseudos=(clean.match(/::[\w-]+/g)||[]).length;const stripped=clean.replace(/#[\w-]+|\.[\w-]+|\[[^\]]+\]|::?[\w-]+(?:\([^)]*\))?|\*/g,' ');const elements=(stripped.match(/(^|[\s>+~])([a-zA-Z][\w-]*)/g)||[]).length+pseudos;return`${ids},${classes},${elements}  ${sel}`;});return{output:lines.join('\n'),summary:S(["Selectors",String(sels.length)],["Format","ID, class, element"])};}
 case "css-clamp-calculator":{const min=num(v.minSize,"Minimum size"),max=num(v.maxSize,"Maximum size"),minV=pos(v.minViewport,"Minimum viewport"),maxV=pos(v.maxViewport,"Maximum viewport"),root=pos(v.root,"Root font size");if(maxV<=minV)throw new Error("Maximum viewport must be greater than minimum viewport.");const slope=(max-min)/(maxV-minV)*100;const intercept=(min-slope*minV/100)/root;const out=`clamp(${fmt(min/root,4)}rem, ${fmt(intercept,4)}rem + ${fmt(slope,4)}vw, ${fmt(max/root,4)}rem)`;return{output:out,summary:S(["Slope",`${fmt(slope,4)}vw`],["Intercept",`${fmt(intercept,4)}rem`])};}
 case "css-box-shadow-generator":{const x=num(v.x,"X offset"),y=num(v.y,"Y offset"),blur=Math.max(0,num(v.blur,"Blur")),spread=num(v.spread,"Spread"),op=num(v.opacity,"Opacity");if(op<0||op>1)throw new Error("Opacity must be between 0 and 1.");const rgb=(v.color||'0, 0, 0').trim();const value=`${v.inset==='inset'?'inset ':''}${x}px ${y}px ${blur}px ${spread}px rgba(${rgb}, ${op})`;return{output:`box-shadow: ${value};`,summary:S(["Shadow",value])};}
 case "css-border-radius-generator":{const vals=['tl','tr','br','bl'].map(k=>Math.max(0,num(v[k],k.toUpperCase())));const value=vals.map(x=>`${x}px`).join(' ');return{output:`border-radius: ${value};`,summary:S(["CSS value",value])};}
 case "css-flexbox-generator":{const gap=Math.max(0,num(v.gap,"Gap"));const out=`display: flex;\nflex-direction: ${v.direction};\njustify-content: ${v.justify};\nalign-items: ${v.align};\nflex-wrap: ${v.wrap};\ngap: ${gap}px;`;return{output:out};}
 case "css-grid-generator":{const gap=Math.max(0,num(v.gap,"Gap"));let cols;if(v.mode==='fixed'){const n=Math.max(1,Math.floor(pos(v.columns,"Columns")));cols=`repeat(${n}, minmax(0, 1fr))`;}else{cols=`repeat(auto-fit, minmax(${Math.max(1,pos(v.min,"Minimum column width"))}px, 1fr))`;}return{output:`display: grid;\ngrid-template-columns: ${cols};\ngap: ${gap}px;`};}
 case "ipv4-to-integer":{const p=ipv4Parts(v.ip||'');const val=((p[0]*16777216)+(p[1]*65536)+(p[2]*256)+p[3])>>>0;return{output:String(val),summary:S(["IPv4",p.join('.')],["Unsigned integer",String(val)])};}
 case "integer-to-ipv4":{const n=Number(v.value);if(!Number.isSafeInteger(n)||n<0||n>4294967295)throw new Error("Enter a whole number from 0 to 4294967295.");const ip=[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255].join('.');return{output:ip,summary:S(["Integer",String(n)],["IPv4",ip])};}
 case "ipv6-compressor":{const out=compressIPv6(v.ip||'');return{output:out,summary:S(["Compressed IPv6",out])};}
 case "ipv6-expander":{const out=expandIPv6(v.ip||'').join(':');return{output:out,summary:S(["Expanded IPv6",out])};}
 case "mac-address-validator":{const raw=(v.mac||'').trim();let hex=raw.replace(/[:-]/g,'').replace(/\./g,'');if(!/^[0-9a-fA-F]{12}$/.test(hex))return{output:"Invalid MAC address",summary:S(["Valid","No"])};hex=hex.toUpperCase();const norm=hex.match(/.{2}/g)!.join(':');return{output:norm,summary:S(["Valid","Yes"],["Normalized",norm],["Locally administered",(parseInt(hex.slice(0,2),16)&2)?"Yes":"No"],["Multicast",(parseInt(hex.slice(0,2),16)&1)?"Yes":"No"])};}
 case "domain-name-parser":{let raw=(v.domain||'').trim();if(!raw)throw new Error("Enter a URL or hostname.");let host='';try{host=new URL(/^[a-z]+:\/\//i.test(raw)?raw:`https://${raw}`).hostname;}catch{throw new Error("Enter a valid URL or hostname.");}host=host.replace(/\.$/,'').toLowerCase();const labels=host.split('.').filter(Boolean);if(!labels.length)throw new Error("No hostname was found.");const tld=labels.length>1?labels.at(-1)!:"";const registrable=labels.length>1?labels.slice(-2).join('.'):host;const sub=labels.length>2?labels.slice(0,-2).join('.'):"";return{output:JSON.stringify({hostname:host,labels,subdomain:sub,registrableDomainEstimate:registrable,tld},null,2),summary:S(["Hostname",host],["Subdomain",sub||"(none)"],["Domain estimate",registrable],["TLD",tld||"(none)"])};}
 case "port-number-lookup":{const p=whole(v.port,"Port");if(p<0||p>65535)throw new Error("Port must be from 0 to 65535.");const ports:Record<number,[string,string]>={20:["FTP Data","TCP"],21:["FTP Control","TCP"],22:["SSH","TCP"],23:["Telnet","TCP"],25:["SMTP","TCP"],53:["DNS","TCP/UDP"],67:["DHCP Server","UDP"],68:["DHCP Client","UDP"],80:["HTTP","TCP"],110:["POP3","TCP"],123:["NTP","UDP"],143:["IMAP","TCP"],161:["SNMP","UDP"],389:["LDAP","TCP/UDP"],443:["HTTPS","TCP"],465:["SMTPS","TCP"],587:["SMTP Submission","TCP"],636:["LDAPS","TCP"],993:["IMAPS","TCP"],995:["POP3S","TCP"],1433:["Microsoft SQL Server","TCP"],1521:["Oracle Database","TCP"],2049:["NFS","TCP/UDP"],3306:["MySQL","TCP"],3389:["RDP","TCP/UDP"],5432:["PostgreSQL","TCP"],6379:["Redis","TCP"],8080:["Common alternate HTTP","TCP"],8443:["Common alternate HTTPS","TCP"]};const hit=ports[p];return{output:hit?`${p} — ${hit[0]} (${hit[1]})`:`${p} — No common service is included in this local lookup table.`,summary:S(["Port",String(p)],["Service",hit?.[0]||"Not in local table"],["Typical protocol",hit?.[1]||"—"])};}
 case "http-header-parser":{const obj:Record<string,string|string[]>={};for(const line of (v.headers||'').split(/\r?\n/)){if(!line.trim())continue;const i=line.indexOf(':');if(i<1)continue;const k=line.slice(0,i).trim();const val=line.slice(i+1).trim();if(k in obj)obj[k]=Array.isArray(obj[k])?[...(obj[k] as string[]),val]:[obj[k] as string,val];else obj[k]=val;}if(!Object.keys(obj).length)throw new Error("No valid header lines were found. Use Name: value format.");return{output:JSON.stringify(obj,null,2),summary:S(["Header names",String(Object.keys(obj).length)])};}
 case "cookie-parser":{const obj:Record<string,string>={};for(const part of (v.cookie||'').split(';')){const i=part.indexOf('=');if(i<1)continue;const k=part.slice(0,i).trim(),val=part.slice(i+1).trim();obj[k]=val;}if(!Object.keys(obj).length)throw new Error("No name=value cookies were found.");return{output:JSON.stringify(obj,null,2),summary:S(["Cookies",String(Object.keys(obj).length)])};}
 case "csp-generator":{const dirs=[['default-src',v.defaultSrc],['script-src',v.scriptSrc],['style-src',v.styleSrc],['img-src',v.imgSrc],['connect-src',v.connectSrc],['font-src',v.fontSrc],['object-src',v.objectSrc]].filter(x=>x[1]?.trim()).map(x=>`${x[0]} ${x[1].trim()}`);const out=dirs.join('; ')+';';return{output:`Content-Security-Policy: ${out}`,summary:S(["Directives",String(dirs.length)])};}
 case "reading-time-calculator":case "speaking-time-calculator":{const words=(v.text||'').trim().match(/\S+/g)?.length||0;const wpm=pos(v.wpm,"Words per minute");const mins=words/wpm;const sec=Math.round(mins*60);const label=kind.startsWith('reading')?'Reading time':'Speaking time';return{output:`${Math.floor(sec/60)} min ${sec%60} sec`,summary:S(["Words",String(words)],["Speed",`${fmt(wpm,0)} wpm`],[label,`${Math.floor(sec/60)} min ${sec%60} sec`])};}
 case "word-frequency-counter":{const words=(v.text||'').toLocaleLowerCase().match(/[\p{L}\p{N}]+(?:['’][\p{L}\p{N}]+)*/gu)||[];const m=new Map<string,number>();words.forEach(w=>m.set(w,(m.get(w)||0)+1));const limit=Math.max(1,Math.min(500,Math.floor(pos(v.limit,"Limit"))));const out=[...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,limit).map(([w,c],i)=>`${i+1}. ${w} — ${c}`).join('\n');return{output:out,summary:S(["Words",String(words.length)],["Unique words",String(m.size)])};}
 case "character-frequency-counter":{const chars=[...(v.text||'')].filter(ch=>v.whitespace==='include'||!/\s/u.test(ch));const m=new Map<string,number>();chars.forEach(ch=>m.set(ch,(m.get(ch)||0)+1));const out=[...m.entries()].sort((a,b)=>b[1]-a[1]).map(([ch,c])=>`${JSON.stringify(ch)}  U+${ch.codePointAt(0)!.toString(16).toUpperCase().padStart(4,'0')}  ${c}`).join('\n');return{output:out,summary:S(["Characters counted",String(chars.length)],["Unique characters",String(m.size)])};}
 case "invisible-character-detector":{const invisible=new Set([0x00a0,0x00ad,0x034f,0x061c,0x180e,0x200b,0x200c,0x200d,0x200e,0x200f,0x202a,0x202b,0x202c,0x202d,0x202e,0x2060,0x2061,0x2062,0x2063,0x2064,0x2066,0x2067,0x2068,0x2069,0xfeff]);const found:{i:number;cp:number}[]=[];let idx=0;for(const ch of v.text||''){const cp=ch.codePointAt(0)!;if(invisible.has(cp))found.push({i:idx,cp});idx+=ch.length;}const out=found.length?found.map(x=>`Index ${x.i}: U+${x.cp.toString(16).toUpperCase().padStart(4,'0')} — ${codePointName(x.cp)}`).join('\n'):"No common invisible characters were detected.";return{output:out,summary:S(["Invisible characters found",String(found.length)])};}
 case "unicode-character-inspector":{let logical=0;const lines=[] as string[];for(const ch of v.text||''){const cp=ch.codePointAt(0)!;const esc=cp<=0xffff?`\\u${cp.toString(16).toUpperCase().padStart(4,'0')}`:`\\u{${cp.toString(16).toUpperCase()}}`;lines.push(`${logical}: ${JSON.stringify(ch)}  U+${cp.toString(16).toUpperCase().padStart(4,'0')}  ${esc}  ${codePointName(cp)}`);logical++;}return{output:lines.join('\n'),summary:S(["Unicode characters",String(logical)])};}
 case "unicode-escape-converter":{const text=v.text||'';if(v.mode==='decode'){const out=text.replace(/\\u\{([0-9a-fA-F]{1,6})\}|\\u([0-9a-fA-F]{4})/g,(_,a,b)=>String.fromCodePoint(parseInt(a||b,16)));return{output:out,summary:S(["Output characters",String([...out].length)])};}const out=[...text].map(ch=>{const cp=ch.codePointAt(0)!;return cp<=0xffff?`\\u${cp.toString(16).toUpperCase().padStart(4,'0')}`:`\\u{${cp.toString(16).toUpperCase()}}`;}).join('');return{output:out,summary:S(["Input characters",String([...text].length)])};}
 case "diacritic-remover":{const out=(v.text||'').normalize('NFD').replace(/\p{M}+/gu,'').normalize('NFC');return{output:out,summary:S(["Characters",String([...out].length)])};}
 case "add-line-numbers":{const start=whole(v.start,"Starting number");const lines=(v.text||'').split(/\r?\n/);const width=String(start+Math.max(0,lines.length-1)).length;return{output:lines.map((line,i)=>`${String(start+i).padStart(width,' ')}. ${line}`).join('\n'),summary:S(["Lines",String(lines.length)])};}
 case "remove-line-numbers":{const lines=(v.text||'').split(/\r?\n/);const out=lines.map(l=>l.replace(/^\s*\d+\s*(?:[.):\-]|\|)?\s+/,'')).join('\n');return{output:out,summary:S(["Lines",String(lines.length)])};}
 case "prime-number-checker":{const n=whole(v.n,"Number");if(n<2)return{output:`${n} is not prime.`,summary:S(["Prime","No"])};let d=0;if(n%2===0&&n!==2)d=2;else for(let i=3;i*i<=n;i+=2){if(n%i===0){d=i;break;}}return{output:d?`${n} is composite. First divisor found: ${d}.`:`${n} is prime.`,summary:S(["Prime",d?"No":"Yes"],...(d?[["First divisor",String(d)] as [string,string]]:[]))};}
 case "prime-factorization-calculator":{let n=whole(v.n,"Number");if(n<2)throw new Error("Enter a whole number of at least 2.");const original=n;const factors:number[]=[];while(n%2===0){factors.push(2);n/=2;}for(let d=3;d*d<=n;d+=2)while(n%d===0){factors.push(d);n/=d;}if(n>1)factors.push(n);const counts=new Map<number,number>();factors.forEach(f=>counts.set(f,(counts.get(f)||0)+1));const pretty=[...counts].map(([f,c])=>c===1?String(f):`${f}^${c}`).join(' × ');return{output:`${original} = ${pretty}`,summary:S(["Prime factors",factors.join(', ')])};}
 case "percentage-error-calculator":{const o=num(v.observed,"Observed value"),t=num(v.true,"True value");if(t===0)throw new Error("True value cannot be zero for percentage error.");const abs=Math.abs(o-t),pct=abs/Math.abs(t)*100;return{output:`${fmt(pct)}%`,summary:S(["Absolute error",fmt(abs)],["Percentage error",`${fmt(pct)}%`])};}
 case "permutation-calculator":case "combination-calculator":{const n=whole(v.n,"n"),r=whole(v.r,"r");if(n<0||r<0||r>n)throw new Error("Use whole numbers with 0 ≤ r ≤ n.");let result:bigint;if(kind.startsWith('permutation'))result=bigFact(n)/bigFact(n-r);else{const rr=Math.min(r,n-r);let top=1n,bot=1n;for(let i=1;i<=rr;i++){top*=BigInt(n-rr+i);bot*=BigInt(i);}result=top/bot;}return{output:result.toString(),summary:S([kind.startsWith('permutation')?'nPr':'nCr',result.toString()])};}
 case "probability-calculator":{const f=num(v.fav,"Favorable outcomes"),t=pos(v.total,"Total outcomes");if(f<0||f>t)throw new Error("Favorable outcomes must be between 0 and total outcomes.");const p=f/t;return{output:fmt(p,8),summary:S(["Probability",fmt(p,8)],["Percentage",`${fmt(p*100,6)}%`],["Odds in favor",f===0?"0 : 1":f===t?"1 : 0":`${fmt(f)} : ${fmt(t-f)}`])};}
 case "z-score-calculator":{const x=num(v.x,"Value"),m=num(v.mean,"Mean"),sd=pos(v.sd,"Standard deviation");const z=(x-m)/sd;return{output:fmt(z,8),summary:S(["Z-score",fmt(z,8)],["Distance from mean",`${fmt(Math.abs(z),6)} standard deviations`])};}
 case "weighted-average-calculator":{const vals=listNums(v.values,"Values"),ws=listNums(v.weights,"Weights");if(vals.length!==ws.length)throw new Error("Values and weights must have the same count.");const total=ws.reduce((a,b)=>a+b,0);if(total===0)throw new Error("Total weight cannot be zero.");const avg=vals.reduce((a,x,i)=>a+x*ws[i],0)/total;return{output:fmt(avg,8),summary:S(["Weighted average",fmt(avg,8)],["Total weight",fmt(total)])};}
 case "geometric-mean-calculator":{const vals=listNums(v.values,"Values");if(vals.some(x=>x<=0))throw new Error("Geometric mean requires positive values.");const mean=Math.exp(vals.reduce((a,x)=>a+Math.log(x),0)/vals.length);return{output:fmt(mean,8),summary:S(["Geometric mean",fmt(mean,8)],["Values",String(vals.length)])};}
 case "harmonic-mean-calculator":{const vals=listNums(v.values,"Values");if(vals.some(x=>x===0))throw new Error("Harmonic mean is undefined when a value is zero.");const mean=vals.length/vals.reduce((a,x)=>a+1/x,0);return{output:fmt(mean,8),summary:S(["Harmonic mean",fmt(mean,8)],["Values",String(vals.length)])};}
 case "triangle-calculator":{const a=pos(v.a,"Side a"),b=pos(v.b,"Side b"),c=pos(v.c,"Side c");if(a+b<=c||a+c<=b||b+c<=a)throw new Error("These sides do not form a valid triangle.");const p=a+b+c,s=p/2,area=Math.sqrt(s*(s-a)*(s-b)*(s-c));const angle=(x:number,y:number,z:number)=>Math.acos(Math.max(-1,Math.min(1,(y*y+z*z-x*x)/(2*y*z))))*180/Math.PI;return{output:`Area: ${fmt(area)}\nPerimeter: ${fmt(p)}`,summary:S(["Area",fmt(area)],["Perimeter",fmt(p)],["Angle A",`${fmt(angle(a,b,c),4)}°`],["Angle B",`${fmt(angle(b,a,c),4)}°`],["Angle C",`${fmt(angle(c,a,b),4)}°`])};}
 case "circle-calculator":{const r=pos(v.r,"Radius");return{output:`Area: ${fmt(Math.PI*r*r)}\nCircumference: ${fmt(2*Math.PI*r)}`,summary:S(["Diameter",fmt(2*r)],["Circumference",fmt(2*Math.PI*r)],["Area",fmt(Math.PI*r*r)])};}
 case "rectangle-calculator":{const l=pos(v.l,"Length"),w=pos(v.w,"Width");return{output:`Area: ${fmt(l*w)}\nPerimeter: ${fmt(2*(l+w))}`,summary:S(["Area",fmt(l*w)],["Perimeter",fmt(2*(l+w))],["Diagonal",fmt(Math.hypot(l,w))])};}
 case "cylinder-volume-calculator":{const r=pos(v.r,"Radius"),h=pos(v.h,"Height");return{output:`Volume: ${fmt(Math.PI*r*r*h)}`,summary:S(["Volume",fmt(Math.PI*r*r*h)],["Lateral area",fmt(2*Math.PI*r*h)],["Surface area",fmt(2*Math.PI*r*(r+h))])};}
 case "sphere-volume-calculator":{const r=pos(v.r,"Radius");return{output:`Volume: ${fmt(4/3*Math.PI*r**3)}`,summary:S(["Volume",fmt(4/3*Math.PI*r**3)],["Surface area",fmt(4*Math.PI*r*r)],["Diameter",fmt(2*r)])};}
 case "cone-volume-calculator":{const r=pos(v.r,"Radius"),h=pos(v.h,"Height"),sl=Math.hypot(r,h);return{output:`Volume: ${fmt(Math.PI*r*r*h/3)}`,summary:S(["Volume",fmt(Math.PI*r*r*h/3)],["Slant height",fmt(sl)],["Lateral area",fmt(Math.PI*r*sl)],["Surface area",fmt(Math.PI*r*(r+sl))])};}
 case "ohms-law-calculator":{const a=num(v.a,"First value"),b=num(v.b,"Second value");let label='',value=0,unit='';if(v.mode==='voltage'){value=a*b;label='Voltage';unit='V';}else if(v.mode==='current'){if(b===0)throw new Error("Resistance cannot be zero.");value=a/b;label='Current';unit='A';}else if(v.mode==='resistance'){if(b===0)throw new Error("Current cannot be zero.");value=a/b;label='Resistance';unit='Ω';}else{value=a*b;label='Power';unit='W';}return{output:`${fmt(value,8)} ${unit}`,summary:S([label,`${fmt(value,8)} ${unit}`])};}
 case "voltage-divider-calculator":{const vin=num(v.vin,"Input voltage"),r1=pos(v.r1,"R1"),r2=pos(v.r2,"R2");const current=vin/(r1+r2),out=vin*r2/(r1+r2);return{output:`${fmt(out,8)} V`,summary:S(["Output voltage",`${fmt(out,8)} V`],["Divider current",`${fmt(current*1000,8)} mA`],["Total resistance",`${fmt(r1+r2)} Ω`])};}
 case "resistor-color-code-calculator":{const c1=colorValues.find(c=>c.name===v.b1)!,c2=colorValues.find(c=>c.name===v.b2)!,cm=colorValues.find(c=>c.name===v.mult)!,ct=colorValues.find(c=>c.name===v.tol)!;const ohms=((c1.digit||0)*10+(c2.digit||0))*cm.mult;const pretty=ohms>=1e6?`${fmt(ohms/1e6,6)} MΩ`:ohms>=1e3?`${fmt(ohms/1e3,6)} kΩ`:`${fmt(ohms,6)} Ω`;return{output:`${pretty} ±${ct.tol}%`,summary:S(["Resistance",pretty],["Tolerance",`±${ct.tol}%`])};}
 case "led-resistor-calculator":{const supply=pos(v.supply,"Supply voltage"),vf=pos(v.forward,"LED forward voltage"),count=Math.max(1,Math.floor(pos(v.count,"LED count"))),ma=pos(v.current,"LED current"),head=supply-vf*count;if(head<=0)throw new Error("Supply voltage must be greater than the total LED forward voltage.");const amps=ma/1000,r=head/amps,p=amps*amps*r;return{output:`${fmt(r,4)} Ω`,summary:S(["Calculated resistance",`${fmt(r,4)} Ω`],["Resistor voltage drop",`${fmt(head,4)} V`],["Resistor power",`${fmt(p,6)} W`],["Suggested minimum power rating",`${fmt(p*2,4)} W or higher`])};}
 default: throw new Error("This tool is not configured.");
 }
}

function ResultGrid({items}:{items:ResultItem[]}){return <div className="grid gap-3 sm:grid-cols-2">{items.map((item,i)=><div key={`${item.label}-${i}`} className="rounded-xl border bg-background p-4"><div className="text-sm text-muted-foreground">{item.label}</div><div className="mt-1 break-words text-xl font-semibold">{item.value}</div>{item.note&&<div className="mt-2 text-xs leading-relaxed text-muted-foreground">{item.note}</div>}</div>)}</div>}

export function Batch251300Tool({kind}:{kind:Batch251300Kind}){
 const config=CONFIG[kind];
 const initial=useMemo(()=>Object.fromEntries(config.fields.map(f=>[f.key,f.defaultValue||""])),[config]);
 const [values,setValues]=useState<Record<string,string>>(initial);const[output,setOutput]=useState("");const[summary,setSummary]=useState<ResultItem[]>([]);const[error,setError]=useState("");const[copied,setCopied]=useState(false);
 const clearResult=()=>{setOutput("");setSummary([]);setError("");setCopied(false)};
 const run=()=>{setError("");setCopied(false);try{const r=runTool(kind,values);setOutput(r.output||"");setSummary(r.summary||[]);}catch(e){setOutput("");setSummary([]);setError(e instanceof Error?e.message:"Unable to process input.");}};
 const reset=()=>{setValues(initial);clearResult()};
 const copy=async()=>{if(!output)return;try{await navigator.clipboard.writeText(output);setCopied(true);window.setTimeout(()=>setCopied(false),1500);}catch{setError("Unable to copy output.")}};
 return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">{config.fields.map(f=><label key={f.key} className={`block space-y-2 ${f.type==='textarea'?'sm:col-span-2':''}`}><span className="text-sm font-medium">{f.label}</span>{f.type==='textarea'?<textarea value={values[f.key]||""} onChange={e=>{setValues(p=>({...p,[f.key]:e.target.value}));clearResult()}} placeholder={f.placeholder} className={textareaClass}/>:f.type==='select'?<select value={values[f.key]||""} onChange={e=>{setValues(p=>({...p,[f.key]:e.target.value}));clearResult()}} className={inputClass}>{(f.options||[]).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={f.type==='number'?'number':'text'} step="any" value={values[f.key]||""} onChange={e=>{setValues(p=>({...p,[f.key]:e.target.value}));clearResult()}} placeholder={f.placeholder} className={inputClass}/>}</label>)}</div>{config.note&&<div className="rounded-lg border bg-muted/30 p-3 text-xs leading-relaxed text-muted-foreground">{config.note}</div>}<div className="flex flex-wrap gap-3"><button type="button" onClick={run} className={buttonClass}>{config.button||"Run Tool"}</button><button type="button" onClick={reset} className={secondaryButtonClass}>Reset</button></div>{error&&<div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error}</div>}{summary.length>0&&<ResultGrid items={summary}/>} {output!==""&&<div className="space-y-2"><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">Result</span><button type="button" onClick={copy} className={secondaryButtonClass}>{copied?"Copied":"Copy"}</button></div><textarea readOnly value={output} className={textareaClass} aria-label="Result"/></div>}</div>;
}
