import { ToolConfig } from "@/types";

const localFaq = [
  { question: "Does this tool send my input to a server?", answer: "No. This tool is designed to process the values or text you enter directly in your browser." },
  { question: "Do I need an account?", answer: "No. Avorqin tools can be used without creating an account." },
  { question: "Can I copy the result?", answer: "Yes. Generated or transformed output can be copied for use in your own workflow." },
];

const mathFaq = [
  { question: "Is this calculation performed in my browser?", answer: "Yes. Avorqin performs the calculation locally in your browser using the values you enter." },
  { question: "Do I need an account?", answer: "No. Avorqin math tools can be used without creating an account." },
  { question: "Are results rounded?", answer: "Some displayed decimal results are rounded for readability, while exact integer results are preserved where practical." },
];

export const batch251To300Tools: ToolConfig[] = [
  {
    id: "html-tag-stripper",
    name: "HTML Tag Stripper",
    slug: "html-tag-stripper",
    category: "Developer",
    description: "Remove HTML tags from markup and extract readable plain text directly in your browser.",
    longDescription: "Remove HTML tags from markup and extract readable plain text directly in your browser. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["html tag stripper", "online html tag stripper", "developer tool", "web tool"],
    icon: "Code2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "html-table-generator",
    name: "HTML Table Generator",
    slug: "html-table-generator",
    category: "Developer",
    description: "Generate clean HTML table markup from rows of comma-, tab-, or pipe-separated data.",
    longDescription: "Generate clean HTML table markup from rows of comma-, tab-, or pipe-separated data. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["html table generator", "online html table generator", "developer tool", "web tool"],
    icon: "Table2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "html-table-to-csv",
    name: "HTML Table to CSV Converter",
    slug: "html-table-to-csv",
    category: "Developer",
    description: "Convert the first HTML table in pasted markup into properly escaped CSV data.",
    longDescription: "Convert the first HTML table in pasted markup into properly escaped CSV data. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["html table to csv converter", "online html table to csv converter", "developer tool", "web tool"],
    icon: "Table2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "csv-to-html-table",
    name: "CSV to HTML Table Converter",
    slug: "csv-to-html-table",
    category: "JSON & Data",
    description: "Convert CSV data into clean HTML table markup with an optional header row.",
    longDescription: "Convert CSV data into clean HTML table markup with an optional header row. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["csv to html table converter", "online csv to html table converter", "developer tool", "web tool"],
    icon: "FileSpreadsheet",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "css-specificity-calculator",
    name: "CSS Specificity Calculator",
    slug: "css-specificity-calculator",
    category: "Developer",
    description: "Estimate CSS selector specificity using ID, class/attribute/pseudo-class, and element counts.",
    longDescription: "Estimate CSS selector specificity using ID, class/attribute/pseudo-class, and element counts. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["css specificity calculator", "online css specificity calculator", "css tool", "web development tool"],
    icon: "Braces",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "css-clamp-calculator",
    name: "CSS Clamp Calculator",
    slug: "css-clamp-calculator",
    category: "Developer",
    description: "Generate a responsive CSS clamp() expression from minimum and maximum sizes and viewport widths.",
    longDescription: "Generate a responsive CSS clamp() expression from minimum and maximum sizes and viewport widths. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["css clamp calculator", "online css clamp calculator", "css tool", "web development tool"],
    icon: "SlidersHorizontal",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "css-box-shadow-generator",
    name: "CSS Box Shadow Generator",
    slug: "css-box-shadow-generator",
    category: "Developer",
    description: "Generate a CSS box-shadow declaration from offsets, blur, spread, opacity, color, and inset settings.",
    longDescription: "Generate a CSS box-shadow declaration from offsets, blur, spread, opacity, color, and inset settings. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["css box shadow generator", "online css box shadow generator", "css tool", "web development tool"],
    icon: "Layers3",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "css-border-radius-generator",
    name: "CSS Border Radius Generator",
    slug: "css-border-radius-generator",
    category: "Developer",
    description: "Generate CSS border-radius values for each corner and preview the resulting declaration.",
    longDescription: "Generate CSS border-radius values for each corner and preview the resulting declaration. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["css border radius generator", "online css border radius generator", "css tool", "web development tool"],
    icon: "SquareRoundCorner",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "css-flexbox-generator",
    name: "CSS Flexbox Generator",
    slug: "css-flexbox-generator",
    category: "Developer",
    description: "Generate common CSS Flexbox container declarations from direction, alignment, wrapping, and gap options.",
    longDescription: "Generate common CSS Flexbox container declarations from direction, alignment, wrapping, and gap options. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["css flexbox generator", "online css flexbox generator", "css tool", "web development tool"],
    icon: "Rows3",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "css-grid-generator",
    name: "CSS Grid Generator",
    slug: "css-grid-generator",
    category: "Developer",
    description: "Generate a responsive CSS Grid declaration with configurable columns, minimum width, and gap.",
    longDescription: "Generate a responsive CSS Grid declaration with configurable columns, minimum width, and gap. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["css grid generator", "online css grid generator", "css tool", "web development tool"],
    icon: "LayoutGrid",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "ipv4-to-integer",
    name: "IPv4 to Integer Converter",
    slug: "ipv4-to-integer",
    category: "Developer",
    description: "Convert a dotted IPv4 address into its unsigned 32-bit integer representation.",
    longDescription: "Convert a dotted IPv4 address into its unsigned 32-bit integer representation. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["ipv4 to integer converter", "online ipv4 to integer converter", "network tool", "developer tool"],
    icon: "Network",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "integer-to-ipv4",
    name: "Integer to IPv4 Converter",
    slug: "integer-to-ipv4",
    category: "Developer",
    description: "Convert an unsigned 32-bit integer into a dotted IPv4 address.",
    longDescription: "Convert an unsigned 32-bit integer into a dotted IPv4 address. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["integer to ipv4 converter", "online integer to ipv4 converter", "network tool", "developer tool"],
    icon: "Binary",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "ipv6-compressor",
    name: "IPv6 Compressor",
    slug: "ipv6-compressor",
    category: "Developer",
    description: "Compress a valid IPv6 address by removing leading zeroes and shortening the longest zero run.",
    longDescription: "Compress a valid IPv6 address by removing leading zeroes and shortening the longest zero run. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["ipv6 compressor", "online ipv6 compressor", "network tool", "developer tool"],
    icon: "Network",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "ipv6-expander",
    name: "IPv6 Expander",
    slug: "ipv6-expander",
    category: "Developer",
    description: "Expand a compressed IPv6 address into eight four-digit hexadecimal groups.",
    longDescription: "Expand a compressed IPv6 address into eight four-digit hexadecimal groups. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["ipv6 expander", "online ipv6 expander", "network tool", "developer tool"],
    icon: "Network",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "mac-address-validator",
    name: "MAC Address Validator",
    slug: "mac-address-validator",
    category: "Developer",
    description: "Validate common MAC address formats and normalize a valid address to colon-separated uppercase notation.",
    longDescription: "Validate common MAC address formats and normalize a valid address to colon-separated uppercase notation. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["mac address validator", "online mac address validator", "network tool", "developer tool"],
    icon: "BadgeCheck",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "domain-name-parser",
    name: "Domain Name Parser",
    slug: "domain-name-parser",
    category: "Developer",
    description: "Parse a URL or hostname into hostname labels, subdomain, registrable-domain estimate, and top-level domain.",
    longDescription: "Parse a URL or hostname into hostname labels, subdomain, registrable-domain estimate, and top-level domain. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["domain name parser", "online domain name parser", "network tool", "developer tool"],
    icon: "Globe2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "port-number-lookup",
    name: "Port Number Lookup",
    slug: "port-number-lookup",
    category: "Developer",
    description: "Look up common TCP and UDP port numbers and the services typically associated with them.",
    longDescription: "Look up common TCP and UDP port numbers and the services typically associated with them. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["port number lookup", "online port number lookup", "network tool", "developer tool"],
    icon: "ServerCog",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "http-header-parser",
    name: "HTTP Header Parser",
    slug: "http-header-parser",
    category: "Developer",
    description: "Parse raw HTTP request or response header lines into a readable JSON object.",
    longDescription: "Parse raw HTTP request or response header lines into a readable JSON object. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["http header parser", "online http header parser", "network tool", "developer tool"],
    icon: "FileKey2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "cookie-parser",
    name: "Cookie Parser",
    slug: "cookie-parser",
    category: "Developer",
    description: "Parse a Cookie header string into individual cookie names and values.",
    longDescription: "Parse a Cookie header string into individual cookie names and values. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["cookie parser", "online cookie parser", "network tool", "developer tool"],
    icon: "Cookie",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "csp-generator",
    name: "Content Security Policy Generator",
    slug: "csp-generator",
    category: "Developer",
    description: "Generate a starter Content-Security-Policy header from common source directives.",
    longDescription: "Generate a starter Content-Security-Policy header from common source directives. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["content security policy generator", "online content security policy generator", "network tool", "developer tool"],
    icon: "Shield",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "reading-time-calculator",
    name: "Reading Time Calculator",
    slug: "reading-time-calculator",
    category: "Developer",
    description: "Estimate reading time from word count and a configurable words-per-minute reading speed.",
    longDescription: "Estimate reading time from word count and a configurable words-per-minute reading speed. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["reading time calculator", "online reading time calculator", "text tool", "developer utility"],
    icon: "BookOpenText",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "speaking-time-calculator",
    name: "Speaking Time Calculator",
    slug: "speaking-time-calculator",
    category: "Developer",
    description: "Estimate speaking time for a script from word count and a configurable speaking speed.",
    longDescription: "Estimate speaking time for a script from word count and a configurable speaking speed. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["speaking time calculator", "online speaking time calculator", "text tool", "developer utility"],
    icon: "Mic2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "word-frequency-counter",
    name: "Word Frequency Counter",
    slug: "word-frequency-counter",
    category: "Developer",
    description: "Count how often each word appears in text and list the most frequent terms.",
    longDescription: "Count how often each word appears in text and list the most frequent terms. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["word frequency counter", "online word frequency counter", "text tool", "developer utility"],
    icon: "ListOrdered",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "character-frequency-counter",
    name: "Character Frequency Counter",
    slug: "character-frequency-counter",
    category: "Developer",
    description: "Count Unicode character frequencies in text with an option to ignore whitespace.",
    longDescription: "Count Unicode character frequencies in text with an option to ignore whitespace. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["character frequency counter", "online character frequency counter", "text tool", "developer utility"],
    icon: "Type",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "invisible-character-detector",
    name: "Invisible Character Detector",
    slug: "invisible-character-detector",
    category: "Developer",
    description: "Find common invisible and zero-width Unicode characters and report their positions and code points.",
    longDescription: "Find common invisible and zero-width Unicode characters and report their positions and code points. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["invisible character detector", "online invisible character detector", "text tool", "developer utility"],
    icon: "ScanText",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "unicode-character-inspector",
    name: "Unicode Character Inspector",
    slug: "unicode-character-inspector",
    category: "Developer",
    description: "Inspect text character by character and view Unicode code points, escape forms, and basic classifications.",
    longDescription: "Inspect text character by character and view Unicode code points, escape forms, and basic classifications. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["unicode character inspector", "online unicode character inspector", "text tool", "developer utility"],
    icon: "Languages",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "unicode-escape-converter",
    name: "Unicode Escape Converter",
    slug: "unicode-escape-converter",
    category: "Developer",
    description: "Convert text to Unicode escape sequences or decode Unicode escapes back into readable text.",
    longDescription: "Convert text to Unicode escape sequences or decode Unicode escapes back into readable text. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["unicode escape converter", "online unicode escape converter", "text tool", "developer utility"],
    icon: "Braces",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "diacritic-remover",
    name: "Diacritic Remover",
    slug: "diacritic-remover",
    category: "Developer",
    description: "Remove common accents and combining diacritic marks from Unicode text.",
    longDescription: "Remove common accents and combining diacritic marks from Unicode text. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["diacritic remover", "online diacritic remover", "text tool", "developer utility"],
    icon: "Eraser",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "add-line-numbers",
    name: "Add Line Numbers",
    slug: "add-line-numbers",
    category: "Developer",
    description: "Add sequential line numbers to multiline text with a configurable starting number.",
    longDescription: "Add sequential line numbers to multiline text with a configurable starting number. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["add line numbers", "online add line numbers", "text tool", "developer utility"],
    icon: "ListPlus",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "remove-line-numbers",
    name: "Remove Line Numbers",
    slug: "remove-line-numbers",
    category: "Developer",
    description: "Remove common leading line-number formats from multiline text.",
    longDescription: "Remove common leading line-number formats from multiline text. Processing runs locally in a modern browser so your input does not need to be sent to an external utility service.",
    keywords: ["remove line numbers", "online remove line numbers", "text tool", "developer utility"],
    icon: "ListMinus",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "prime-number-checker",
    name: "Prime Number Checker",
    slug: "prime-number-checker",
    category: "Math",
    description: "Check whether a whole number is prime and see the first divisor when it is composite.",
    longDescription: "Check whether a whole number is prime and see the first divisor when it is composite. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["prime number checker", "online prime number checker", "math calculator", "online calculator"],
    icon: "BadgeCheck",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "prime-factorization-calculator",
    name: "Prime Factorization Calculator",
    slug: "prime-factorization-calculator",
    category: "Math",
    description: "Find the prime factorization of a positive whole number.",
    longDescription: "Find the prime factorization of a positive whole number. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["prime factorization calculator", "online prime factorization calculator", "math calculator", "online calculator"],
    icon: "Sigma",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "percentage-error-calculator",
    name: "Percentage Error Calculator",
    slug: "percentage-error-calculator",
    category: "Math",
    description: "Calculate absolute error and percentage error from an observed value and a true or accepted value.",
    longDescription: "Calculate absolute error and percentage error from an observed value and a true or accepted value. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["percentage error calculator", "online percentage error calculator", "math calculator", "online calculator"],
    icon: "Percent",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "permutation-calculator",
    name: "Permutation Calculator",
    slug: "permutation-calculator",
    category: "Math",
    description: "Calculate the number of ordered selections nPr using exact whole-number arithmetic.",
    longDescription: "Calculate the number of ordered selections nPr using exact whole-number arithmetic. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["permutation calculator", "online permutation calculator", "math calculator", "online calculator"],
    icon: "Calculator",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "combination-calculator",
    name: "Combination Calculator",
    slug: "combination-calculator",
    category: "Math",
    description: "Calculate the number of unordered selections nCr using exact whole-number arithmetic.",
    longDescription: "Calculate the number of unordered selections nCr using exact whole-number arithmetic. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["combination calculator", "online combination calculator", "math calculator", "online calculator"],
    icon: "Calculator",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "probability-calculator",
    name: "Probability Calculator",
    slug: "probability-calculator",
    category: "Math",
    description: "Calculate probability, percentage, and simple odds from favorable and total outcomes.",
    longDescription: "Calculate probability, percentage, and simple odds from favorable and total outcomes. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["probability calculator", "online probability calculator", "math calculator", "online calculator"],
    icon: "Dices",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "z-score-calculator",
    name: "Z Score Calculator",
    slug: "z-score-calculator",
    category: "Math",
    description: "Calculate a z-score from a value, population mean, and standard deviation.",
    longDescription: "Calculate a z-score from a value, population mean, and standard deviation. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["z score calculator", "online z score calculator", "math calculator", "online calculator"],
    icon: "Activity",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "weighted-average-calculator",
    name: "Weighted Average Calculator",
    slug: "weighted-average-calculator",
    category: "Math",
    description: "Calculate a weighted average from comma-separated values and corresponding weights.",
    longDescription: "Calculate a weighted average from comma-separated values and corresponding weights. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["weighted average calculator", "online weighted average calculator", "math calculator", "online calculator"],
    icon: "ChartNoAxesColumnIncreasing",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "geometric-mean-calculator",
    name: "Geometric Mean Calculator",
    slug: "geometric-mean-calculator",
    category: "Math",
    description: "Calculate the geometric mean of positive numeric values.",
    longDescription: "Calculate the geometric mean of positive numeric values. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["geometric mean calculator", "online geometric mean calculator", "math calculator", "online calculator"],
    icon: "Sigma",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "harmonic-mean-calculator",
    name: "Harmonic Mean Calculator",
    slug: "harmonic-mean-calculator",
    category: "Math",
    description: "Calculate the harmonic mean of non-zero numeric values.",
    longDescription: "Calculate the harmonic mean of non-zero numeric values. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["harmonic mean calculator", "online harmonic mean calculator", "math calculator", "online calculator"],
    icon: "Sigma",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "triangle-calculator",
    name: "Triangle Calculator",
    slug: "triangle-calculator",
    category: "Math",
    description: "Calculate triangle perimeter, area, and angles from three side lengths.",
    longDescription: "Calculate triangle perimeter, area, and angles from three side lengths. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["triangle calculator", "online triangle calculator", "math calculator", "online calculator"],
    icon: "Triangle",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "circle-calculator",
    name: "Circle Calculator",
    slug: "circle-calculator",
    category: "Math",
    description: "Calculate a circle diameter, circumference, and area from its radius.",
    longDescription: "Calculate a circle diameter, circumference, and area from its radius. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["circle calculator", "online circle calculator", "math calculator", "online calculator"],
    icon: "Circle",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "rectangle-calculator",
    name: "Rectangle Calculator",
    slug: "rectangle-calculator",
    category: "Math",
    description: "Calculate rectangle area, perimeter, and diagonal from length and width.",
    longDescription: "Calculate rectangle area, perimeter, and diagonal from length and width. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["rectangle calculator", "online rectangle calculator", "math calculator", "online calculator"],
    icon: "RectangleHorizontal",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "cylinder-volume-calculator",
    name: "Cylinder Volume Calculator",
    slug: "cylinder-volume-calculator",
    category: "Math",
    description: "Calculate cylinder volume, lateral area, and total surface area from radius and height.",
    longDescription: "Calculate cylinder volume, lateral area, and total surface area from radius and height. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["cylinder volume calculator", "online cylinder volume calculator", "math calculator", "online calculator"],
    icon: "Cylinder",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "sphere-volume-calculator",
    name: "Sphere Volume Calculator",
    slug: "sphere-volume-calculator",
    category: "Math",
    description: "Calculate sphere volume, surface area, and diameter from radius.",
    longDescription: "Calculate sphere volume, surface area, and diameter from radius. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["sphere volume calculator", "online sphere volume calculator", "math calculator", "online calculator"],
    icon: "CircleDot",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "cone-volume-calculator",
    name: "Cone Volume Calculator",
    slug: "cone-volume-calculator",
    category: "Math",
    description: "Calculate cone volume, slant height, lateral area, and total surface area from radius and height.",
    longDescription: "Calculate cone volume, slant height, lateral area, and total surface area from radius and height. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["cone volume calculator", "online cone volume calculator", "math calculator", "online calculator"],
    icon: "Triangle",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "ohms-law-calculator",
    name: "Ohm's Law Calculator",
    slug: "ohms-law-calculator",
    category: "Math",
    description: "Calculate voltage, current, resistance, or power using common Ohm’s law relationships.",
    longDescription: "Calculate voltage, current, resistance, or power using common Ohm’s law relationships. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["ohms law calculator", "online ohms law calculator", "math calculator", "online calculator"],
    icon: "Zap",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "voltage-divider-calculator",
    name: "Voltage Divider Calculator",
    slug: "voltage-divider-calculator",
    category: "Math",
    description: "Calculate output voltage and resistor currents for a basic two-resistor voltage divider.",
    longDescription: "Calculate output voltage and resistor currents for a basic two-resistor voltage divider. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["voltage divider calculator", "online voltage divider calculator", "math calculator", "online calculator"],
    icon: "CircuitBoard",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "resistor-color-code-calculator",
    name: "Resistor Color Code Calculator",
    slug: "resistor-color-code-calculator",
    category: "Math",
    description: "Decode a four-band resistor color code into resistance and tolerance.",
    longDescription: "Decode a four-band resistor color code into resistance and tolerance. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["resistor color code calculator", "online resistor color code calculator", "math calculator", "online calculator"],
    icon: "Palette",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  },
  {
    id: "led-resistor-calculator",
    name: "LED Resistor Calculator",
    slug: "led-resistor-calculator",
    category: "Math",
    description: "Calculate a suggested series resistor and resistor power for one or more LEDs.",
    longDescription: "Calculate a suggested series resistor and resistor power for one or more LEDs. Enter the required values and Avorqin calculates the result locally in your browser using standard mathematical formulas.",
    keywords: ["led resistor calculator", "online led resistor calculator", "math calculator", "online calculator"],
    icon: "Lightbulb",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: mathFaq,
  }
];
