import { ToolConfig } from "@/types";

const financeFaq = [
  { question: "Are these calculations performed in my browser?", answer: "Yes. Avorqin performs the calculations locally in your browser and does not need to send the values you enter to an external calculation service." },
  { question: "Are the results financial advice?", answer: "No. Results are estimates based on the values and formulas shown by the tool and are not financial, tax, lending, investment, or legal advice." },
  { question: "Do I need an account?", answer: "No. Avorqin tools can be used without creating an account." },
];

const localFaq = [
  { question: "Does this tool upload my input?", answer: "No. This tool is designed to process the text you enter directly in your browser." },
  { question: "Do I need an account?", answer: "No. Avorqin tools can be used without creating an account." },
  { question: "Can I copy the result?", answer: "Yes. Generated or transformed output can be selected and copied for use in your own workflow." },
];

export const batch201To250Tools: ToolConfig[] = [
  {
    id: "auto-loan-calculator",
    name: "Auto Loan Calculator",
    slug: "auto-loan-calculator",
    category: "Finance & Business",
    description: "Calculate estimated auto loan payments, financed amount, and total interest from vehicle price, down payment, trade-in, tax, APR, and term.",
    longDescription: "Calculate estimated auto loan payments, financed amount, and total interest from vehicle price, down payment, trade-in, tax, APR, and term. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["auto loan calculator", "auto loan calculator", "online auto loan calculator", "finance calculator", "business calculator"],
    icon: "Car",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "credit-card-payoff-calculator",
    name: "Credit Card Payoff Calculator",
    slug: "credit-card-payoff-calculator",
    category: "Finance & Business",
    description: "Estimate how long it will take to pay off a credit card balance and how much interest you may pay.",
    longDescription: "Estimate how long it will take to pay off a credit card balance and how much interest you may pay. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["credit card payoff calculator", "credit card payoff calculator", "online credit card payoff calculator", "finance calculator", "business calculator"],
    icon: "CreditCard",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "debt-payoff-calculator",
    name: "Debt Payoff Calculator",
    slug: "debt-payoff-calculator",
    category: "Finance & Business",
    description: "Estimate a payoff timeline, total interest, and total payments for a debt using a fixed monthly payment.",
    longDescription: "Estimate a payoff timeline, total interest, and total payments for a debt using a fixed monthly payment. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["debt payoff calculator", "debt payoff calculator", "online debt payoff calculator", "finance calculator", "business calculator"],
    icon: "BadgeDollarSign",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "debt-snowball-calculator",
    name: "Debt Snowball Calculator",
    slug: "debt-snowball-calculator",
    category: "Finance & Business",
    description: "Estimate a debt snowball payoff plan by targeting the smallest balance first while rolling freed payments forward.",
    longDescription: "Estimate a debt snowball payoff plan by targeting the smallest balance first while rolling freed payments forward. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["debt snowball calculator", "debt snowball calculator", "online debt snowball calculator", "finance calculator", "business calculator"],
    icon: "ListOrdered",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "debt-avalanche-calculator",
    name: "Debt Avalanche Calculator",
    slug: "debt-avalanche-calculator",
    category: "Finance & Business",
    description: "Estimate a debt avalanche payoff plan by targeting the highest APR first while rolling freed payments forward.",
    longDescription: "Estimate a debt avalanche payoff plan by targeting the highest APR first while rolling freed payments forward. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["debt avalanche calculator", "debt avalanche calculator", "online debt avalanche calculator", "finance calculator", "business calculator"],
    icon: "TrendingDown",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "apr-calculator",
    name: "APR Calculator",
    slug: "apr-calculator",
    category: "Finance & Business",
    description: "Estimate annual percentage rate from net loan proceeds, monthly payment, and repayment term.",
    longDescription: "Estimate annual percentage rate from net loan proceeds, monthly payment, and repayment term. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["apr calculator", "apr calculator", "online apr calculator", "finance calculator", "business calculator"],
    icon: "Percent",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "apy-calculator",
    name: "APY Calculator",
    slug: "apy-calculator",
    category: "Finance & Business",
    description: "Convert a stated annual interest rate and compounding frequency into annual percentage yield.",
    longDescription: "Convert a stated annual interest rate and compounding frequency into annual percentage yield. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["apy calculator", "apy calculator", "online apy calculator", "finance calculator", "business calculator"],
    icon: "BadgePercent",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "debt-to-income-ratio-calculator",
    name: "Debt-to-Income Ratio Calculator",
    slug: "debt-to-income-ratio-calculator",
    category: "Finance & Business",
    description: "Calculate debt-to-income ratio from gross monthly income and recurring monthly debt payments.",
    longDescription: "Calculate debt-to-income ratio from gross monthly income and recurring monthly debt payments. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["debt-to-income ratio calculator", "debt to income ratio calculator", "online debt to income ratio calculator", "finance calculator", "business calculator"],
    icon: "Gauge",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "loan-amortization-calculator",
    name: "Loan Amortization Calculator",
    slug: "loan-amortization-calculator",
    category: "Finance & Business",
    description: "Calculate fixed loan payments, total interest, and first-payment principal and interest amounts.",
    longDescription: "Calculate fixed loan payments, total interest, and first-payment principal and interest amounts. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["loan amortization calculator", "loan amortization calculator", "online loan amortization calculator", "finance calculator", "business calculator"],
    icon: "Landmark",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "rule-of-72-calculator",
    name: "Rule of 72 Calculator",
    slug: "rule-of-72-calculator",
    category: "Finance & Business",
    description: "Estimate how many years it may take money to double at a fixed annual growth rate using the Rule of 72.",
    longDescription: "Estimate how many years it may take money to double at a fixed annual growth rate using the Rule of 72. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["rule of 72 calculator", "rule of 72 calculator", "online rule of 72 calculator", "finance calculator", "business calculator"],
    icon: "Clock3",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "rent-vs-buy-calculator",
    name: "Rent vs Buy Calculator",
    slug: "rent-vs-buy-calculator",
    category: "Finance & Business",
    description: "Compare a simplified estimated cost of renting with buying a home over a selected time horizon.",
    longDescription: "Compare a simplified estimated cost of renting with buying a home over a selected time horizon. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["rent vs buy calculator", "rent vs buy calculator", "online rent vs buy calculator", "finance calculator", "business calculator"],
    icon: "House",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "down-payment-calculator",
    name: "Down Payment Calculator",
    slug: "down-payment-calculator",
    category: "Finance & Business",
    description: "Calculate down payment amount and estimated loan amount from a purchase price and down payment percentage.",
    longDescription: "Calculate down payment amount and estimated loan amount from a purchase price and down payment percentage. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["down payment calculator", "down payment calculator", "online down payment calculator", "finance calculator", "business calculator"],
    icon: "WalletCards",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "mortgage-refinance-calculator",
    name: "Mortgage Refinance Calculator",
    slug: "mortgage-refinance-calculator",
    category: "Finance & Business",
    description: "Compare current and refinance mortgage payments and estimate monthly savings and closing-cost break-even time.",
    longDescription: "Compare current and refinance mortgage payments and estimate monthly savings and closing-cost break-even time. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["mortgage refinance calculator", "mortgage refinance calculator", "online mortgage refinance calculator", "finance calculator", "business calculator"],
    icon: "RefreshCw",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "biweekly-mortgage-calculator",
    name: "Biweekly Mortgage Calculator",
    slug: "biweekly-mortgage-calculator",
    category: "Finance & Business",
    description: "Compare standard monthly mortgage payments with a biweekly payment schedule and estimate interest savings.",
    longDescription: "Compare standard monthly mortgage payments with a biweekly payment schedule and estimate interest savings. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["biweekly mortgage calculator", "biweekly mortgage calculator", "online biweekly mortgage calculator", "finance calculator", "business calculator"],
    icon: "CalendarClock",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "credit-card-interest-calculator",
    name: "Credit Card Interest Calculator",
    slug: "credit-card-interest-calculator",
    category: "Finance & Business",
    description: "Estimate monthly and daily credit card interest from a balance and annual percentage rate.",
    longDescription: "Estimate monthly and daily credit card interest from a balance and annual percentage rate. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["credit card interest calculator", "credit card interest calculator", "online credit card interest calculator", "finance calculator", "business calculator"],
    icon: "CreditCard",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "credit-card-minimum-payment-calculator",
    name: "Credit Card Minimum Payment Calculator",
    slug: "credit-card-minimum-payment-calculator",
    category: "Finance & Business",
    description: "Estimate a credit card minimum payment using a percentage of balance, a minimum floor, and accrued interest.",
    longDescription: "Estimate a credit card minimum payment using a percentage of balance, a minimum floor, and accrued interest. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["credit card minimum payment calculator", "credit card minimum payment calculator", "online credit card minimum payment calculator", "finance calculator", "business calculator"],
    icon: "ReceiptText",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "pay-raise-calculator",
    name: "Pay Raise Calculator",
    slug: "pay-raise-calculator",
    category: "Finance & Business",
    description: "Calculate a new salary, annual increase, and monthly increase from a current salary and raise percentage.",
    longDescription: "Calculate a new salary, annual increase, and monthly increase from a current salary and raise percentage. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["pay raise calculator", "pay raise calculator", "online pay raise calculator", "finance calculator", "business calculator"],
    icon: "TrendingUp",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "overtime-pay-calculator",
    name: "Overtime Pay Calculator",
    slug: "overtime-pay-calculator",
    category: "Finance & Business",
    description: "Calculate regular pay, overtime pay, and total gross pay from hours, hourly rate, and overtime multiplier.",
    longDescription: "Calculate regular pay, overtime pay, and total gross pay from hours, hourly rate, and overtime multiplier. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["overtime pay calculator", "overtime pay calculator", "online overtime pay calculator", "finance calculator", "business calculator"],
    icon: "TimerReset",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "freelance-rate-calculator",
    name: "Freelance Rate Calculator",
    slug: "freelance-rate-calculator",
    category: "Finance & Business",
    description: "Estimate an hourly freelance rate from target income, billable hours, working weeks, overhead, and tax reserve.",
    longDescription: "Estimate an hourly freelance rate from target income, billable hours, working weeks, overhead, and tax reserve. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["freelance rate calculator", "freelance rate calculator", "online freelance rate calculator", "finance calculator", "business calculator"],
    icon: "BriefcaseBusiness",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "cost-per-unit-calculator",
    name: "Cost Per Unit Calculator",
    slug: "cost-per-unit-calculator",
    category: "Finance & Business",
    description: "Calculate cost per unit by dividing total cost by the number of units produced or purchased.",
    longDescription: "Calculate cost per unit by dividing total cost by the number of units produced or purchased. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["cost per unit calculator", "cost per unit calculator", "online cost per unit calculator", "finance calculator", "business calculator"],
    icon: "Package",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "unit-price-calculator",
    name: "Unit Price Calculator",
    slug: "unit-price-calculator",
    category: "Finance & Business",
    description: "Calculate unit price from package price and quantity for easier product and purchasing comparisons.",
    longDescription: "Calculate unit price from package price and quantity for easier product and purchasing comparisons. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["unit price calculator", "unit price calculator", "online unit price calculator", "finance calculator", "business calculator"],
    icon: "Scale",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "price-per-square-foot-calculator",
    name: "Price Per Square Foot Calculator",
    slug: "price-per-square-foot-calculator",
    category: "Finance & Business",
    description: "Calculate price per square foot from total price and property or project area.",
    longDescription: "Calculate price per square foot from total price and property or project area. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["price per square foot calculator", "price per square foot calculator", "online price per square foot calculator", "finance calculator", "business calculator"],
    icon: "Ruler",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "revenue-growth-calculator",
    name: "Revenue Growth Calculator",
    slug: "revenue-growth-calculator",
    category: "Finance & Business",
    description: "Calculate revenue growth or decline between an earlier period and a later period.",
    longDescription: "Calculate revenue growth or decline between an earlier period and a later period. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["revenue growth calculator", "revenue growth calculator", "online revenue growth calculator", "finance calculator", "business calculator"],
    icon: "ChartNoAxesCombined",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "customer-acquisition-cost-calculator",
    name: "Customer Acquisition Cost Calculator",
    slug: "customer-acquisition-cost-calculator",
    category: "Finance & Business",
    description: "Calculate customer acquisition cost from sales and marketing spend and the number of new customers acquired.",
    longDescription: "Calculate customer acquisition cost from sales and marketing spend and the number of new customers acquired. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["customer acquisition cost calculator", "customer acquisition cost calculator", "online customer acquisition cost calculator", "finance calculator", "business calculator"],
    icon: "UserPlus",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "customer-lifetime-value-calculator",
    name: "Customer Lifetime Value Calculator",
    slug: "customer-lifetime-value-calculator",
    category: "Finance & Business",
    description: "Estimate customer lifetime value from order value, purchase frequency, customer lifespan, and gross margin.",
    longDescription: "Estimate customer lifetime value from order value, purchase frequency, customer lifespan, and gross margin. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["customer lifetime value calculator", "customer lifetime value calculator", "online customer lifetime value calculator", "finance calculator", "business calculator"],
    icon: "Users",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "roas-calculator",
    name: "ROAS Calculator",
    slug: "roas-calculator",
    category: "Finance & Business",
    description: "Calculate return on ad spend from advertising revenue and advertising cost.",
    longDescription: "Calculate return on ad spend from advertising revenue and advertising cost. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["roas calculator", "roas calculator", "online roas calculator", "finance calculator", "business calculator"],
    icon: "Megaphone",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "cpm-calculator",
    name: "CPM Calculator",
    slug: "cpm-calculator",
    category: "Finance & Business",
    description: "Calculate advertising cost per thousand impressions from spend and impression count.",
    longDescription: "Calculate advertising cost per thousand impressions from spend and impression count. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["cpm calculator", "cpm calculator", "online cpm calculator", "finance calculator", "business calculator"],
    icon: "Eye",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "cpc-calculator",
    name: "CPC Calculator",
    slug: "cpc-calculator",
    category: "Finance & Business",
    description: "Calculate average cost per click from advertising spend and click count.",
    longDescription: "Calculate average cost per click from advertising spend and click count. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["cpc calculator", "cpc calculator", "online cpc calculator", "finance calculator", "business calculator"],
    icon: "MousePointerClick",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "cpa-calculator",
    name: "CPA Calculator",
    slug: "cpa-calculator",
    category: "Finance & Business",
    description: "Calculate cost per acquisition from advertising spend and conversion count.",
    longDescription: "Calculate cost per acquisition from advertising spend and conversion count. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["cpa calculator", "cpa calculator", "online cpa calculator", "finance calculator", "business calculator"],
    icon: "Goal",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "conversion-rate-calculator",
    name: "Conversion Rate Calculator",
    slug: "conversion-rate-calculator",
    category: "Finance & Business",
    description: "Calculate conversion rate from total visitors or sessions and completed conversions.",
    longDescription: "Calculate conversion rate from total visitors or sessions and completed conversions. Use the calculator as a planning estimate and verify real-world rates, fees, taxes, terms, and lender or business assumptions before making a financial decision.",
    keywords: ["conversion rate calculator", "conversion rate calculator", "online conversion rate calculator", "finance calculator", "business calculator"],
    icon: "ChartSpline",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: financeFaq,
  },
  {
    id: "title-tag-length-checker",
    name: "Title Tag Length Checker",
    slug: "title-tag-length-checker",
    category: "Developer",
    description: "Check title tag character length and get a quick indication of whether the title falls within a common SEO length range.",
    longDescription: "Check title tag character length and get a quick indication of whether the title falls within a common SEO length range. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["title tag length checker", "title tag length checker", "online title tag length checker", "seo tool", "technical seo"],
    icon: "Heading1",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "meta-description-length-checker",
    name: "Meta Description Length Checker",
    slug: "meta-description-length-checker",
    category: "Developer",
    description: "Check meta description character length and compare it with a common search-snippet length range.",
    longDescription: "Check meta description character length and compare it with a common search-snippet length range. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["meta description length checker", "meta description length checker", "online meta description length checker", "seo tool", "technical seo"],
    icon: "AlignLeft",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "canonical-tag-generator",
    name: "Canonical Tag Generator",
    slug: "canonical-tag-generator",
    category: "Developer",
    description: "Generate a canonical link tag from an absolute webpage URL directly in your browser.",
    longDescription: "Generate a canonical link tag from an absolute webpage URL directly in your browser. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["canonical tag generator", "canonical tag generator", "online canonical tag generator", "seo tool", "technical seo"],
    icon: "Link2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "meta-robots-tag-generator",
    name: "Meta Robots Tag Generator",
    slug: "meta-robots-tag-generator",
    category: "Developer",
    description: "Generate a meta robots tag from index, follow, snippet, preview, and other robots directives.",
    longDescription: "Generate a meta robots tag from index, follow, snippet, preview, and other robots directives. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["meta robots tag generator", "meta robots tag generator", "online meta robots tag generator", "seo tool", "technical seo"],
    icon: "Bot",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "hreflang-validator",
    name: "Hreflang Validator",
    slug: "hreflang-validator",
    category: "Developer",
    description: "Check common hreflang language-region codes, URLs, duplicates, and x-default entries from a pasted list.",
    longDescription: "Check common hreflang language-region codes, URLs, duplicates, and x-default entries from a pasted list. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["hreflang validator", "hreflang validator", "online hreflang validator", "seo tool", "technical seo"],
    icon: "Languages",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "json-ld-validator",
    name: "JSON-LD Validator",
    slug: "json-ld-validator",
    category: "Developer",
    description: "Validate JSON-LD syntax and inspect common structured-data fields such as @context and @type.",
    longDescription: "Validate JSON-LD syntax and inspect common structured-data fields such as @context and @type. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["json-ld validator", "json ld validator", "online json ld validator", "seo tool", "technical seo"],
    icon: "Braces",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "xml-sitemap-validator",
    name: "XML Sitemap Validator",
    slug: "xml-sitemap-validator",
    category: "Developer",
    description: "Validate XML sitemap syntax, identify sitemap type, count URL locations, and flag malformed location URLs.",
    longDescription: "Validate XML sitemap syntax, identify sitemap type, count URL locations, and flag malformed location URLs. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["xml sitemap validator", "xml sitemap validator", "online xml sitemap validator", "seo tool", "technical seo"],
    icon: "FileCode2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "sitemap-url-extractor",
    name: "Sitemap URL Extractor",
    slug: "sitemap-url-extractor",
    category: "Developer",
    description: "Extract every loc URL from an XML sitemap or sitemap index into a clean copyable list.",
    longDescription: "Extract every loc URL from an XML sitemap or sitemap index into a clean copyable list. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["sitemap url extractor", "sitemap url extractor", "online sitemap url extractor", "seo tool", "technical seo"],
    icon: "ListFilter",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "redirect-rule-generator",
    name: "Redirect Rule Generator",
    slug: "redirect-rule-generator",
    category: "Developer",
    description: "Generate common Apache and Nginx redirect rules from a source path, destination URL, and redirect status.",
    longDescription: "Generate common Apache and Nginx redirect rules from a source path, destination URL, and redirect status. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["redirect rule generator", "redirect rule generator", "online redirect rule generator", "seo tool", "technical seo"],
    icon: "Route",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "utm-decoder",
    name: "UTM Decoder",
    slug: "utm-decoder",
    category: "Developer",
    description: "Decode UTM campaign parameters from a URL and inspect source, medium, campaign, term, content, and other parameters.",
    longDescription: "Decode UTM campaign parameters from a URL and inspect source, medium, campaign, term, content, and other parameters. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["utm decoder", "utm decoder", "online utm decoder", "seo tool", "technical seo"],
    icon: "Tags",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "json-schema-validator",
    name: "JSON Schema Validator",
    slug: "json-schema-validator",
    category: "JSON & Data",
    description: "Validate JSON data against common JSON Schema rules including types, required fields, properties, arrays, enums, and ranges.",
    longDescription: "Validate JSON data against common JSON Schema rules including types, required fields, properties, arrays, enums, and ranges. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["json schema validator", "json schema validator", "online json schema validator", "developer tool", "data tool"],
    icon: "FileJson",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "json-escape-unescape",
    name: "JSON Escape / Unescape Tool",
    slug: "json-escape-unescape",
    category: "JSON & Data",
    description: "Escape text for use inside a JSON string or unescape JSON string content directly in your browser.",
    longDescription: "Escape text for use inside a JSON string or unescape JSON string content directly in your browser. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["json escape / unescape tool", "json escape unescape", "online json escape unescape", "developer tool", "data tool"],
    icon: "Braces",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "json-string-converter",
    name: "JSON String Converter",
    slug: "json-string-converter",
    category: "JSON & Data",
    description: "Convert JSON into an escaped JSON string or decode a JSON string back into formatted JSON.",
    longDescription: "Convert JSON into an escaped JSON string or decode a JSON string back into formatted JSON. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["json string converter", "json string converter", "online json string converter", "developer tool", "data tool"],
    icon: "FileJson2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "csv-formatter",
    name: "CSV Formatter",
    slug: "csv-formatter",
    category: "JSON & Data",
    description: "Parse and reformat CSV data with consistent quoting while preserving rows, columns, commas, and embedded line breaks.",
    longDescription: "Parse and reformat CSV data with consistent quoting while preserving rows, columns, commas, and embedded line breaks. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["csv formatter", "csv formatter", "online csv formatter", "developer tool", "data tool"],
    icon: "Table",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "csv-column-extractor",
    name: "CSV Column Extractor",
    slug: "csv-column-extractor",
    category: "JSON & Data",
    description: "Extract one CSV column by header name or 1-based column number and copy the resulting values.",
    longDescription: "Extract one CSV column by header name or 1-based column number and copy the resulting values. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["csv column extractor", "csv column extractor", "online csv column extractor", "developer tool", "data tool"],
    icon: "Columns3",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "csv-duplicate-remover",
    name: "CSV Duplicate Remover",
    slug: "csv-duplicate-remover",
    category: "JSON & Data",
    description: "Remove exact duplicate CSV rows while preserving the first occurrence and the original header row.",
    longDescription: "Remove exact duplicate CSV rows while preserving the first occurrence and the original header row. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["csv duplicate remover", "csv duplicate remover", "online csv duplicate remover", "developer tool", "data tool"],
    icon: "ListX",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "csv-sorter",
    name: "CSV Sorter",
    slug: "csv-sorter",
    category: "JSON & Data",
    description: "Sort CSV rows by a selected header or column number in ascending or descending order.",
    longDescription: "Sort CSV rows by a selected header or column number in ascending or descending order. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["csv sorter", "csv sorter", "online csv sorter", "developer tool", "data tool"],
    icon: "ArrowUpDown",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "tsv-to-csv",
    name: "TSV to CSV Converter",
    slug: "tsv-to-csv",
    category: "JSON & Data",
    description: "Convert tab-separated values to standards-friendly comma-separated values with quoting when needed.",
    longDescription: "Convert tab-separated values to standards-friendly comma-separated values with quoting when needed. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["tsv to csv converter", "tsv to csv", "online tsv to csv", "developer tool", "data tool"],
    icon: "ArrowRightLeft",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "csv-to-tsv",
    name: "CSV to TSV Converter",
    slug: "csv-to-tsv",
    category: "JSON & Data",
    description: "Convert comma-separated values to tab-separated values while preserving quoted fields and embedded text.",
    longDescription: "Convert comma-separated values to tab-separated values while preserving quoted fields and embedded text. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["csv to tsv converter", "csv to tsv", "online csv to tsv", "developer tool", "data tool"],
    icon: "ArrowLeftRight",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
  {
    id: "yaml-validator",
    name: "YAML Validator",
    slug: "yaml-validator",
    category: "JSON & Data",
    description: "Check common YAML syntax issues including tabs, indentation consistency, unbalanced quotes, and bracket mismatches.",
    longDescription: "Check common YAML syntax issues including tabs, indentation consistency, unbalanced quotes, and bracket mismatches. Processing runs locally in a modern browser so the input does not need to be sent to an external conversion or validation service.",
    keywords: ["yaml validator", "yaml validator", "online yaml validator", "developer tool", "data tool"],
    icon: "FileCheck2",
    howToUse: ["Enter the requested values or paste the input into the tool.", "Choose any available options for the calculation or transformation.", "Run the tool and review the result.", "Copy the result or adjust the inputs and run it again."],
    faq: localFaq,
  },
];
