import { tools } from "@/lib/tools-data";

export type ToolCategoryConfig = {
  slug: string;
  name: string;
  description: string;
  intro: string;
  keywords: string[];
  toolSlugs: string[];
};

export const toolCategories: ToolCategoryConfig[] = [
  {
    slug: "json",
    name: "JSON & Data Tools",
    description:
      "Format, validate, minify, convert, and work with JSON and structured data directly in your browser.",
    intro:
      "Avorqin's JSON and data tools help you format, validate, minify, and convert structured data for APIs, configuration files, exports, and everyday development workflows.",
    keywords: [
      "JSON tools",
      "JSON formatter",
      "JSON validator",
      "JSON minifier",
      "JSON converter",
      "JSON to CSV",
      "JSON to YAML",
      "XML to JSON",
    ],
    toolSlugs: [
      "json-formatter",
      "json-validator",
      "json-minifier",
      "csv-to-json",
      "json-to-csv",
      "yaml-to-json",
      "json-to-yaml",
      "xml-to-json",
      "json-to-xml",
      "json-to-typescript",
      "jsonpath-tester",
      "json-diff",
      "json-schema-validator",
      "json-escape-unescape",
      "json-string-converter",
      "csv-formatter",
      "csv-column-extractor",
      "csv-duplicate-remover",
      "csv-sorter",
      "tsv-to-csv",
      "csv-to-tsv",
      "yaml-validator",
      "csv-to-sql-converter",
      "json-to-sql-converter",
      "sql-to-json-converter",
      "xml-to-csv-converter",
      "csv-to-xml-converter",
      "json-to-toml-converter",
      "toml-to-json-converter",
      "yaml-to-toml-converter",
      "toml-to-yaml-converter",
      "json-flattener",
      "json-unflattener",
      "csv-delimiter-converter",
      "csv-row-filter",
      "csv-column-remover",
      "csv-merge-tool",
      "ini-to-json-converter",
      "json-to-php-array-converter",
      "php-array-to-json-converter",
      "json-to-python-dict-converter",
      "python-dict-to-json-converter",
      "json-to-csharp-class-generator",
      "json-to-java-class-generator",
      "json-to-go-struct-generator",
      "json-to-rust-struct-generator",
      "json-to-kotlin-data-class-generator",
      "json-to-swift-codable-generator",
      "csv-to-markdown-table-converter",
      "markdown-table-to-csv-converter",
      "html-table-to-markdown-converter",
      "markdown-table-to-html-converter",
      "sql-to-csv-converter",
      "csv-to-jsonl-converter",
      "jsonl-to-csv-converter",
      "jsonl-formatter",
      "jsonl-validator",
      "yaml-to-xml-converter",
      "xml-to-yaml-converter",
      "env-to-json-converter",
      "json-to-env-converter",
      "properties-to-json-converter",
      "json-to-properties-converter",
      "regex-escape-tool",
      "cron-next-run-calculator",
      "semantic-version-comparator",
      "semantic-version-bump-calculator",
      "cache-control-header-builder",
      "cors-header-generator",
      "csp-header-parser",
      "htaccess-redirect-generator",
      "nginx-redirect-generator",
      "ip-range-calculator",
      "cidr-to-ip-range-converter",
      "ipv6-subnet-calculator",
      "dns-ttl-converter",
      "dns-record-parser",
      "base32-encoder",
      "base32-decoder",
      "base58-encoder",
      "base58-decoder",
      "tsv-to-json-converter",
      "json-to-tsv-converter",
      "csv-to-yaml-converter",
      "yaml-to-csv-converter",
      "json-pointer-tester",
      "json-patch-generator",
      "json-merge-patch-tool",
      "http-basic-auth-header-generator",
      "content-disposition-header-generator",
      "url-query-parameter-sorter",
      "url-normalizer",
      "sql-create-table-generator",
    ],
  },

  {
    slug: "formatters",
    name: "Code Formatters",
    description:
      "Format, beautify, minify, and clean up JSON, HTML, CSS, YAML, XML, SQL, and JavaScript.",
    intro:
      "Clean up hard-to-read code and structured data with browser-based formatters and minifiers for common developer formats.",
    keywords: [
      "code formatter",
      "code beautifier",
      "JSON formatter",
      "HTML formatter",
      "CSS formatter",
      "YAML formatter",
      "XML formatter",
      "SQL formatter",
      "code minifier",
    ],
    toolSlugs: [
      "json-formatter",
      "html-formatter",
      "css-formatter",
      "yaml-formatter",
      "xml-formatter",
      "sql-formatter",
      "json-minifier",
      "css-minifier",
      "html-minifier",
      "javascript-minifier",
      "csv-formatter",
      "yaml-validator",
      "html-tag-stripper",
      "diacritic-remover",
      "add-line-numbers",
      "remove-line-numbers",
    ],
  },

  {
    slug: "converters",
    name: "Developer Converters",
    description:
      "Convert data formats, number bases, text encodings, measurements, storage units, dimensions, rates, and color values online.",
    intro:
      "Convert common developer formats and representations without installing software. Avorqin converters run directly in your browser for fast everyday transformations.",
    keywords: [
      "developer converters",
      "data converter",
      "JSON converter",
      "YAML converter",
      "XML converter",
      "binary converter",
      "hex converter",
      "unit converter",
      "length converter",
      "temperature converter",
      "data rate converter",
      "ASCII converter",
      "color converter",
    ],
    toolSlugs: [
      "csv-to-json",
      "json-to-csv",
      "yaml-to-json",
      "json-to-yaml",
      "xml-to-json",
      "json-to-xml",
      "timestamp-converter",
      "unix-timestamp-to-date",
      "number-base-converter",
      "binary-to-text",
      "text-to-binary",
      "hex-to-text",
      "text-to-hex",
      "hex-to-rgb",
      "rgb-to-hex",
      "rem-to-px-converter",
      "px-to-rem-converter",
      "em-to-px-converter",
      "bytes-converter",
      "url-slug-decoder",
      "fraction-to-percentage-calculator",
      "percentage-to-fraction-calculator",
      "decimal-to-percentage-calculator",
      "percentage-to-decimal-calculator",
      "length-converter",
      "weight-converter",
      "temperature-converter",
      "area-converter",
      "volume-converter",
      "speed-converter",
      "time-converter",
      "pressure-converter",
      "energy-converter",
      "power-converter",
      "frequency-converter",
      "angle-converter",
      "data-rate-converter",
      "fuel-economy-converter",
      "ascii-to-text-converter",
      "text-to-ascii-converter",
      "tsv-to-csv",
      "csv-to-tsv",
      "html-table-to-csv",
      "csv-to-html-table",
      "ipv4-to-integer",
      "integer-to-ipv4",
      "ipv6-compressor",
      "ipv6-expander",
      "unicode-escape-converter",
      "inches-to-centimeters-converter",
      "centimeters-to-inches-converter",
      "feet-to-meters-converter",
      "meters-to-feet-converter",
      "miles-to-kilometers-converter",
      "kilometers-to-miles-converter",
      "pounds-to-kilograms-converter",
      "kilograms-to-pounds-converter",
      "ounces-to-grams-converter",
      "grams-to-ounces-converter",
      "cups-to-milliliters-converter",
      "milliliters-to-cups-converter",
      "gallons-to-liters-converter",
      "liters-to-gallons-converter",
      "celsius-to-fahrenheit-converter",
      "fahrenheit-to-celsius-converter",
      "mph-to-kmh-converter",
      "kmh-to-mph-converter",
      "mb-to-gb-converter",
      "gb-to-mb-converter",
      "va-to-watts-calculator",
      "watts-to-va-calculator",
      "kva-to-amps-calculator",
      "amps-to-kva-calculator",
      "kva-to-watts-calculator",
      "watts-to-kva-calculator",
      "kva-to-kw-calculator",
      "kw-to-kva-calculator",
      "volts-to-kw-calculator",
      "kw-to-volts-calculator",
      "ohms-to-amps-calculator",
      "amps-to-ohms-calculator",
      "volts-to-ohms-calculator",
      "ohms-to-volts-calculator",
      "watts-to-ohms-calculator",
      "ohms-to-watts-calculator",
      "ah-to-wh-calculator",
      "wh-to-ah-calculator",
      "horsepower-to-watts-calculator",
      "watts-to-horsepower-calculator",
      "ac-amps-to-watts-calculator",
      "dc-amps-to-watts-calculator",
      "single-phase-amps-to-watts-calculator",
      "three-phase-amps-to-watts-calculator",
      "12v-amps-to-watts-calculator",
      "24v-amps-to-watts-calculator",
      "48v-amps-to-watts-calculator",
      "120v-amps-to-watts-calculator",
      "230v-amps-to-watts-calculator",
      "240v-amps-to-watts-calculator",
      "12v-watts-to-amps-calculator",
      "24v-watts-to-amps-calculator",
      "48v-watts-to-amps-calculator",
      "120v-watts-to-amps-calculator",
      "230v-watts-to-amps-calculator",
      "240v-watts-to-amps-calculator",
      "watts-to-kwh-per-day-calculator",
      "monthly-electricity-usage-calculator",
      "annual-electricity-cost-calculator",
      "energy-cost-per-hour-calculator",
      "frequency-to-period-calculator",
      "period-to-frequency-calculator",
      "wavelength-calculator",
      "dbm-to-watts-calculator",
      "watts-to-dbm-calculator",
      "dbw-to-watts-calculator",
      "watts-to-dbw-calculator",
      "rms-voltage-calculator",
      "peak-voltage-calculator",
      "peak-to-peak-voltage-calculator",
      "px-to-em-converter",
      "rem-to-em-converter",
      "em-to-rem-converter",
      "pt-to-px-converter",
      "px-to-pt-converter",
      "vw-to-px-converter",
      "px-to-vw-converter",
      "vh-to-px-converter",
      "px-to-vh-converter",
      "csv-to-sql-converter",
      "json-to-sql-converter",
      "sql-to-json-converter",
      "xml-to-csv-converter",
      "csv-to-xml-converter",
      "json-to-toml-converter",
      "toml-to-json-converter",
      "yaml-to-toml-converter",
      "toml-to-yaml-converter",
      "csv-delimiter-converter",
      "ini-to-json-converter",
      "json-to-php-array-converter",
      "php-array-to-json-converter",
      "json-to-python-dict-converter",
      "python-dict-to-json-converter",
      "json-to-csharp-class-generator",
      "json-to-java-class-generator",
      "json-to-go-struct-generator",
      "json-to-rust-struct-generator",
      "json-to-kotlin-data-class-generator",
      "json-to-swift-codable-generator",
      "csv-to-markdown-table-converter",
      "markdown-table-to-csv-converter",
      "html-table-to-markdown-converter",
      "markdown-table-to-html-converter",
      "sql-to-csv-converter",
      "csv-to-jsonl-converter",
      "jsonl-to-csv-converter",
      "jsonl-formatter",
      "jsonl-validator",
      "yaml-to-xml-converter",
      "xml-to-yaml-converter",
      "env-to-json-converter",
      "json-to-env-converter",
      "properties-to-json-converter",
      "json-to-properties-converter",
      "regex-escape-tool",
      "cron-next-run-calculator",
      "semantic-version-comparator",
      "semantic-version-bump-calculator",
      "cache-control-header-builder",
      "cors-header-generator",
      "csp-header-parser",
      "htaccess-redirect-generator",
      "nginx-redirect-generator",
      "ip-range-calculator",
      "cidr-to-ip-range-converter",
      "ipv6-subnet-calculator",
      "dns-ttl-converter",
      "dns-record-parser",
      "base32-encoder",
      "base32-decoder",
      "base58-encoder",
      "base58-decoder",
      "tsv-to-json-converter",
      "json-to-tsv-converter",
      "csv-to-yaml-converter",
      "yaml-to-csv-converter",
      "json-pointer-tester",
      "json-patch-generator",
      "json-merge-patch-tool",
      "http-basic-auth-header-generator",
      "content-disposition-header-generator",
      "url-query-parameter-sorter",
      "url-normalizer",
      "sql-create-table-generator",
    ],
  },

  {
    slug: "encode-decode",
    name: "Encode & Decode Tools",
    description:
      "Encode and decode Base64, URLs, HTML entities, JWTs, binary, hexadecimal text, and URL slugs.",
    intro:
      "Encode, decode, and inspect common web and developer formats quickly. These utilities are useful for debugging payloads, inspecting encoded strings, and transforming text representations.",
    keywords: [
      "encode decode tools",
      "Base64 encoder",
      "Base64 decoder",
      "URL encoder",
      "URL decoder",
      "HTML encoder",
      "JWT decoder",
      "binary decoder",
      "hex decoder",
    ],
    toolSlugs: [
      "base64-encoder",
      "base64-decoder",
      "url-encoder",
      "url-decoder",
      "html-encoder",
      "html-decoder",
      "binary-to-text",
      "text-to-binary",
      "hex-to-text",
      "text-to-hex",
      "jwt-decoder",
      "url-slug-decoder",
      "ascii-to-text-converter",
      "text-to-ascii-converter",
      "punycode-encoder",
      "punycode-decoder",
    ],
  },

  {
    slug: "generators",
    name: "Developer Generators",
    description:
      "Generate UUIDs, hashes, HMACs, passwords, random strings, QR codes, MAC addresses, placeholder text, and URL slugs.",
    intro:
      "Generate common development values instantly with browser-based utilities for identifiers, hashes, secure random values, QR codes, test data, placeholder copy, and clean URL slugs.",
    keywords: [
      "developer generators",
      "UUID generator",
      "hash generator",
      "password generator",
      "random string generator",
      "HMAC generator",
      "QR code generator",
      "MAC address generator",
      "slug generator",
    ],
    toolSlugs: [
      "uuid-generator",
      "uuid-validator",
      "qr-code-generator",
      "mac-address-generator",
      "sha256-hash-generator",
      "sha1-hash-generator",
      "sha512-hash-generator",
      "hmac-generator",
      "random-string-generator",
      "password-generator",
      "lorem-ipsum-generator",
      "slug-generator",
      "unix-timestamp-generator",
      "sql-insert-generator",
    ],
  },

  {
    slug: "web-code",
    name: "Web & Code Tools",
    description:
      "Inspect URLs, query strings, JWTs, regular expressions, cron expressions, HTTP data, Markdown, user agents, and text.",
    intro:
      "A collection of practical web and code utilities for inspecting, testing, transforming, and debugging common developer inputs directly in your browser.",
    keywords: [
      "web developer tools",
      "URL parser",
      "query string parser",
      "regex tester",
      "cron expression helper",
      "JWT decoder",
      "HTTP status lookup",
      "MIME type lookup",
      "user agent parser",
      "Markdown previewer",
      "text tools",
    ],
    toolSlugs: [
      "url-parser",
      "query-string-parser",
      "query-string-builder",
      "regex-tester",
      "cron-expression-helper",
      "jwt-decoder",
      "markdown-previewer",
      "text-diff-checker",
      "text-case-converter",
      "word-character-counter",
      "line-sorter",
      "duplicate-line-remover",
      "whitespace-cleaner",
      "text-reverser",
      "http-status-code-lookup",
      "mime-type-lookup",
      "user-agent-parser",
      "ip-subnet-calculator",
      "markdown-to-html",
      "html-to-markdown",
      "html-tag-stripper",
      "html-table-generator",
      "html-table-to-csv",
      "csv-to-html-table",
      "css-specificity-calculator",
      "css-clamp-calculator",
      "css-box-shadow-generator",
      "css-border-radius-generator",
      "css-flexbox-generator",
      "css-grid-generator",
      "ipv4-to-integer",
      "integer-to-ipv4",
      "ipv6-compressor",
      "ipv6-expander",
      "mac-address-validator",
      "domain-name-parser",
      "port-number-lookup",
      "http-header-parser",
      "cookie-parser",
      "csp-generator",
      "reading-time-calculator",
      "speaking-time-calculator",
      "word-frequency-counter",
      "character-frequency-counter",
      "invisible-character-detector",
      "unicode-character-inspector",
      "unicode-escape-converter",
      "diacritic-remover",
      "add-line-numbers",
      "remove-line-numbers",
      "utf8-byte-counter",
      "xpath-tester",
      "sql-insert-generator",
      "chmod-calculator",
      "ini-to-json-converter",
      "json-to-php-array-converter",
      "php-array-to-json-converter",
      "json-to-python-dict-converter",
      "python-dict-to-json-converter",
      "json-to-csharp-class-generator",
      "json-to-java-class-generator",
      "json-to-go-struct-generator",
      "json-to-rust-struct-generator",
      "json-to-kotlin-data-class-generator",
      "json-to-swift-codable-generator",
      "csv-to-markdown-table-converter",
      "markdown-table-to-csv-converter",
      "html-table-to-markdown-converter",
      "markdown-table-to-html-converter",
      "sql-to-csv-converter",
      "csv-to-jsonl-converter",
      "jsonl-to-csv-converter",
      "jsonl-formatter",
      "jsonl-validator",
      "yaml-to-xml-converter",
      "xml-to-yaml-converter",
      "env-to-json-converter",
      "json-to-env-converter",
      "properties-to-json-converter",
      "json-to-properties-converter",
      "regex-escape-tool",
      "cron-next-run-calculator",
      "semantic-version-comparator",
      "semantic-version-bump-calculator",
      "cache-control-header-builder",
      "cors-header-generator",
      "csp-header-parser",
      "htaccess-redirect-generator",
      "nginx-redirect-generator",
      "ip-range-calculator",
      "cidr-to-ip-range-converter",
      "ipv6-subnet-calculator",
      "dns-ttl-converter",
      "dns-record-parser",
      "base32-encoder",
      "base32-decoder",
      "base58-encoder",
      "base58-decoder",
      "tsv-to-json-converter",
      "json-to-tsv-converter",
      "csv-to-yaml-converter",
      "yaml-to-csv-converter",
      "json-pointer-tester",
      "json-patch-generator",
      "json-merge-patch-tool",
      "http-basic-auth-header-generator",
      "content-disposition-header-generator",
      "url-query-parameter-sorter",
      "url-normalizer",
      "sql-create-table-generator",
    ],
  },

  {
    slug: "seo",
    name: "SEO & Marketing Tools",
    description:
      "Generate and inspect meta tags, search snippets, Open Graph metadata, robots.txt rules, sitemaps, schema markup, UTM links, keywords, and headings.",
    intro:
      "Avorqin's SEO and marketing tools help site owners, developers, marketers, and content teams create and inspect common technical SEO and campaign data directly in the browser. Generate metadata, structured data, robots.txt rules, XML sitemaps, hreflang tags, tracking URLs, and content checks without installing software.",
    keywords: [
      "SEO tools",
      "meta tag generator",
      "SERP preview",
      "Open Graph preview",
      "robots.txt generator",
      "robots.txt tester",
      "XML sitemap generator",
      "schema markup generator",
      "FAQ schema generator",
      "hreflang generator",
      "UTM builder",
      "keyword density checker",
      "heading structure analyzer",
    ],
    toolSlugs: [
      "meta-tag-generator",
      "serp-preview",
      "open-graph-preview",
      "robots-txt-generator",
      "robots-txt-tester",
      "xml-sitemap-generator",
      "schema-markup-generator",
      "faq-schema-generator",
      "hreflang-generator",
      "utm-builder",
      "keyword-density-checker",
      "heading-structure-analyzer",
      "title-tag-length-checker",
      "meta-description-length-checker",
      "canonical-tag-generator",
      "meta-robots-tag-generator",
      "hreflang-validator",
      "json-ld-validator",
      "xml-sitemap-validator",
      "sitemap-url-extractor",
      "redirect-rule-generator",
      "utm-decoder",
    ],
  },



  {
    slug: "math",
    name: "Math Tools",
    description:
      "Solve scientific expressions, fractions, statistics, number theory, equations, coordinate geometry, triangles, and random-number problems.",
    intro:
      "Avorqin's math tools help students, developers, professionals, and everyday users solve common calculations directly in the browser. Evaluate scientific expressions, work with fractions and statistics, calculate GCD and LCM, solve quadratic equations, analyze coordinate geometry, use the Pythagorean theorem, and generate random numbers.",
    keywords: [
      "math tools",
      "scientific calculator",
      "fraction calculator",
      "standard deviation calculator",
      "mean median mode calculator",
      "GCD calculator",
      "LCM calculator",
      "quadratic formula calculator",
      "slope calculator",
      "midpoint calculator",
      "distance formula calculator",
      "pythagorean theorem calculator",
      "random number generator",
    ],
    toolSlugs: [
      "scientific-calculator",
      "fraction-calculator",
      "standard-deviation-calculator",
      "mean-median-mode-calculator",
      "gcd-calculator",
      "lcm-calculator",
      "quadratic-formula-calculator",
      "slope-calculator",
      "midpoint-calculator",
      "distance-formula-calculator",
      "pythagorean-theorem-calculator",
      "random-number-generator",
      "prime-number-checker",
      "prime-factorization-calculator",
      "percentage-error-calculator",
      "permutation-calculator",
      "combination-calculator",
      "probability-calculator",
      "z-score-calculator",
      "weighted-average-calculator",
      "geometric-mean-calculator",
      "harmonic-mean-calculator",
      "triangle-calculator",
      "circle-calculator",
      "rectangle-calculator",
      "cylinder-volume-calculator",
      "sphere-volume-calculator",
      "cone-volume-calculator",
      "ohms-law-calculator",
      "voltage-divider-calculator",
      "resistor-color-code-calculator",
      "led-resistor-calculator",
      "matrix-determinant-calculator",
      "matrix-multiplication-calculator",
      "matrix-inverse-calculator",
      "linear-equation-solver",
      "system-of-equations-solver",
      "logarithm-calculator",
      "exponent-calculator",
      "square-root-calculator",
      "cube-root-calculator",
      "factorial-calculator",
      "modulo-calculator",
      "remainder-calculator",
      "proportion-calculator",
      "decimal-to-fraction-calculator",
      "mixed-number-calculator",
      "fraction-simplifier",
      "percent-difference-calculator",
      "quartile-calculator",
      "interquartile-range-calculator",
      "ratio-to-percentage-calculator",
      "linear-interpolation-calculator",
      "standard-error-calculator",
      "variance-calculator",
      "coefficient-of-variation-calculator",
      "range-calculator",
      "fraction-to-decimal-calculator",
      "scientific-notation-calculator",
      "significant-figures-calculator",
      "rounding-calculator",
      "arithmetic-sequence-calculator",
      "geometric-sequence-calculator",
      "binomial-probability-calculator",
      "expected-value-calculator",
      "percentile-calculator",
      "percentile-rank-calculator",
      "normal-distribution-calculator",
      "confidence-interval-calculator",
      "margin-of-error-calculator",
      "sample-size-calculator",
      "correlation-coefficient-calculator",
      "covariance-calculator",
      "linear-regression-calculator",
      "arc-length-calculator",
      "sector-area-calculator",
      "ellipse-calculator",
      "trapezoid-calculator",
      "polygon-area-calculator",
      "root-mean-square-calculator",
      "sum-of-squares-calculator",
      "t-statistic-calculator",
      "p-value-calculator",
      "chi-square-calculator",
      "one-way-anova-calculator",
      "hypergeometric-calculator",
      "poisson-distribution-calculator",
      "exponential-distribution-calculator",
      "uniform-distribution-calculator",
      "beta-distribution-calculator",
      "gamma-distribution-calculator",
      "weibull-distribution-calculator",
      "lognormal-distribution-calculator",
      "geometric-distribution-calculator",
      "negative-binomial-calculator",
      "mean-absolute-deviation-calculator",
      "median-absolute-deviation-calculator",
      "weighted-standard-deviation-calculator",
      "root-mean-square-error-calculator",
      "mean-absolute-error-calculator",
      "mape-calculator",
      "r-squared-calculator",
      "vector-magnitude-calculator",
      "dot-product-calculator",
      "cross-product-calculator",
      "complex-number-calculator",
      "polynomial-degree-calculator",
      "skewness-calculator",
      "kurtosis-calculator",
      "weighted-variance-calculator",
      "matrix-trace-calculator",
      "matrix-transpose-calculator",
      "vector-angle-calculator",
      "cosine-similarity-calculator",
    ],
  },

  {
    slug: "finance",
    name: "Finance & Business Tools",
    description:
      "Calculate mortgages, loans, interest, ROI, margins, markup, break-even points, commissions, salary conversions, growth rates, and savings goals.",
    intro:
      "Avorqin's finance and business tools provide quick browser-based estimates for borrowing, saving, pricing, profitability, compensation, and business planning. Enter your own values to calculate mortgage and loan payments, interest, ROI, margins, markup, break-even points, commissions, salary conversions, CAGR, and savings targets.",
    keywords: [
      "finance tools",
      "business calculators",
      "mortgage calculator",
      "loan calculator",
      "compound interest calculator",
      "simple interest calculator",
      "ROI calculator",
      "profit margin calculator",
      "markup calculator",
      "break even calculator",
      "commission calculator",
      "CAGR calculator",
      "salary calculator",
      "savings goal calculator",
    ],
    toolSlugs: [
      "mortgage-calculator",
      "loan-calculator",
      "compound-interest-calculator",
      "simple-interest-calculator",
      "roi-calculator",
      "profit-margin-calculator",
      "markup-calculator",
      "break-even-calculator",
      "gross-profit-calculator",
      "commission-calculator",
      "cagr-calculator",
      "hourly-to-salary-calculator",
      "salary-to-hourly-calculator",
      "savings-goal-calculator",
      "auto-loan-calculator",
      "credit-card-payoff-calculator",
      "debt-payoff-calculator",
      "debt-snowball-calculator",
      "debt-avalanche-calculator",
      "apr-calculator",
      "apy-calculator",
      "debt-to-income-ratio-calculator",
      "loan-amortization-calculator",
      "rule-of-72-calculator",
      "rent-vs-buy-calculator",
      "down-payment-calculator",
      "mortgage-refinance-calculator",
      "biweekly-mortgage-calculator",
      "credit-card-interest-calculator",
      "credit-card-minimum-payment-calculator",
      "pay-raise-calculator",
      "overtime-pay-calculator",
      "freelance-rate-calculator",
      "cost-per-unit-calculator",
      "unit-price-calculator",
      "price-per-square-foot-calculator",
      "revenue-growth-calculator",
      "customer-acquisition-cost-calculator",
      "customer-lifetime-value-calculator",
      "roas-calculator",
      "cpm-calculator",
      "cpc-calculator",
      "cpa-calculator",
      "conversion-rate-calculator",
      "average-order-value-calculator",
      "click-through-rate-calculator",
      "cost-per-lead-calculator",
      "lead-conversion-rate-calculator",
      "email-open-rate-calculator",
      "email-click-through-rate-calculator",
      "ecommerce-profit-calculator",
      "gmroi-calculator",
      "inventory-turnover-calculator",
      "reorder-point-calculator",
      "safety-stock-calculator",
      "economic-order-quantity-calculator",
      "sell-through-rate-calculator",
      "cart-abandonment-rate-calculator",
      "engagement-rate-calculator",
      "churn-rate-calculator",
      "retention-rate-calculator",
      "mrr-calculator",
      "arr-calculator",
      "mrr-growth-calculator",
      "ltv-to-cac-ratio-calculator",
      "cac-payback-period-calculator",
      "payback-period-calculator",
      "contribution-margin-calculator",
      "operating-margin-calculator",
      "ebitda-margin-calculator",
      "cost-of-goods-sold-calculator",
      "average-revenue-per-user-calculator",
      "ad-spend-calculator",
      "target-roas-calculator",
      "mortgage-extra-payment-calculator",
      "pmi-calculator",
      "mortgage-points-calculator",
      "closing-cost-calculator",
      "home-affordability-calculator",
      "heloc-payment-calculator",
      "balloon-loan-calculator",
      "interest-only-loan-calculator",
      "student-loan-calculator",
      "car-lease-calculator",
      "present-value-calculator",
      "annuity-payment-calculator",
      "retirement-savings-calculator",
      "401k-calculator",
      "roth-ira-calculator",
      "inflation-calculator",
      "cd-calculator",
      "net-worth-calculator",
      "emergency-fund-calculator",
      "current-ratio-calculator",
      "business-burn-rate-calculator",
      "cash-runway-calculator",
      "working-capital-calculator",
      "debt-service-coverage-ratio-calculator",
      "cap-rate-calculator",
      "cash-on-cash-return-calculator",
      "rental-property-roi-calculator",
      "rental-yield-calculator",
      "gross-rent-multiplier-calculator",
      "loan-to-value-calculator",
      "home-equity-calculator",
      "sinking-fund-calculator",
      "bond-yield-calculator",
      "bond-price-calculator",
      "dividend-yield-calculator",
      "dividend-reinvestment-calculator",
      "stock-average-calculator",
      "risk-reward-ratio-calculator",
      "pe-ratio-calculator",
      "peg-ratio-calculator",
      "earnings-per-share-calculator",
      "return-on-assets-calculator",
      "return-on-equity-calculator",
      "npv-calculator",
      "irr-calculator",
      "mirr-calculator",
      "wacc-calculator",
      "capm-calculator",
      "sharpe-ratio-calculator",
      "sortino-ratio-calculator",
      "cash-ratio-calculator",
      "interest-coverage-ratio-calculator",
      "asset-turnover-calculator",
      "cash-conversion-cycle-calculator",
    ],
  },


  {
    slug: "date-time",
    name: "Date & Time Tools",
    description:
      "Calculate business days, working hours, date adjustments, time-zone conversions, and durations between dates and times.",
    intro:
      "Avorqin's date and time tools help you count working days, calculate hours, add or subtract calendar time, convert between common time zones, and measure elapsed time between dates and times directly in your browser.",
    keywords: [
      "date and time tools",
      "business days calculator",
      "working days calculator",
      "hours calculator",
      "date calculator",
      "add days to date",
      "timezone converter",
      "time zone converter",
      "time duration calculator",
      "elapsed time calculator",
    ],
    toolSlugs: [
      "business-days-calculator",
      "hours-calculator",
      "date-add-subtract-calculator",
      "timezone-converter",
      "time-duration-calculator",
      "days-from-today-calculator",
      "weeks-from-today-calculator",
      "months-from-today-calculator",
      "hours-from-now-calculator",
      "minutes-from-now-calculator",
      "week-number-calculator",
      "day-of-week-calculator",
      "day-of-year-calculator",
      "leap-year-calculator",
      "business-date-calculator",
      "time-zone-difference-calculator",
      "meeting-time-planner",
      "iso-week-date-converter",
      "julian-date-converter",
      "epoch-milliseconds-converter",
      "unix-time-to-iso-8601-converter",
      "iso-8601-to-unix-time-converter",
      "time-zone-offset-converter",
      "working-days-from-today-calculator",
      "weekend-days-calculator",
      "time-card-calculator",
      "shift-length-calculator",
      "overtime-hours-calculator",
      "decimal-hours-calculator",
      "date-midpoint-calculator",
      "nth-weekday-calculator",
      "fiscal-quarter-calculator",
      "quarter-end-date-calculator",
      "unix-nanoseconds-converter",
      "iso-duration-calculator",
    ],
  },

  {
    slug: "calculators",
    name: "Developer Calculators",
    description:
      "Calculate averages, ratios, percentages, discounts, sales tax, tips, dates, age, resolutions, network values, data transfer times, and more.",
    intro:
      "Avorqin's calculators provide quick browser-based answers for everyday development, design, networking, date, percentage, storage, and data-transfer calculations.",
    keywords: [
      "developer calculators",
      "percentage calculator",
      "percentage change calculator",
      "average calculator",
      "ratio calculator",
      "discount calculator",
      "sales tax calculator",
      "tip calculator",
      "date difference calculator",
      "age calculator",
      "aspect ratio calculator",
      "screen resolution calculator",
      "subnet calculator",
      "data transfer calculator",
    ],
    toolSlugs: [
      "date-difference-calculator",
      "age-calculator",
      "percentage-calculator",
      "percentage-change-calculator",
      "aspect-ratio-calculator",
      "screen-resolution-calculator",
      "ip-subnet-calculator",
      "data-transfer-time-calculator",
      "bytes-converter",
      "rem-to-px-converter",
      "px-to-rem-converter",
      "em-to-px-converter",
      "average-calculator",
      "ratio-calculator",
      "fraction-to-percentage-calculator",
      "percentage-to-fraction-calculator",
      "decimal-to-percentage-calculator",
      "percentage-to-decimal-calculator",
      "discount-calculator",
      "sales-tax-calculator",
      "tip-calculator",
      "reading-time-calculator",
      "speaking-time-calculator",
      "prime-number-checker",
      "prime-factorization-calculator",
      "percentage-error-calculator",
      "permutation-calculator",
      "combination-calculator",
      "probability-calculator",
      "z-score-calculator",
      "weighted-average-calculator",
      "geometric-mean-calculator",
      "harmonic-mean-calculator",
      "triangle-calculator",
      "circle-calculator",
      "rectangle-calculator",
      "cylinder-volume-calculator",
      "sphere-volume-calculator",
      "cone-volume-calculator",
      "ohms-law-calculator",
      "voltage-divider-calculator",
      "resistor-color-code-calculator",
      "led-resistor-calculator",
      "square-footage-calculator",
      "concrete-calculator",
      "concrete-slab-calculator",
      "concrete-bag-calculator",
      "cubic-yard-calculator",
      "gravel-calculator",
      "mulch-calculator",
      "topsoil-calculator",
      "sand-calculator",
      "brick-calculator",
      "concrete-block-calculator",
      "drywall-calculator",
      "paint-calculator",
      "wallpaper-calculator",
      "flooring-calculator",
      "tile-calculator",
      "carpet-calculator",
      "decking-calculator",
      "fence-calculator",
      "roofing-calculator",
      "roof-pitch-calculator",
      "rafter-length-calculator",
      "roof-shingle-calculator",
      "stair-calculator",
      "board-foot-calculator",
      "lumber-calculator",
      "stud-calculator",
      "insulation-calculator",
      "paver-calculator",
      "asphalt-calculator",
      "room-area-calculator",
      "wall-area-calculator",
      "ceiling-area-calculator",
      "cubic-feet-calculator",
      "square-feet-to-cubic-yards-calculator",
      "grout-calculator",
      "mortar-calculator",
      "thinset-calculator",
      "rebar-calculator",
      "pool-volume-calculator",
      "tank-volume-calculator",
      "pipe-volume-calculator",
      "gpm-calculator",
      "flow-rate-calculator",
      "deck-stain-calculator",
      "epoxy-calculator",
      "crushed-stone-calculator",
      "road-base-calculator",
      "gravel-driveway-calculator",
      "fence-post-depth-calculator",
      "watts-to-amps-calculator",
      "amps-to-watts-calculator",
      "volts-to-watts-calculator",
      "watts-to-volts-calculator",
      "amps-to-volts-calculator",
      "volts-to-amps-calculator",
      "kw-to-amps-calculator",
      "amps-to-kw-calculator",
      "kw-to-kwh-calculator",
      "kwh-to-kw-calculator",
      "watts-to-kwh-calculator",
      "kwh-to-watts-calculator",
      "mah-to-wh-calculator",
      "wh-to-mah-calculator",
      "battery-life-calculator",
      "battery-capacity-calculator",
      "power-factor-calculator",
      "voltage-drop-calculator",
      "wire-gauge-calculator",
      "series-resistor-calculator",
      "parallel-resistor-calculator",
      "capacitor-series-calculator",
      "capacitor-parallel-calculator",
      "rc-time-constant-calculator",
      "transformer-calculator",
      "joules-to-watts-calculator",
      "watts-to-joules-calculator",
      "lumens-to-watts-calculator",
      "watts-to-lumens-calculator",
      "lux-to-lumens-calculator",
      "gpa-calculator",
      "weighted-gpa-calculator",
      "high-school-gpa-calculator",
      "college-gpa-calculator",
      "grade-calculator",
      "final-grade-calculator",
      "weighted-grade-calculator",
      "test-grade-calculator",
      "semester-gpa-calculator",
      "cumulative-gpa-calculator",
      "matrix-determinant-calculator",
      "matrix-multiplication-calculator",
      "matrix-inverse-calculator",
      "linear-equation-solver",
      "system-of-equations-solver",
      "logarithm-calculator",
      "exponent-calculator",
      "square-root-calculator",
      "cube-root-calculator",
      "factorial-calculator",
      "average-order-value-calculator",
      "click-through-rate-calculator",
      "cost-per-lead-calculator",
      "lead-conversion-rate-calculator",
      "email-open-rate-calculator",
      "email-click-through-rate-calculator",
      "ecommerce-profit-calculator",
      "gmroi-calculator",
      "inventory-turnover-calculator",
      "reorder-point-calculator",
      "safety-stock-calculator",
      "economic-order-quantity-calculator",
      "sell-through-rate-calculator",
      "cart-abandonment-rate-calculator",
      "engagement-rate-calculator",
      "churn-rate-calculator",
      "retention-rate-calculator",
      "mrr-calculator",
      "arr-calculator",
      "mrr-growth-calculator",
      "ltv-to-cac-ratio-calculator",
      "cac-payback-period-calculator",
      "payback-period-calculator",
      "contribution-margin-calculator",
      "operating-margin-calculator",
      "ebitda-margin-calculator",
      "cost-of-goods-sold-calculator",
      "average-revenue-per-user-calculator",
      "ad-spend-calculator",
      "target-roas-calculator",
      "days-from-today-calculator",
      "weeks-from-today-calculator",
      "months-from-today-calculator",
      "hours-from-now-calculator",
      "minutes-from-now-calculator",
      "week-number-calculator",
      "day-of-week-calculator",
      "day-of-year-calculator",
      "leap-year-calculator",
      "business-date-calculator",
      "time-zone-difference-calculator",
      "meeting-time-planner",
      "iso-week-date-converter",
      "julian-date-converter",
      "epoch-milliseconds-converter",
      "unix-time-to-iso-8601-converter",
      "iso-8601-to-unix-time-converter",
      "time-zone-offset-converter",
      "working-days-from-today-calculator",
      "weekend-days-calculator",
      "modulo-calculator",
      "remainder-calculator",
      "proportion-calculator",
      "decimal-to-fraction-calculator",
      "mixed-number-calculator",
      "fraction-simplifier",
      "percent-difference-calculator",
      "quartile-calculator",
      "interquartile-range-calculator",
      "ratio-to-percentage-calculator",
      "linear-interpolation-calculator",
      "standard-error-calculator",
      "variance-calculator",
      "coefficient-of-variation-calculator",
      "range-calculator",
      "va-to-watts-calculator",
      "watts-to-va-calculator",
      "kva-to-amps-calculator",
      "amps-to-kva-calculator",
      "kva-to-watts-calculator",
      "watts-to-kva-calculator",
      "kva-to-kw-calculator",
      "kw-to-kva-calculator",
      "volts-to-kw-calculator",
      "kw-to-volts-calculator",
      "ohms-to-amps-calculator",
      "amps-to-ohms-calculator",
      "volts-to-ohms-calculator",
      "ohms-to-volts-calculator",
      "watts-to-ohms-calculator",
      "ohms-to-watts-calculator",
      "ah-to-wh-calculator",
      "wh-to-ah-calculator",
      "amp-hour-calculator",
      "battery-runtime-calculator",
      "kwh-cost-calculator",
      "electricity-cost-calculator",
      "appliance-energy-cost-calculator",
      "power-consumption-calculator",
      "generator-size-calculator",
      "generator-wattage-calculator",
      "generator-fuel-consumption-calculator",
      "extension-cord-gauge-calculator",
      "cable-size-calculator",
      "dc-wire-size-calculator",
      "ac-wire-size-calculator",
      "12v-wire-size-calculator",
      "24v-wire-size-calculator",
      "48v-wire-size-calculator",
      "wire-resistance-calculator",
      "breaker-size-calculator",
      "fuse-size-calculator",
      "transformer-sizing-calculator",
      "current-transformer-calculator",
      "transformer-turns-ratio-calculator",
      "motor-full-load-amps-calculator",
      "motor-horsepower-to-amps-calculator",
      "horsepower-to-watts-calculator",
      "watts-to-horsepower-calculator",
      "ac-power-calculator",
      "dc-power-calculator",
      "three-phase-power-calculator",
      "single-phase-power-calculator",
      "reactive-power-calculator",
      "apparent-power-calculator",
      "ac-amps-to-watts-calculator",
      "dc-amps-to-watts-calculator",
      "single-phase-amps-to-watts-calculator",
      "three-phase-amps-to-watts-calculator",
      "12v-amps-to-watts-calculator",
      "24v-amps-to-watts-calculator",
      "48v-amps-to-watts-calculator",
      "120v-amps-to-watts-calculator",
      "230v-amps-to-watts-calculator",
      "240v-amps-to-watts-calculator",
      "12v-watts-to-amps-calculator",
      "24v-watts-to-amps-calculator",
      "48v-watts-to-amps-calculator",
      "120v-watts-to-amps-calculator",
      "230v-watts-to-amps-calculator",
      "240v-watts-to-amps-calculator",
      "watts-to-kwh-per-day-calculator",
      "monthly-electricity-usage-calculator",
      "annual-electricity-cost-calculator",
      "energy-cost-per-hour-calculator",
      "solar-panel-output-calculator",
      "solar-panel-size-calculator",
      "solar-battery-size-calculator",
      "solar-battery-runtime-calculator",
      "solar-charge-time-calculator",
      "inverter-size-calculator",
      "inverter-battery-runtime-calculator",
      "battery-charging-time-calculator",
      "battery-c-rate-calculator",
      "battery-energy-density-calculator",
      "capacitor-energy-calculator",
      "capacitor-charge-calculator",
      "capacitive-reactance-calculator",
      "inductive-reactance-calculator",
      "resonant-frequency-calculator",
      "rl-time-constant-calculator",
      "series-rlc-impedance-calculator",
      "parallel-rlc-impedance-calculator",
      "impedance-triangle-calculator",
      "phase-angle-calculator",
      "frequency-to-period-calculator",
      "period-to-frequency-calculator",
      "wavelength-calculator",
      "dbm-to-watts-calculator",
      "watts-to-dbm-calculator",
      "dbw-to-watts-calculator",
      "watts-to-dbw-calculator",
      "rms-voltage-calculator",
      "peak-voltage-calculator",
      "peak-to-peak-voltage-calculator",
      "concrete-block-fill-calculator",
      "block-wall-calculator",
      "cinder-block-calculator",
      "breeze-block-calculator",
      "block-and-beam-floor-calculator",
      "retaining-wall-block-calculator",
      "retaining-wall-material-calculator",
      "brick-wall-calculator",
      "bricks-per-square-foot-calculator",
      "bricks-per-square-meter-calculator",
      "brick-mortar-calculator",
      "masonry-mortar-calculator",
      "masonry-wall-calculator",
      "footing-concrete-calculator",
      "strip-footing-concrete-calculator",
      "foundation-concrete-calculator",
      "pier-concrete-calculator",
      "sonotube-concrete-calculator",
      "concrete-column-calculator",
      "concrete-stairs-calculator",
      "concrete-curb-calculator",
      "concrete-driveway-calculator",
      "concrete-patio-calculator",
      "concrete-post-hole-calculator",
      "concrete-yield-calculator",
      "ready-mix-concrete-cost-calculator",
      "aggregate-calculator",
      "pea-gravel-calculator",
      "limestone-calculator",
      "crushed-concrete-calculator",
      "decomposed-granite-calculator",
      "landscape-rock-calculator",
      "driveway-material-calculator",
      "asphalt-driveway-calculator",
      "asphalt-tonnage-calculator",
      "asphalt-cost-calculator",
      "road-gravel-calculator",
      "sub-base-calculator",
      "trench-volume-calculator",
      "excavation-volume-calculator",
      "fill-dirt-calculator",
      "backfill-calculator",
      "dirt-weight-calculator",
      "retaining-wall-gravel-calculator",
      "plaster-calculator",
      "stucco-calculator",
      "siding-calculator",
      "baseboard-calculator",
      "crown-molding-calculator",
      "roof-tile-calculator",
      "screen-ppi-calculator",
      "utf8-byte-counter",
      "chmod-calculator",
      "force-calculator",
      "acceleration-calculator",
      "momentum-calculator",
      "impulse-calculator",
      "kinetic-energy-calculator",
      "potential-energy-calculator",
      "work-calculator",
      "mechanical-power-calculator",
      "lever-torque-calculator",
      "pressure-force-area-calculator",
      "density-calculator",
      "specific-gravity-calculator",
      "buoyancy-calculator",
      "reynolds-number-calculator",
      "bernoulli-equation-calculator",
      "hydraulic-power-calculator",
      "pump-power-calculator",
      "pipe-flow-rate-calculator",
      "heat-transfer-calculator",
      "thermal-expansion-calculator",
    ],
  },

  {
    slug: "colors",
    name: "Color & Design Tools",
    description:
      "Pick, convert, compare, and generate colors, palettes, gradients, shades, tints, and accessibility contrast values directly in your browser.",
    intro:
      "Avorqin's color and design tools help developers and designers convert between HEX, RGB, HSL, and CMYK, check WCAG contrast, create color palettes, build CSS gradients, and generate shades and tints without installing design software.",
    keywords: [
      "color tools",
      "color converter",
      "color picker",
      "HEX to RGB",
      "RGB to HEX",
      "HEX to HSL",
      "HSL to HEX",
      "RGB to HSL",
      "HSL to RGB",
      "RGB to CMYK",
      "CMYK to RGB",
      "color contrast checker",
      "color palette generator",
      "CSS gradient generator",
      "shades and tints generator",
    ],
    toolSlugs: [
      "hex-to-rgb",
      "rgb-to-hex",
      "color-picker",
      "color-converter",
      "hex-to-hsl",
      "hsl-to-hex",
      "rgb-to-hsl",
      "hsl-to-rgb",
      "rgb-to-cmyk",
      "cmyk-to-rgb",
      "color-contrast-checker",
      "color-palette-generator",
      "gradient-generator",
      "shades-and-tints-generator",
    ],
  },

  {
    slug: "pdf",
    name: "PDF & Document Tools",
    description:
      "Merge, split, inspect, convert, compress, edit, generate, and transform PDF documents directly in your browser.",
    intro:
      "Avorqin's PDF and document tools help you work with PDFs locally in your browser. Merge and split files, extract or remove pages, reorder and rotate documents, inspect metadata and page information, add page numbers or watermarks, convert images and text-based content to PDF, render PDF pages as images, extract selectable text, compress image-heavy PDFs, create grayscale copies, and check file size without relying on an external conversion service.",
    keywords: [
      "PDF tools",
      "PDF converter",
      "merge PDF",
      "split PDF",
      "extract PDF pages",
      "remove PDF pages",
      "rotate PDF",
      "PDF metadata",
      "PDF page size",
      "images to PDF",
      "JPG to PDF",
      "PNG to PDF",
      "PDF to JPG",
      "PDF to PNG",
      "PDF to text",
      "compress PDF",
      "HTML to PDF",
      "text to PDF",
      "Markdown to PDF",
      "PDF to grayscale",
      "PDF file size checker",
    ],
    toolSlugs: [
      "merge-pdf",
      "split-pdf",
      "extract-pdf-pages",
      "remove-pdf-pages",
      "reorder-pdf-pages",
      "rotate-pdf",
      "pdf-page-counter",
      "pdf-metadata-viewer",
      "pdf-metadata-remover",
      "pdf-page-size-checker",
      "pdf-orientation-checker",
      "pdf-info",
      "add-page-numbers-to-pdf",
      "add-watermark-to-pdf",
      "images-to-pdf",
      "jpg-to-pdf",
      "png-to-pdf",
      "pdf-to-jpg",
      "pdf-to-png",
      "pdf-to-text",
      "compress-pdf",
      "html-to-pdf",
      "text-to-pdf",
      "markdown-to-pdf",
      "pdf-to-grayscale",
      "pdf-file-size-checker",
    ],
  },
  {
    slug: "images",
    name: "Image Tools",
    description:
      "Compress, resize, crop, rotate, inspect, encode, and convert JPG, PNG, WebP, and SVG images directly in your browser.",
    intro:
      "Avorqin's image tools help you resize, compress, crop, rotate, inspect, encode, and convert common image formats without installing desktop software. Supported images are processed directly in your browser rather than intentionally uploaded to Avorqin for processing.",
    keywords: [
      "image tools",
      "image converter",
      "image compressor",
      "image resizer",
      "image cropper",
      "JPG to PNG",
      "PNG to JPG",
      "WebP converter",
      "SVG to PNG",
      "image dimensions",
      "image DPI calculator",
      "image to Base64",
    ],
    toolSlugs: [
      "image-compressor",
      "image-resizer",
      "image-cropper",
      "image-rotator",
      "jpg-to-png",
      "png-to-jpg",
      "webp-to-png",
      "png-to-webp",
      "jpg-to-webp",
      "webp-to-jpg",
      "svg-to-png",
      "image-dimensions-checker",
      "image-dpi-calculator",
      "image-to-base64",
      "base64-to-image-decoder",
      "png-to-ico-converter",
      "ico-to-png-converter",
      "svg-viewer",
      "svg-optimizer",
      "svg-to-base64-encoder",
      "base64-to-svg-decoder",
      "image-flipper",
      "image-grayscale-converter",
      "image-color-picker",
      "image-palette-extractor",
      "image-border-adder",
      "image-rounded-corners",
      "image-pixelate-tool",
      "image-blur-tool",
    ],
  },
  {
    slug: "construction",
    name: "Construction & Home Tools",
    description: "Calculate concrete, flooring, roofing, paint, gravel, lumber, fencing, landscaping materials, and common home-project quantities.",
    intro: "Plan common construction, renovation, landscaping, and home-improvement projects with browser-based calculators for material quantities, areas, volumes, roofing, flooring, concrete, gravel, lumber, paint, fencing, and more.",
    keywords: ["construction calculators", "home improvement calculators", "concrete calculator", "square footage calculator", "roofing calculator", "flooring calculator", "gravel calculator", "paint calculator"],
    toolSlugs: [
      "square-footage-calculator",
      "concrete-calculator",
      "concrete-slab-calculator",
      "concrete-bag-calculator",
      "cubic-yard-calculator",
      "gravel-calculator",
      "mulch-calculator",
      "topsoil-calculator",
      "sand-calculator",
      "brick-calculator",
      "concrete-block-calculator",
      "drywall-calculator",
      "paint-calculator",
      "wallpaper-calculator",
      "flooring-calculator",
      "tile-calculator",
      "carpet-calculator",
      "decking-calculator",
      "fence-calculator",
      "roofing-calculator",
      "roof-pitch-calculator",
      "rafter-length-calculator",
      "roof-shingle-calculator",
      "stair-calculator",
      "board-foot-calculator",
      "lumber-calculator",
      "stud-calculator",
      "insulation-calculator",
      "paver-calculator",
      "asphalt-calculator",
      "room-area-calculator",
      "wall-area-calculator",
      "ceiling-area-calculator",
      "cubic-feet-calculator",
      "square-feet-to-cubic-yards-calculator",
      "grout-calculator",
      "mortar-calculator",
      "thinset-calculator",
      "rebar-calculator",
      "pool-volume-calculator",
      "tank-volume-calculator",
      "pipe-volume-calculator",
      "gpm-calculator",
      "flow-rate-calculator",
      "deck-stain-calculator",
      "epoxy-calculator",
      "crushed-stone-calculator",
      "road-base-calculator",
      "gravel-driveway-calculator",
      "fence-post-depth-calculator",
      "concrete-block-fill-calculator",
      "block-wall-calculator",
      "cinder-block-calculator",
      "breeze-block-calculator",
      "block-and-beam-floor-calculator",
      "retaining-wall-block-calculator",
      "retaining-wall-material-calculator",
      "brick-wall-calculator",
      "bricks-per-square-foot-calculator",
      "bricks-per-square-meter-calculator",
      "brick-mortar-calculator",
      "masonry-mortar-calculator",
      "masonry-wall-calculator",
      "footing-concrete-calculator",
      "strip-footing-concrete-calculator",
      "foundation-concrete-calculator",
      "pier-concrete-calculator",
      "sonotube-concrete-calculator",
      "concrete-column-calculator",
      "concrete-stairs-calculator",
      "concrete-curb-calculator",
      "concrete-driveway-calculator",
      "concrete-patio-calculator",
      "concrete-post-hole-calculator",
      "concrete-yield-calculator",
      "ready-mix-concrete-cost-calculator",
      "aggregate-calculator",
      "pea-gravel-calculator",
      "limestone-calculator",
      "crushed-concrete-calculator",
      "decomposed-granite-calculator",
      "landscape-rock-calculator",
      "driveway-material-calculator",
      "asphalt-driveway-calculator",
      "asphalt-tonnage-calculator",
      "asphalt-cost-calculator",
      "road-gravel-calculator",
      "sub-base-calculator",
      "trench-volume-calculator",
      "excavation-volume-calculator",
      "fill-dirt-calculator",
      "backfill-calculator",
      "dirt-weight-calculator",
      "retaining-wall-gravel-calculator",
      "plaster-calculator",
      "stucco-calculator",
      "siding-calculator",
      "baseboard-calculator",
      "crown-molding-calculator",
      "roof-tile-calculator",
      "drywall-mud-calculator",
      "drywall-screw-calculator",
      "drywall-cost-calculator",
      "paint-cost-calculator",
      "flooring-cost-calculator",
      "tile-cost-calculator",
      "fence-post-spacing-calculator",
      "gutter-size-calculator",
      "gutter-slope-calculator",
      "downspout-calculator",
      "insulation-r-value-calculator",
      "room-btu-calculator",
      "hvac-tonnage-calculator",
      "cfm-calculator",
      "air-changes-per-hour-calculator",
      "duct-size-calculator",
      "pipe-slope-calculator",
      "water-pressure-loss-calculator",
      "rainwater-harvesting-calculator",
      "lawn-seed-calculator",
      "sod-calculator",
      "concrete-weight-calculator",
      "lumber-weight-calculator",
      "lumber-cost-calculator",
      "stair-stringer-calculator",
      "rebar-weight-calculator",
      "rebar-spacing-calculator",
      "tile-layout-calculator",
      "ceiling-tile-calculator",
      "door-rough-opening-calculator",
      "fence-picket-spacing-calculator",
      "stair-baluster-spacing-calculator",
      "wheelchair-ramp-length-calculator",
      "landscape-fabric-calculator",
      "acoustic-panel-calculator",
      "cabinet-linear-feet-calculator",
      "countertop-square-footage-calculator",
    ],
  },
  {
    slug: "electrical",
    name: "Electrical & Electronics Tools",
    description: "Calculate watts, amps, volts, energy, batteries, voltage drop, wire gauge, resistance, capacitance, transformers, and lighting values.",
    intro: "Use practical browser-based electrical calculators for power conversions, battery estimates, wire voltage drop, resistance and capacitance networks, transformer relationships, energy, and lighting calculations.",
    keywords: ["electrical calculators", "watts to amps calculator", "amps to watts calculator", "voltage drop calculator", "wire gauge calculator", "battery life calculator", "resistor calculator"],
    toolSlugs: [
      "watts-to-amps-calculator",
      "amps-to-watts-calculator",
      "volts-to-watts-calculator",
      "watts-to-volts-calculator",
      "amps-to-volts-calculator",
      "volts-to-amps-calculator",
      "kw-to-amps-calculator",
      "amps-to-kw-calculator",
      "kw-to-kwh-calculator",
      "kwh-to-kw-calculator",
      "watts-to-kwh-calculator",
      "kwh-to-watts-calculator",
      "mah-to-wh-calculator",
      "wh-to-mah-calculator",
      "battery-life-calculator",
      "battery-capacity-calculator",
      "power-factor-calculator",
      "voltage-drop-calculator",
      "wire-gauge-calculator",
      "series-resistor-calculator",
      "parallel-resistor-calculator",
      "capacitor-series-calculator",
      "capacitor-parallel-calculator",
      "rc-time-constant-calculator",
      "transformer-calculator",
      "joules-to-watts-calculator",
      "watts-to-joules-calculator",
      "lumens-to-watts-calculator",
      "watts-to-lumens-calculator",
      "lux-to-lumens-calculator",
      "va-to-watts-calculator",
      "watts-to-va-calculator",
      "kva-to-amps-calculator",
      "amps-to-kva-calculator",
      "kva-to-watts-calculator",
      "watts-to-kva-calculator",
      "kva-to-kw-calculator",
      "kw-to-kva-calculator",
      "volts-to-kw-calculator",
      "kw-to-volts-calculator",
      "ohms-to-amps-calculator",
      "amps-to-ohms-calculator",
      "volts-to-ohms-calculator",
      "ohms-to-volts-calculator",
      "watts-to-ohms-calculator",
      "ohms-to-watts-calculator",
      "ah-to-wh-calculator",
      "wh-to-ah-calculator",
      "amp-hour-calculator",
      "battery-runtime-calculator",
      "kwh-cost-calculator",
      "electricity-cost-calculator",
      "appliance-energy-cost-calculator",
      "power-consumption-calculator",
      "generator-size-calculator",
      "generator-wattage-calculator",
      "generator-fuel-consumption-calculator",
      "extension-cord-gauge-calculator",
      "cable-size-calculator",
      "dc-wire-size-calculator",
      "ac-wire-size-calculator",
      "12v-wire-size-calculator",
      "24v-wire-size-calculator",
      "48v-wire-size-calculator",
      "wire-resistance-calculator",
      "breaker-size-calculator",
      "fuse-size-calculator",
      "transformer-sizing-calculator",
      "current-transformer-calculator",
      "transformer-turns-ratio-calculator",
      "motor-full-load-amps-calculator",
      "motor-horsepower-to-amps-calculator",
      "horsepower-to-watts-calculator",
      "watts-to-horsepower-calculator",
      "ac-power-calculator",
      "dc-power-calculator",
      "three-phase-power-calculator",
      "single-phase-power-calculator",
      "reactive-power-calculator",
      "apparent-power-calculator",
      "ac-amps-to-watts-calculator",
      "dc-amps-to-watts-calculator",
      "single-phase-amps-to-watts-calculator",
      "three-phase-amps-to-watts-calculator",
      "12v-amps-to-watts-calculator",
      "24v-amps-to-watts-calculator",
      "48v-amps-to-watts-calculator",
      "120v-amps-to-watts-calculator",
      "230v-amps-to-watts-calculator",
      "240v-amps-to-watts-calculator",
      "12v-watts-to-amps-calculator",
      "24v-watts-to-amps-calculator",
      "48v-watts-to-amps-calculator",
      "120v-watts-to-amps-calculator",
      "230v-watts-to-amps-calculator",
      "240v-watts-to-amps-calculator",
      "watts-to-kwh-per-day-calculator",
      "monthly-electricity-usage-calculator",
      "annual-electricity-cost-calculator",
      "energy-cost-per-hour-calculator",
      "solar-panel-output-calculator",
      "solar-panel-size-calculator",
      "solar-battery-size-calculator",
      "solar-battery-runtime-calculator",
      "solar-charge-time-calculator",
      "inverter-size-calculator",
      "inverter-battery-runtime-calculator",
      "battery-charging-time-calculator",
      "battery-c-rate-calculator",
      "battery-energy-density-calculator",
      "capacitor-energy-calculator",
      "capacitor-charge-calculator",
      "capacitive-reactance-calculator",
      "inductive-reactance-calculator",
      "resonant-frequency-calculator",
      "rl-time-constant-calculator",
      "series-rlc-impedance-calculator",
      "parallel-rlc-impedance-calculator",
      "impedance-triangle-calculator",
      "phase-angle-calculator",
      "frequency-to-period-calculator",
      "period-to-frequency-calculator",
      "wavelength-calculator",
      "dbm-to-watts-calculator",
      "watts-to-dbm-calculator",
      "dbw-to-watts-calculator",
      "watts-to-dbw-calculator",
      "rms-voltage-calculator",
      "peak-voltage-calculator",
      "peak-to-peak-voltage-calculator",
      "pcb-trace-width-calculator",
      "resistor-power-rating-calculator",
      "capacitor-code-calculator",
      "battery-pack-series-parallel-calculator",
      "ups-runtime-calculator",
      "motor-torque-calculator",
      "current-density-calculator",
      "capacitor-discharge-time-calculator",
    ],
  },
  {
    slug: "education",
    name: "Education & Grade Tools",
    description: "Calculate GPA, weighted GPA, final grades, test grades, semester GPA, cumulative GPA, and weighted course grades.",
    intro: "Estimate grades and GPA with straightforward browser-based calculators for students. Work with course credits, letter grades, weighted categories, final exams, tests, semesters, and cumulative GPA.",
    keywords: ["grade calculator", "GPA calculator", "weighted GPA calculator", "final grade calculator", "test grade calculator", "college GPA calculator", "high school GPA calculator"],
    toolSlugs: [
      "gpa-calculator",
      "weighted-gpa-calculator",
      "high-school-gpa-calculator",
      "college-gpa-calculator",
      "grade-calculator",
      "final-grade-calculator",
      "weighted-grade-calculator",
      "test-grade-calculator",
      "semester-gpa-calculator",
      "cumulative-gpa-calculator",
      "grade-curve-calculator",
      "attendance-percentage-calculator",
      "credit-hour-calculator",
      "course-load-calculator",
      "study-time-calculator",
      "study-schedule-calculator",
      "reading-speed-calculator",
      "apa-citation-generator",
      "mla-citation-generator",
      "chicago-citation-generator",
      "harvard-citation-generator",
      "ieee-citation-generator",
      "bibtex-entry-generator",
      "vancouver-citation-generator",
      "ama-citation-generator",
    ],
  },
  {
    slug: "ecommerce",
    name: "Ecommerce & SaaS Tools",
    description: "Calculate ecommerce, advertising, inventory, retention, recurring revenue, customer economics, and SaaS business metrics.",
    intro: "Avorqin's ecommerce and SaaS tools help merchants, marketers, founders, and operators calculate order value, advertising efficiency, inventory metrics, churn, retention, recurring revenue, unit economics, margins, and customer acquisition performance directly in the browser.",
    keywords: ["ecommerce calculators", "SaaS calculators", "AOV calculator", "churn rate calculator", "MRR calculator", "ROAS calculator", "inventory turnover calculator", "CAC calculator"],
    toolSlugs: [
      "average-order-value-calculator",
      "click-through-rate-calculator",
      "cost-per-lead-calculator",
      "lead-conversion-rate-calculator",
      "email-open-rate-calculator",
      "email-click-through-rate-calculator",
      "ecommerce-profit-calculator",
      "gmroi-calculator",
      "inventory-turnover-calculator",
      "reorder-point-calculator",
      "safety-stock-calculator",
      "economic-order-quantity-calculator",
      "sell-through-rate-calculator",
      "cart-abandonment-rate-calculator",
      "engagement-rate-calculator",
      "churn-rate-calculator",
      "retention-rate-calculator",
      "mrr-calculator",
      "arr-calculator",
      "mrr-growth-calculator",
      "ltv-to-cac-ratio-calculator",
      "cac-payback-period-calculator",
      "payback-period-calculator",
      "contribution-margin-calculator",
      "operating-margin-calculator",
      "ebitda-margin-calculator",
      "cost-of-goods-sold-calculator",
      "average-revenue-per-user-calculator",
      "ad-spend-calculator",
      "target-roas-calculator",
      "net-revenue-retention-calculator",
      "gross-revenue-retention-calculator",
      "revenue-churn-calculator",
      "expansion-mrr-calculator",
      "contraction-mrr-calculator",
      "net-new-mrr-calculator",
      "saas-magic-number-calculator",
      "rule-of-40-calculator",
      "saas-quick-ratio-calculator",
      "average-revenue-per-account-calculator",
      "net-promoter-score-calculator",
      "marketing-efficiency-ratio-calculator",
      "saas-burn-multiple-calculator",
      "average-contract-value-calculator",
      "trial-conversion-rate-calculator",
    ],
  },
  {
    slug: "engineering",
    name: "Physics & Engineering Tools",
    description: "Calculate common physics, mechanics, fluids, thermal, and engineering values in your browser.",
    intro: "Use focused physics and engineering calculators for force, motion, energy, fluids, heat transfer, hydraulics, and related technical work.",
    keywords: ["physics calculators", "engineering calculators", "force calculator", "reynolds number calculator", "heat transfer calculator"],
    toolSlugs: [
      "force-calculator",
      "acceleration-calculator",
      "momentum-calculator",
      "impulse-calculator",
      "kinetic-energy-calculator",
      "potential-energy-calculator",
      "work-calculator",
      "mechanical-power-calculator",
      "lever-torque-calculator",
      "pressure-force-area-calculator",
      "density-calculator",
      "specific-gravity-calculator",
      "buoyancy-calculator",
      "reynolds-number-calculator",
      "bernoulli-equation-calculator",
      "hydraulic-power-calculator",
      "pump-power-calculator",
      "pipe-flow-rate-calculator",
      "heat-transfer-calculator",
      "thermal-expansion-calculator",
    ],
  },
  {
    slug: "automotive",
    name: "Automotive Tools",
    description: "Calculate fuel cost, tire size, gearing, engine performance, EV charging, and other automotive values.",
    intro: "Plan and compare common vehicle calculations including fuel economy, tire sizing, gearing, engine performance, EV charging, depreciation, and towing.",
    keywords: ["automotive calculators", "mpg calculator", "tire size calculator", "fuel cost calculator", "EV charging calculator"],
    toolSlugs: [
      "mpg-calculator",
      "fuel-cost-calculator",
      "cost-per-mile-calculator",
      "tire-size-calculator",
      "speedometer-error-calculator",
      "wheel-offset-calculator",
      "wheel-backspacing-calculator",
      "gear-ratio-calculator",
      "rpm-speed-calculator",
      "engine-displacement-calculator",
      "compression-ratio-calculator",
      "horsepower-to-weight-ratio-calculator",
      "torque-to-horsepower-calculator",
      "horsepower-to-torque-calculator",
      "quarter-mile-horsepower-calculator",
      "vehicle-depreciation-calculator",
      "lease-mileage-calculator",
      "ev-charging-time-calculator",
      "ev-charging-cost-calculator",
      "ev-range-calculator",
      "piston-speed-calculator",
      "wheel-torque-calculator",
      "stopping-distance-calculator",
      "vehicle-weight-distribution-calculator",
      "trailer-tongue-weight-calculator",
    ],
  },
  {
    slug: "cooking-baking",
    name: "Cooking & Baking Tools",
    description: "Scale recipes and calculate dough, baking, coffee, brine, and food-cost values.",
    intro: "Use practical cooking and baking calculators for recipe scaling, dough hydration, baker percentages, coffee ratios, brines, and kitchen planning.",
    keywords: ["cooking calculators", "baking calculators", "recipe scaling calculator", "dough hydration calculator", "bakers percentage calculator"],
    toolSlugs: [
      "recipe-scaling-calculator",
      "recipe-cost-calculator",
      "bakers-percentage-calculator",
      "dough-hydration-calculator",
      "pizza-dough-calculator",
      "bread-dough-calculator",
      "sourdough-starter-feeding-calculator",
      "coffee-ratio-calculator",
      "cold-brew-ratio-calculator",
      "rice-water-ratio-calculator",
      "brine-percentage-calculator",
      "food-cost-percentage-calculator",
      "yeast-conversion-calculator",
      "dough-ball-weight-calculator",
      "cake-pan-conversion-calculator",
    ],
  },
  {
    slug: "photography-video",
    name: "Photography & Video Tools",
    description: "Calculate photography exposure, depth of field, focal length, video bitrate, file size, and recording time.",
    intro: "Use photography and video calculators for lenses, exposure, depth of field, filters, timelapse, bitrate, media size, and timecode workflows.",
    keywords: ["photography calculators", "video calculators", "depth of field calculator", "video bitrate calculator", "timelapse calculator"],
    toolSlugs: [
      "crop-factor-calculator",
      "equivalent-focal-length-calculator",
      "field-of-view-calculator",
      "hyperfocal-distance-calculator",
      "depth-of-field-calculator",
      "exposure-value-calculator",
      "shutter-speed-stops-calculator",
      "nd-filter-calculator",
      "timelapse-calculator",
      "video-bitrate-calculator",
      "video-file-size-calculator",
      "audio-file-size-calculator",
      "recording-time-calculator",
      "frame-count-calculator",
      "frames-to-timecode-converter",
    ],
  },
];

export function getToolCategory(
  slug: string
): ToolCategoryConfig | undefined {
  return toolCategories.find((category) => category.slug === slug);
}

export function getCategoryTools(category: ToolCategoryConfig) {
  const positions = new Map(
    category.toolSlugs.map((slug, index) => [slug, index])
  );

  return tools
    .filter((tool) => positions.has(tool.slug))
    .sort(
      (a, b) =>
        (positions.get(a.slug) ?? 0) -
        (positions.get(b.slug) ?? 0)
    );
}