export function minifyJson(input:string){ if(!input.trim()) throw new Error("Enter JSON."); return JSON.stringify(JSON.parse(input)); }
export function minifyCss(input:string){ return input.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ").replace(/\s*([{}:;,>+~])\s*/g,"$1").replace(/;}/g,"}").trim(); }
export function minifyHtml(input:string){ return input.replace(/<!--(?!\[if)[\s\S]*?-->/g,"").replace(/>\s+</g,"><").replace(/\s{2,}/g," ").trim(); }
export function compactJs(input:string){ return input.replace(/\/\*[\s\S]*?\*\//g,"").replace(/^\s*\/\/.*$/gm,"").replace(/[ \t]+/g," ").replace(/\n\s*/g,"\n").trim(); }
export function nowTs(){ const ms=Date.now(); return {seconds:Math.floor(ms/1000),milliseconds:ms}; }
export function tsToDate(v:number,unit:"seconds"|"milliseconds"){ const d=new Date(unit==="seconds"?v*1000:v); if(Number.isNaN(d.getTime())) throw new Error("Invalid timestamp."); return {iso:d.toISOString(),utc:d.toUTCString(),local:d.toLocaleString()}; }
export function diffDates(a:string,b:string){ const x=new Date(a+"T00:00:00"),y=new Date(b+"T00:00:00"); if(Number.isNaN(x.getTime())||Number.isNaN(y.getTime())) throw new Error("Invalid date."); const ms=Math.abs(y.getTime()-x.getTime()); return {days:ms/86400000,weeks:ms/604800000,hours:ms/3600000}; }
export function age(birth:string,asOf:string){ const b=new Date(birth+"T00:00:00"),a=new Date(asOf+"T00:00:00"); if(Number.isNaN(b.getTime())||Number.isNaN(a.getTime())||a<b) throw new Error("Invalid dates."); let years=a.getFullYear()-b.getFullYear(), months=a.getMonth()-b.getMonth(), days=a.getDate()-b.getDate(); if(days<0){months--;days+=new Date(a.getFullYear(),a.getMonth(),0).getDate();} if(months<0){years--;months+=12;} return {years,months,days};}
export function pctOf(p:number,v:number){return p/100*v;} export function pctPart(part:number,whole:number){if(whole===0)throw new Error("Whole cannot be zero.");return part/whole*100;} export function pctChange(oldV:number,newV:number){if(oldV===0)throw new Error("Starting value cannot be zero.");return (newV-oldV)/Math.abs(oldV)*100;}
function gcd(a:number,b:number){a=Math.abs(Math.round(a));b=Math.abs(Math.round(b));while(b)[a,b]=[b,a%b];return a||1;} export function ratio(w:number,h:number){if(w<=0||h<=0)throw new Error("Values must be positive.");const d=gcd(w,h);return {w:Math.round(w/d),h:Math.round(h/d),decimal:w/h};}
export function resolution(w:number,h:number){const pixels=w*h;return {pixels,megapixels:pixels/1e6};}
export function remToPx(v:number,root:number){return v*root;} export function pxToRem(v:number,root:number){if(root===0)throw new Error("Root cannot be zero.");return v/root;} export function emToPx(v:number,font:number){return v*font;}
export function bytes(v:number,from:string,to:string){const u:Record<string,number>={B:1,KB:1e3,MB:1e6,GB:1e9,TB:1e12,KiB:1024,MiB:1024**2,GiB:1024**3};if(!u[from]||!u[to])throw new Error("Unsupported unit.");return v*u[from]/u[to];}
export function transfer(size:number,sizeUnit:string,speed:number,speedUnit:string){const s:Record<string,number>={MB:8e6,GB:8e9,TB:8e12,MiB:8*1024**2,GiB:8*1024**3};const p:Record<string,number>={Kbps:1e3,Mbps:1e6,Gbps:1e9};if(speed<=0)throw new Error("Speed must be positive.");const seconds=size*(s[sizeUnit]||8e9)/(speed*(p[speedUnit]||1e6));return {seconds,minutes:seconds/60,hours:seconds/3600};}
export function decodeSlug(s:string){return s.trim().replace(/^\/+|\/+$/g,"").split(/[\/_-]+/).filter(Boolean).map(w=>w[0].toUpperCase()+w.slice(1)).join(" ");}
const HTTP:Record<number,string>={200:"OK",201:"Created",204:"No Content",301:"Moved Permanently",302:"Found",304:"Not Modified",307:"Temporary Redirect",308:"Permanent Redirect",400:"Bad Request",401:"Unauthorized",403:"Forbidden",404:"Not Found",405:"Method Not Allowed",409:"Conflict",410:"Gone",415:"Unsupported Media Type",422:"Unprocessable Content",429:"Too Many Requests",500:"Internal Server Error",502:"Bad Gateway",503:"Service Unavailable",504:"Gateway Timeout"}; export function httpLookup(c:number){return HTTP[c]||null;}
const MIME:Record<string,string>={".html":"text/html",".css":"text/css",".js":"text/javascript",".json":"application/json",".xml":"application/xml",".csv":"text/csv",".txt":"text/plain",".md":"text/markdown",".pdf":"application/pdf",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".gif":"image/gif",".webp":"image/webp",".svg":"image/svg+xml",".mp3":"audio/mpeg",".mp4":"video/mp4",".zip":"application/zip"}; export function mimeLookup(q:string){q=q.trim().toLowerCase();if(q.includes("/"))return Object.entries(MIME).filter(([,m])=>m===q).map(([ext,mime])=>({ext,mime}));const ext=q.startsWith(".")?q:"."+q;return MIME[ext]?[{ext,mime:MIME[ext]}]:[];}
export function uaParse(ua:string){const browser=/Edg\/([\d.]+)/.exec(ua)?`Edge ${/Edg\/([\d.]+)/.exec(ua)?.[1]}`:/Chrome\/([\d.]+)/.exec(ua)?`Chrome ${/Chrome\/([\d.]+)/.exec(ua)?.[1]}`:/Firefox\/([\d.]+)/.exec(ua)?`Firefox ${/Firefox\/([\d.]+)/.exec(ua)?.[1]}`:/Version\/([\d.]+).*Safari/.exec(ua)?`Safari ${/Version\/([\d.]+)/.exec(ua)?.[1]}`:"Unknown";const os=/Windows/.test(ua)?"Windows":/Android/.test(ua)?"Android":/iPhone|iPad/.test(ua)?"iOS/iPadOS":/Mac OS X/.test(ua)?"macOS":/Linux/.test(ua)?"Linux":"Unknown";const device=/Mobile|Android|iPhone/i.test(ua)?"Mobile":/iPad|Tablet/i.test(ua)?"Tablet":"Desktop";return {browser,os,device};}
export function uuidCheck(v:string){const m=v.trim().match(/^[{(]?([0-9a-f]{8})-([0-9a-f]{4})-([1-8][0-9a-f]{3})-([89ab][0-9a-f]{3})-([0-9a-f]{12})[)}]?$/i);return m?{valid:true,version:Number(m[3][0])}:{valid:false,version:null};}
function ipInt(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))throw new Error("Invalid IPv4 address.");return (((p[0]<<24)>>>0)+(p[1]<<16)+(p[2]<<8)+p[3])>>>0;} function intIp(n:number){return[n>>>24,(n>>>16)&255,(n>>>8)&255,n&255].join(".");}
export function subnet(input:string){const [ip,pr]=input.trim().split("/");const prefix=Number(pr);if(!Number.isInteger(prefix)||prefix<0||prefix>32)throw new Error("CIDR must be 0-32.");const i=ipInt(ip),mask=prefix===0?0:(0xffffffff<<(32-prefix))>>>0,network=(i&mask)>>>0,broadcast=(network|(~mask>>>0))>>>0,total=2**(32-prefix);return {network:intIp(network),broadcast:intIp(broadcast),subnetMask:intIp(mask),firstHost:intIp(prefix>=31?network:network+1),lastHost:intIp(prefix>=31?broadcast:broadcast-1),totalAddresses:total,usableHosts:prefix>=31?total:Math.max(total-2,0)};}
export function randomMac(){const a=new Uint8Array(6);crypto.getRandomValues(a);a[0]=(a[0]|2)&254;return Array.from(a).map(x=>x.toString(16).padStart(2,"0")).join(":").toUpperCase();}
