export type Batch601650Kind =
  | "concrete-block-fill-calculator"
  | "block-wall-calculator"
  | "cinder-block-calculator"
  | "breeze-block-calculator"
  | "block-and-beam-floor-calculator"
  | "retaining-wall-block-calculator"
  | "retaining-wall-material-calculator"
  | "brick-wall-calculator"
  | "bricks-per-square-foot-calculator"
  | "bricks-per-square-meter-calculator"
  | "brick-mortar-calculator"
  | "masonry-mortar-calculator"
  | "masonry-wall-calculator"
  | "footing-concrete-calculator"
  | "strip-footing-concrete-calculator"
  | "foundation-concrete-calculator"
  | "pier-concrete-calculator"
  | "sonotube-concrete-calculator"
  | "concrete-column-calculator"
  | "concrete-stairs-calculator"
  | "concrete-curb-calculator"
  | "concrete-driveway-calculator"
  | "concrete-patio-calculator"
  | "concrete-post-hole-calculator"
  | "concrete-yield-calculator"
  | "ready-mix-concrete-cost-calculator"
  | "aggregate-calculator"
  | "pea-gravel-calculator"
  | "limestone-calculator"
  | "crushed-concrete-calculator"
  | "decomposed-granite-calculator"
  | "landscape-rock-calculator"
  | "driveway-material-calculator"
  | "asphalt-driveway-calculator"
  | "asphalt-tonnage-calculator"
  | "asphalt-cost-calculator"
  | "road-gravel-calculator"
  | "sub-base-calculator"
  | "trench-volume-calculator"
  | "excavation-volume-calculator"
  | "fill-dirt-calculator"
  | "backfill-calculator"
  | "dirt-weight-calculator"
  | "retaining-wall-gravel-calculator"
  | "plaster-calculator"
  | "stucco-calculator"
  | "siding-calculator"
  | "baseboard-calculator"
  | "crown-molding-calculator"
  | "roof-tile-calculator";

export type Batch601650Field = {
  key: string;
  label: string;
  type?: "number" | "input" | "select";
  defaultValue?: string;
  placeholder?: string;
  options?: { label: string; value: string }[];
};

export type Batch601650Config = { fields: Batch601650Field[]; button?: string; note?: string };
export type Batch601650ResultItem = { label: string; value: string; note?: string };
export type Batch601650Result = { output: string; summary: Batch601650ResultItem[] };

const num=(x:string,l:string)=>{const n=Number(x);if(!Number.isFinite(n))throw new Error(`${l} must be a valid number.`);return n;};
const pos=(x:string,l:string)=>{const n=num(x,l);if(n<=0)throw new Error(`${l} must be greater than zero.`);return n;};
const nonneg=(x:string,l:string)=>{const n=num(x,l);if(n<0)throw new Error(`${l} cannot be negative.`);return n;};
const pct=(x:string,l:string)=>{const n=nonneg(x,l);if(n>100)throw new Error(`${l} cannot exceed 100%.`);return n/100;};
const fmt=(n:number,d=4)=>new Intl.NumberFormat(undefined,{maximumFractionDigits:d}).format(n);
const money=(n:number)=>new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n);
const R=(output:string,pairs:[string,string][]):Batch601650Result=>({output,summary:pairs.map(([label,value])=>({label,value}))});
const volPair=(cf:number)=>[["Cubic feet",`${fmt(cf)} cu ft`],["Cubic yards",`${fmt(cf/27)} cu yd`]] as [string,string][];
const materialBox=(v:Record<string,string>,densityDefault:number)=>{const l=pos(v.length,"Length"),w=pos(v.width,"Width"),d=pos(v.depth,"Depth"),density=v.density?pos(v.density,"Density"):densityDefault,cf=l*w*d/12,cy=cf/27,tons=cf*density/2000;return R(`${fmt(cy)} cu yd`,[["Volume",`${fmt(cy)} cu yd`],["Cubic feet",`${fmt(cf)} cu ft`],["Estimated weight",`${fmt(tons)} tons`]]);};
const slab=(v:Record<string,string>,lengthKey="length",widthKey="width",thicknessKey="thickness")=>{const l=pos(v[lengthKey],"Length"),w=pos(v[widthKey],"Width"),t=pos(v[thicknessKey],"Thickness"),wa=pct(v.waste,"Waste allowance"),cf=l*w*t/12*(1+wa),cy=cf/27;return R(`${fmt(cy)} cu yd`,[["Concrete volume",`${fmt(cy)} cu yd`],["Cubic feet",`${fmt(cf)} cu ft`],["Including waste",`${fmt(wa*100)}%`]]);};
const cylinder=(diameterIn:number,heightFt:number,qty:number)=>Math.PI*Math.pow(diameterIn/24,2)*heightFt*qty;
const blockCount=(wallLengthFt:number,wallHeightFt:number,blockLengthIn:number,blockHeightIn:number,waste:number)=>Math.ceil((wallLengthFt*wallHeightFt*144)/(blockLengthIn*blockHeightIn)*(1+waste));

export const BATCH601650_CONFIG: Record<Batch601650Kind, Batch601650Config> = {
  "concrete-block-fill-calculator": { fields: [{"key": "blocks", "label": "Number of blocks", "type": "number", "defaultValue": "200"}, {"key": "fillPerBlock", "label": "Fill volume per block (cu ft)", "type": "number", "defaultValue": "0.18"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "block-wall-calculator": { fields: [{"key": "wallLength", "label": "Wall length (ft)", "type": "number", "defaultValue": "30"}, {"key": "wallHeight", "label": "Wall height (ft)", "type": "number", "defaultValue": "8"}, {"key": "blockLength", "label": "Block face length (in)", "type": "number", "defaultValue": "16"}, {"key": "blockHeight", "label": "Block face height (in)", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "5"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "cinder-block-calculator": { fields: [{"key": "wallLength", "label": "Wall length (ft)", "type": "number", "defaultValue": "30"}, {"key": "wallHeight", "label": "Wall height (ft)", "type": "number", "defaultValue": "8"}, {"key": "blockLength", "label": "Block face length (in)", "type": "number", "defaultValue": "16"}, {"key": "blockHeight", "label": "Block face height (in)", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "5"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "breeze-block-calculator": { fields: [{"key": "wallLength", "label": "Wall length (m)", "type": "number", "defaultValue": "6"}, {"key": "wallHeight", "label": "Wall height (m)", "type": "number", "defaultValue": "2.4"}, {"key": "blockLength", "label": "Block face length (mm)", "type": "number", "defaultValue": "440"}, {"key": "blockHeight", "label": "Block face height (mm)", "type": "number", "defaultValue": "215"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "5"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "block-and-beam-floor-calculator": { fields: [{"key": "length", "label": "Floor length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Floor width (ft)", "type": "number", "defaultValue": "20"}, {"key": "beamSpacing", "label": "Beam spacing (ft)", "type": "number", "defaultValue": "2"}, {"key": "blockLength", "label": "Infill block length (in)", "type": "number", "defaultValue": "17"}, {"key": "blockWidth", "label": "Infill block width (in)", "type": "number", "defaultValue": "8.5"}, {"key": "waste", "label": "Block waste allowance (%)", "type": "number", "defaultValue": "5"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "retaining-wall-block-calculator": { fields: [{"key": "length", "label": "Wall length (ft)", "type": "number", "defaultValue": "40"}, {"key": "height", "label": "Wall height (ft)", "type": "number", "defaultValue": "3"}, {"key": "blockLength", "label": "Block face length (in)", "type": "number", "defaultValue": "12"}, {"key": "blockHeight", "label": "Block face height (in)", "type": "number", "defaultValue": "4"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "5"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "retaining-wall-material-calculator": { fields: [{"key": "length", "label": "Wall length (ft)", "type": "number", "defaultValue": "40"}, {"key": "height", "label": "Wall height (ft)", "type": "number", "defaultValue": "3"}, {"key": "blocksPerSqFt", "label": "Blocks per sq ft", "type": "number", "defaultValue": "3"}, {"key": "gravelWidth", "label": "Drainage gravel width (in)", "type": "number", "defaultValue": "12"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "5"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "brick-wall-calculator": { fields: [{"key": "wallLength", "label": "Wall length (ft)", "type": "number", "defaultValue": "30"}, {"key": "wallHeight", "label": "Wall height (ft)", "type": "number", "defaultValue": "8"}, {"key": "brickLength", "label": "Brick length (in)", "type": "number", "defaultValue": "8"}, {"key": "brickHeight", "label": "Brick height (in)", "type": "number", "defaultValue": "2.25"}, {"key": "joint", "label": "Mortar joint (in)", "type": "number", "defaultValue": "0.375"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "bricks-per-square-foot-calculator": { fields: [{"key": "brickLength", "label": "Brick length (in)", "type": "number", "defaultValue": "8"}, {"key": "brickHeight", "label": "Brick height (in)", "type": "number", "defaultValue": "2.25"}, {"key": "joint", "label": "Mortar joint (in)", "type": "number", "defaultValue": "0.375"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "bricks-per-square-meter-calculator": { fields: [{"key": "brickLength", "label": "Brick length (mm)", "type": "number", "defaultValue": "215"}, {"key": "brickHeight", "label": "Brick height (mm)", "type": "number", "defaultValue": "65"}, {"key": "joint", "label": "Mortar joint (mm)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "brick-mortar-calculator": { fields: [{"key": "wallLength", "label": "Wall length (ft)", "type": "number", "defaultValue": "30"}, {"key": "wallHeight", "label": "Wall height (ft)", "type": "number", "defaultValue": "8"}, {"key": "brickLength", "label": "Brick length (in)", "type": "number", "defaultValue": "8"}, {"key": "brickHeight", "label": "Brick height (in)", "type": "number", "defaultValue": "2.25"}, {"key": "brickDepth", "label": "Brick depth (in)", "type": "number", "defaultValue": "3.625"}, {"key": "joint", "label": "Mortar joint (in)", "type": "number", "defaultValue": "0.375"}, {"key": "bagYield", "label": "Mortar yield per bag (cu ft)", "type": "number", "defaultValue": "0.6"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "masonry-mortar-calculator": { fields: [{"key": "area", "label": "Masonry area (sq ft)", "type": "number", "defaultValue": "500"}, {"key": "coverage", "label": "Coverage per bag (sq ft)", "type": "number", "defaultValue": "35"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "masonry-wall-calculator": { fields: [{"key": "wallLength", "label": "Wall length (ft)", "type": "number", "defaultValue": "30"}, {"key": "wallHeight", "label": "Wall height (ft)", "type": "number", "defaultValue": "8"}, {"key": "unitLength", "label": "Unit face length (in)", "type": "number", "defaultValue": "16"}, {"key": "unitHeight", "label": "Unit face height (in)", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "5"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "footing-concrete-calculator": { fields: [{"key": "length", "label": "Footing length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Footing width (in)", "type": "number", "defaultValue": "24"}, {"key": "depth", "label": "Footing depth (in)", "type": "number", "defaultValue": "12"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "strip-footing-concrete-calculator": { fields: [{"key": "totalLength", "label": "Total footing length (ft)", "type": "number", "defaultValue": "80"}, {"key": "width", "label": "Footing width (in)", "type": "number", "defaultValue": "24"}, {"key": "depth", "label": "Footing depth (in)", "type": "number", "defaultValue": "10"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "foundation-concrete-calculator": { fields: [{"key": "length", "label": "Total wall length (ft)", "type": "number", "defaultValue": "120"}, {"key": "height", "label": "Wall height (ft)", "type": "number", "defaultValue": "8"}, {"key": "thickness", "label": "Wall thickness (in)", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "pier-concrete-calculator": { fields: [{"key": "diameter", "label": "Pier diameter (in)", "type": "number", "defaultValue": "18"}, {"key": "depth", "label": "Pier depth (ft)", "type": "number", "defaultValue": "4"}, {"key": "quantity", "label": "Number of piers", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "sonotube-concrete-calculator": { fields: [{"key": "diameter", "label": "Tube diameter (in)", "type": "number", "defaultValue": "12"}, {"key": "height", "label": "Tube height (ft)", "type": "number", "defaultValue": "4"}, {"key": "quantity", "label": "Number of tubes", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "concrete-column-calculator": { fields: [{"key": "width", "label": "Column width (in)", "type": "number", "defaultValue": "12"}, {"key": "depth", "label": "Column depth (in)", "type": "number", "defaultValue": "12"}, {"key": "height", "label": "Column height (ft)", "type": "number", "defaultValue": "10"}, {"key": "quantity", "label": "Number of columns", "type": "number", "defaultValue": "4"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "concrete-stairs-calculator": { fields: [{"key": "width", "label": "Stair width (ft)", "type": "number", "defaultValue": "4"}, {"key": "riser", "label": "Riser height (in)", "type": "number", "defaultValue": "7.5"}, {"key": "tread", "label": "Tread depth (in)", "type": "number", "defaultValue": "10"}, {"key": "steps", "label": "Number of steps", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Planning estimate only. This calculator estimates material quantities and does not perform structural engineering or code compliance checks." },
  "concrete-curb-calculator": { fields: [{"key": "length", "label": "Curb length (ft)", "type": "number", "defaultValue": "100"}, {"key": "width", "label": "Curb width (in)", "type": "number", "defaultValue": "6"}, {"key": "height", "label": "Curb height (in)", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "concrete-driveway-calculator": { fields: [{"key": "length", "label": "Driveway length (ft)", "type": "number", "defaultValue": "40"}, {"key": "width", "label": "Driveway width (ft)", "type": "number", "defaultValue": "18"}, {"key": "thickness", "label": "Thickness (in)", "type": "number", "defaultValue": "4"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "concrete-patio-calculator": { fields: [{"key": "length", "label": "Patio length (ft)", "type": "number", "defaultValue": "20"}, {"key": "width", "label": "Patio width (ft)", "type": "number", "defaultValue": "16"}, {"key": "thickness", "label": "Thickness (in)", "type": "number", "defaultValue": "4"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "concrete-post-hole-calculator": { fields: [{"key": "diameter", "label": "Hole diameter (in)", "type": "number", "defaultValue": "12"}, {"key": "depth", "label": "Hole depth (ft)", "type": "number", "defaultValue": "3"}, {"key": "quantity", "label": "Number of holes", "type": "number", "defaultValue": "10"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "concrete-yield-calculator": { fields: [{"key": "bags", "label": "Number of bags", "type": "number", "defaultValue": "20"}, {"key": "yield", "label": "Yield per bag (cu ft)", "type": "number", "defaultValue": "0.6"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "ready-mix-concrete-cost-calculator": { fields: [{"key": "yards", "label": "Concrete volume (cu yd)", "type": "number", "defaultValue": "10"}, {"key": "price", "label": "Price per cu yd ($)", "type": "number", "defaultValue": "165"}, {"key": "delivery", "label": "Delivery/short-load fee ($)", "type": "number", "defaultValue": "0"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "5"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "aggregate-calculator": { fields: [{"key": "length", "label": "Length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Width (ft)", "type": "number", "defaultValue": "20"}, {"key": "depth", "label": "Depth (in)", "type": "number", "defaultValue": "4"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "100"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "pea-gravel-calculator": { fields: [{"key": "length", "label": "Length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Width (ft)", "type": "number", "defaultValue": "20"}, {"key": "depth", "label": "Depth (in)", "type": "number", "defaultValue": "3"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "95"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "limestone-calculator": { fields: [{"key": "length", "label": "Length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Width (ft)", "type": "number", "defaultValue": "20"}, {"key": "depth", "label": "Depth (in)", "type": "number", "defaultValue": "4"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "100"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "crushed-concrete-calculator": { fields: [{"key": "length", "label": "Length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Width (ft)", "type": "number", "defaultValue": "20"}, {"key": "depth", "label": "Depth (in)", "type": "number", "defaultValue": "4"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "110"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "decomposed-granite-calculator": { fields: [{"key": "length", "label": "Length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Width (ft)", "type": "number", "defaultValue": "20"}, {"key": "depth", "label": "Depth (in)", "type": "number", "defaultValue": "3"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "100"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "landscape-rock-calculator": { fields: [{"key": "length", "label": "Length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Width (ft)", "type": "number", "defaultValue": "10"}, {"key": "depth", "label": "Depth (in)", "type": "number", "defaultValue": "3"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "100"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "driveway-material-calculator": { fields: [{"key": "length", "label": "Driveway length (ft)", "type": "number", "defaultValue": "50"}, {"key": "width", "label": "Driveway width (ft)", "type": "number", "defaultValue": "12"}, {"key": "depth", "label": "Depth (in)", "type": "number", "defaultValue": "6"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "110"}, {"key": "cost", "label": "Cost per ton ($)", "type": "number", "defaultValue": "45"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "asphalt-driveway-calculator": { fields: [{"key": "length", "label": "Driveway length (ft)", "type": "number", "defaultValue": "50"}, {"key": "width", "label": "Driveway width (ft)", "type": "number", "defaultValue": "12"}, {"key": "thickness", "label": "Asphalt thickness (in)", "type": "number", "defaultValue": "3"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "145"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "asphalt-tonnage-calculator": { fields: [{"key": "area", "label": "Paved area (sq ft)", "type": "number", "defaultValue": "1000"}, {"key": "thickness", "label": "Thickness (in)", "type": "number", "defaultValue": "3"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "145"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "asphalt-cost-calculator": { fields: [{"key": "tons", "label": "Asphalt quantity (tons)", "type": "number", "defaultValue": "10"}, {"key": "price", "label": "Price per ton ($)", "type": "number", "defaultValue": "120"}, {"key": "extra", "label": "Additional fees ($)", "type": "number", "defaultValue": "0"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "road-gravel-calculator": { fields: [{"key": "length", "label": "Road length (ft)", "type": "number", "defaultValue": "500"}, {"key": "width", "label": "Road width (ft)", "type": "number", "defaultValue": "12"}, {"key": "depth", "label": "Depth (in)", "type": "number", "defaultValue": "6"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "110"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "sub-base-calculator": { fields: [{"key": "length", "label": "Area length (ft)", "type": "number", "defaultValue": "50"}, {"key": "width", "label": "Area width (ft)", "type": "number", "defaultValue": "20"}, {"key": "depth", "label": "Compacted depth (in)", "type": "number", "defaultValue": "6"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "120"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "trench-volume-calculator": { fields: [{"key": "length", "label": "Trench length (ft)", "type": "number", "defaultValue": "100"}, {"key": "width", "label": "Trench width (in)", "type": "number", "defaultValue": "18"}, {"key": "depth", "label": "Trench depth (ft)", "type": "number", "defaultValue": "3"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "excavation-volume-calculator": { fields: [{"key": "length", "label": "Excavation length (ft)", "type": "number", "defaultValue": "30"}, {"key": "width", "label": "Excavation width (ft)", "type": "number", "defaultValue": "20"}, {"key": "depth", "label": "Excavation depth (ft)", "type": "number", "defaultValue": "4"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "fill-dirt-calculator": { fields: [{"key": "length", "label": "Area length (ft)", "type": "number", "defaultValue": "50"}, {"key": "width", "label": "Area width (ft)", "type": "number", "defaultValue": "30"}, {"key": "depth", "label": "Fill depth (in)", "type": "number", "defaultValue": "6"}, {"key": "compaction", "label": "Compaction/settlement allowance (%)", "type": "number", "defaultValue": "15"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "backfill-calculator": { fields: [{"key": "length", "label": "Excavation length (ft)", "type": "number", "defaultValue": "40"}, {"key": "width", "label": "Excavation width (ft)", "type": "number", "defaultValue": "4"}, {"key": "depth", "label": "Excavation depth (ft)", "type": "number", "defaultValue": "5"}, {"key": "occupied", "label": "Buried structure volume (cu ft)", "type": "number", "defaultValue": "200"}, {"key": "compaction", "label": "Compaction allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "dirt-weight-calculator": { fields: [{"key": "yards", "label": "Dirt volume (cu yd)", "type": "number", "defaultValue": "10"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "90"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "retaining-wall-gravel-calculator": { fields: [{"key": "length", "label": "Wall length (ft)", "type": "number", "defaultValue": "40"}, {"key": "height", "label": "Gravel height (ft)", "type": "number", "defaultValue": "3"}, {"key": "width", "label": "Gravel zone width (in)", "type": "number", "defaultValue": "12"}, {"key": "density", "label": "Density (lb/cu ft)", "type": "number", "defaultValue": "100"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "plaster-calculator": { fields: [{"key": "area", "label": "Wall/ceiling area (sq ft)", "type": "number", "defaultValue": "1000"}, {"key": "coats", "label": "Number of coats", "type": "number", "defaultValue": "2"}, {"key": "coverage", "label": "Coverage per bag per coat (sq ft)", "type": "number", "defaultValue": "100"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "stucco-calculator": { fields: [{"key": "area", "label": "Surface area (sq ft)", "type": "number", "defaultValue": "1500"}, {"key": "coats", "label": "Number of coats", "type": "number", "defaultValue": "3"}, {"key": "coverage", "label": "Coverage per bag per coat (sq ft)", "type": "number", "defaultValue": "100"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "siding-calculator": { fields: [{"key": "wallArea", "label": "Gross wall area (sq ft)", "type": "number", "defaultValue": "2000"}, {"key": "openings", "label": "Windows/doors area (sq ft)", "type": "number", "defaultValue": "250"}, {"key": "pieceCoverage", "label": "Coverage per siding piece (sq ft)", "type": "number", "defaultValue": "8"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "baseboard-calculator": { fields: [{"key": "perimeter", "label": "Room perimeter (ft)", "type": "number", "defaultValue": "60"}, {"key": "openings", "label": "Door/opening width to subtract (ft)", "type": "number", "defaultValue": "6"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}, {"key": "stockLength", "label": "Stock piece length (ft)", "type": "number", "defaultValue": "8"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "crown-molding-calculator": { fields: [{"key": "perimeter", "label": "Room perimeter (ft)", "type": "number", "defaultValue": "60"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}, {"key": "stockLength", "label": "Stock piece length (ft)", "type": "number", "defaultValue": "8"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." },
  "roof-tile-calculator": { fields: [{"key": "area", "label": "Roof area (sq ft)", "type": "number", "defaultValue": "2000"}, {"key": "tileCoverage", "label": "Coverage per tile (sq ft)", "type": "number", "defaultValue": "1.2"}, {"key": "waste", "label": "Waste allowance (%)", "type": "number", "defaultValue": "10"}], button: "Calculate", note: "Material estimate only. Actual quantities vary with dimensions, waste, cuts, compaction, installation method, manufacturer specifications, and local construction requirements." }
};

export function runBatch601650(kind: Batch601650Kind, v: Record<string,string>): Batch601650Result {
  switch(kind) {
    case "concrete-block-fill-calculator": { const blocks=pos(v.blocks,"Number of blocks"), per=pos(v.fillPerBlock,"Fill volume per block"), wa=pct(v.waste,"Waste allowance"), cf=blocks*per*(1+wa), bags=Math.ceil(cf/0.6); return R(`${fmt(cf/27)} cu yd`,[["Fill volume",`${fmt(cf)} cu ft`],["Cubic yards",`${fmt(cf/27)} cu yd`],["Approx. 80 lb bags at 0.6 cu ft each",String(bags)]]); }
    case "block-wall-calculator":
    case "cinder-block-calculator": { const count=blockCount(pos(v.wallLength,"Wall length"),pos(v.wallHeight,"Wall height"),pos(v.blockLength,"Block length"),pos(v.blockHeight,"Block height"),pct(v.waste,"Waste allowance")); const area=pos(v.wallLength,"Wall length")*pos(v.wallHeight,"Wall height"); return R(`${count} blocks`,[["Estimated blocks",String(count)],["Wall area",`${fmt(area)} sq ft`]]); }
    case "breeze-block-calculator": { const area=pos(v.wallLength,"Wall length")*pos(v.wallHeight,"Wall height"), unit=(pos(v.blockLength,"Block length")/1000)*(pos(v.blockHeight,"Block height")/1000), count=Math.ceil(area/unit*(1+pct(v.waste,"Waste allowance"))); return R(`${count} blocks`,[["Estimated blocks",String(count)],["Wall area",`${fmt(area)} m²`]]); }
    case "block-and-beam-floor-calculator": { const l=pos(v.length,"Floor length"),w=pos(v.width,"Floor width"),sp=pos(v.beamSpacing,"Beam spacing"),rows=Math.ceil(w/sp)+1,totalBeam=rows*l,blockArea=pos(v.blockLength,"Block length")*pos(v.blockWidth,"Block width")/144,blocks=Math.ceil(l*w/blockArea*(1+pct(v.waste,"Waste allowance"))); return R(`${blocks} infill blocks`,[["Floor area",`${fmt(l*w)} sq ft`],["Approx. beam rows",String(rows)],["Approx. total beam length",`${fmt(totalBeam)} ft`],["Estimated infill blocks",String(blocks)]]); }
    case "retaining-wall-block-calculator": { const count=blockCount(pos(v.length,"Wall length"),pos(v.height,"Wall height"),pos(v.blockLength,"Block length"),pos(v.blockHeight,"Block height"),pct(v.waste,"Waste allowance")); return R(`${count} blocks`,[["Estimated blocks",String(count)],["Wall face area",`${fmt(pos(v.length,"Wall length")*pos(v.height,"Wall height"))} sq ft`]]); }
    case "retaining-wall-material-calculator": { const l=pos(v.length,"Wall length"),h=pos(v.height,"Wall height"),b=pos(v.blocksPerSqFt,"Blocks per sq ft"),wa=pct(v.waste,"Waste allowance"),blocks=Math.ceil(l*h*b*(1+wa)),gravelCf=l*h*pos(v.gravelWidth,"Gravel width")/12; return R(`${blocks} blocks`,[["Estimated blocks",String(blocks)],["Drainage gravel",`${fmt(gravelCf/27)} cu yd`],["Wall face area",`${fmt(l*h)} sq ft`]]); }
    case "brick-wall-calculator": { const wl=pos(v.wallLength,"Wall length"),wh=pos(v.wallHeight,"Wall height"),bl=pos(v.brickLength,"Brick length"),bh=pos(v.brickHeight,"Brick height"),j=nonneg(v.joint,"Mortar joint"),count=Math.ceil(wl*wh*144/((bl+j)*(bh+j))*(1+pct(v.waste,"Waste allowance"))); return R(`${count} bricks`,[["Estimated bricks",String(count)],["Wall area",`${fmt(wl*wh)} sq ft`]]); }
    case "bricks-per-square-foot-calculator": { const bl=pos(v.brickLength,"Brick length"),bh=pos(v.brickHeight,"Brick height"),j=nonneg(v.joint,"Mortar joint"),n=144/((bl+j)*(bh+j)); return R(`${fmt(n)} bricks/sq ft`,[["Bricks per square foot",fmt(n)],["Coverage per brick",`${fmt(((bl+j)*(bh+j))/144)} sq ft`]]); }
    case "bricks-per-square-meter-calculator": { const bl=pos(v.brickLength,"Brick length")/1000,bh=pos(v.brickHeight,"Brick height")/1000,j=nonneg(v.joint,"Mortar joint")/1000,n=1/((bl+j)*(bh+j)); return R(`${fmt(n)} bricks/m²`,[["Bricks per square meter",fmt(n)],["Coverage per brick",`${fmt((bl+j)*(bh+j),6)} m²`]]); }
    case "brick-mortar-calculator": { const wl=pos(v.wallLength,"Wall length")*12,wh=pos(v.wallHeight,"Wall height")*12,bl=pos(v.brickLength,"Brick length"),bh=pos(v.brickHeight,"Brick height"),bd=pos(v.brickDepth,"Brick depth"),j=nonneg(v.joint,"Mortar joint"),yieldCf=pos(v.bagYield,"Bag yield"),wallArea=wl*wh,cell=(bl+j)*(bh+j),bricks=Math.floor(wallArea/cell),wallVol=wallArea*bd,brickVol=bricks*bl*bh*bd,mortarCf=Math.max(0,wallVol-brickVol)/1728,bags=Math.ceil(mortarCf/yieldCf); return R(`${fmt(mortarCf)} cu ft`,[["Approx. mortar volume",`${fmt(mortarCf)} cu ft`],["Estimated bags",String(bags)],["Approx. bricks",String(bricks)]]); }
    case "masonry-mortar-calculator": { const a=pos(v.area,"Masonry area"),cov=pos(v.coverage,"Coverage"),adj=a*(1+pct(v.waste,"Waste allowance")),bags=Math.ceil(adj/cov); return R(`${bags} bags`,[["Adjusted area",`${fmt(adj)} sq ft`],["Estimated bags",String(bags)]]); }
    case "masonry-wall-calculator": { const count=blockCount(pos(v.wallLength,"Wall length"),pos(v.wallHeight,"Wall height"),pos(v.unitLength,"Unit length"),pos(v.unitHeight,"Unit height"),pct(v.waste,"Waste allowance")); return R(`${count} masonry units`,[["Estimated units",String(count)],["Wall area",`${fmt(pos(v.wallLength,"Wall length")*pos(v.wallHeight,"Wall height"))} sq ft`]]); }
    case "footing-concrete-calculator": { const cf=pos(v.length,"Length")*pos(v.width,"Width")/12*pos(v.depth,"Depth")/12*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,[["Concrete volume",`${fmt(cf/27)} cu yd`],["Cubic feet",`${fmt(cf)} cu ft`]]); }
    case "strip-footing-concrete-calculator": { const cf=pos(v.totalLength,"Total length")*pos(v.width,"Width")/12*pos(v.depth,"Depth")/12*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,[["Concrete volume",`${fmt(cf/27)} cu yd`],["Cubic feet",`${fmt(cf)} cu ft`]]); }
    case "foundation-concrete-calculator": { const cf=pos(v.length,"Length")*pos(v.height,"Height")*pos(v.thickness,"Thickness")/12*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,[["Concrete volume",`${fmt(cf/27)} cu yd`],["Cubic feet",`${fmt(cf)} cu ft`]]); }
    case "pier-concrete-calculator": { const cf=cylinder(pos(v.diameter,"Diameter"),pos(v.depth,"Depth"),pos(v.quantity,"Quantity"))*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,volPair(cf)); }
    case "sonotube-concrete-calculator": { const cf=cylinder(pos(v.diameter,"Diameter"),pos(v.height,"Height"),pos(v.quantity,"Quantity"))*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,volPair(cf)); }
    case "concrete-column-calculator": { const cf=pos(v.width,"Width")/12*pos(v.depth,"Depth")/12*pos(v.height,"Height")*pos(v.quantity,"Quantity")*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,volPair(cf)); }
    case "concrete-stairs-calculator": { const width=pos(v.width,"Width"),r=pos(v.riser,"Riser")/12,t=pos(v.tread,"Tread")/12,n=Math.ceil(pos(v.steps,"Steps")),cf=width*t*r*n*(n+1)/2*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,[["Approx. solid stair volume",`${fmt(cf/27)} cu yd`],["Cubic feet",`${fmt(cf)} cu ft`],["Steps",String(n)]]); }
    case "concrete-curb-calculator": { const cf=pos(v.length,"Length")*pos(v.width,"Width")/12*pos(v.height,"Height")/12*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,volPair(cf)); }
    case "concrete-driveway-calculator":
    case "concrete-patio-calculator": return slab(v);
    case "concrete-post-hole-calculator": { const cf=cylinder(pos(v.diameter,"Diameter"),pos(v.depth,"Depth"),pos(v.quantity,"Quantity"))*(1+pct(v.waste,"Waste allowance")); return R(`${fmt(cf/27)} cu yd`,volPair(cf)); }
    case "concrete-yield-calculator": { const bags=pos(v.bags,"Number of bags"),y=pos(v.yield,"Yield per bag"),cf=bags*y; return R(`${fmt(cf)} cu ft`,[["Total yield",`${fmt(cf)} cu ft`],["Cubic yards",`${fmt(cf/27)} cu yd`],["Bags",fmt(bags)]]); }
    case "ready-mix-concrete-cost-calculator": { const y=pos(v.yards,"Concrete volume"),wa=pct(v.waste,"Waste allowance"),adj=y*(1+wa),cost=adj*nonneg(v.price,"Price")+nonneg(v.delivery,"Delivery fee"); return R(money(cost),[["Order volume with waste",`${fmt(adj)} cu yd`],["Estimated material + delivery cost",money(cost)]]); }
    case "aggregate-calculator": return materialBox(v,100);
    case "pea-gravel-calculator": return materialBox(v,95);
    case "limestone-calculator": return materialBox(v,100);
    case "crushed-concrete-calculator": return materialBox(v,110);
    case "decomposed-granite-calculator": return materialBox(v,100);
    case "landscape-rock-calculator": return materialBox(v,100);
    case "driveway-material-calculator": { const l=pos(v.length,"Length"),w=pos(v.width,"Width"),d=pos(v.depth,"Depth"),density=pos(v.density,"Density"),cf=l*w*d/12,cy=cf/27,tons=cf*density/2000,cost=tons*nonneg(v.cost,"Cost per ton"); return R(money(cost),[["Volume",`${fmt(cy)} cu yd`],["Estimated weight",`${fmt(tons)} tons`],["Estimated material cost",money(cost)]]); }
    case "asphalt-driveway-calculator": { const cf=pos(v.length,"Length")*pos(v.width,"Width")*pos(v.thickness,"Thickness")/12,tons=cf*pos(v.density,"Density")/2000; return R(`${fmt(tons)} tons`,[["Asphalt tonnage",`${fmt(tons)} tons`],["Volume",`${fmt(cf/27)} cu yd`],["Paved area",`${fmt(pos(v.length,"Length")*pos(v.width,"Width"))} sq ft`]]); }
    case "asphalt-tonnage-calculator": { const cf=pos(v.area,"Area")*pos(v.thickness,"Thickness")/12,tons=cf*pos(v.density,"Density")/2000; return R(`${fmt(tons)} tons`,[["Asphalt tonnage",`${fmt(tons)} tons`],["Volume",`${fmt(cf/27)} cu yd`]]); }
    case "asphalt-cost-calculator": { const tons=pos(v.tons,"Asphalt quantity"),cost=tons*nonneg(v.price,"Price")+nonneg(v.extra,"Additional fees"); return R(money(cost),[["Asphalt quantity",`${fmt(tons)} tons`],["Estimated cost",money(cost)]]); }
    case "road-gravel-calculator": return materialBox(v,110);
    case "sub-base-calculator": return materialBox(v,120);
    case "trench-volume-calculator": { const cf=pos(v.length,"Length")*pos(v.width,"Width")/12*pos(v.depth,"Depth"); return R(`${fmt(cf/27)} cu yd`,volPair(cf)); }
    case "excavation-volume-calculator": { const cf=pos(v.length,"Length")*pos(v.width,"Width")*pos(v.depth,"Depth"); return R(`${fmt(cf/27)} cu yd`,volPair(cf)); }
    case "fill-dirt-calculator": { const cf=pos(v.length,"Length")*pos(v.width,"Width")*pos(v.depth,"Depth")/12*(1+pct(v.compaction,"Compaction allowance")); return R(`${fmt(cf/27)} cu yd`,[["Order volume",`${fmt(cf/27)} cu yd`],["Cubic feet",`${fmt(cf)} cu ft`]]); }
    case "backfill-calculator": { const excav=pos(v.length,"Length")*pos(v.width,"Width")*pos(v.depth,"Depth"),occupied=nonneg(v.occupied,"Occupied volume"),base=Math.max(0,excav-occupied),cf=base*(1+pct(v.compaction,"Compaction allowance")); return R(`${fmt(cf/27)} cu yd`,[["Excavation volume",`${fmt(excav)} cu ft`],["Net backfill before allowance",`${fmt(base)} cu ft`],["Order backfill",`${fmt(cf/27)} cu yd`]]); }
    case "dirt-weight-calculator": { const y=pos(v.yards,"Dirt volume"),density=pos(v.density,"Density"),lb=y*27*density,tons=lb/2000; return R(`${fmt(tons)} tons`,[["Estimated weight",`${fmt(tons)} tons`],["Pounds",`${fmt(lb)} lb`]]); }
    case "retaining-wall-gravel-calculator": { const cf=pos(v.length,"Length")*pos(v.height,"Height")*pos(v.width,"Width")/12,tons=cf*pos(v.density,"Density")/2000; return R(`${fmt(cf/27)} cu yd`,[["Drainage gravel",`${fmt(cf/27)} cu yd`],["Estimated weight",`${fmt(tons)} tons`]]); }
    case "plaster-calculator":
    case "stucco-calculator": { const area=pos(v.area,"Area"),coats=pos(v.coats,"Coats"),cov=pos(v.coverage,"Coverage"),adj=area*coats*(1+pct(v.waste,"Waste allowance")),bags=Math.ceil(adj/cov); return R(`${bags} bags`,[["Coat-adjusted area",`${fmt(adj)} sq ft`],["Estimated bags",String(bags)]]); }
    case "siding-calculator": { const gross=pos(v.wallArea,"Wall area"),open=nonneg(v.openings,"Openings"),net=Math.max(0,gross-open),adj=net*(1+pct(v.waste,"Waste allowance")),pieces=Math.ceil(adj/pos(v.pieceCoverage,"Piece coverage")),squares=adj/100; return R(`${fmt(squares)} squares`,[["Net wall area",`${fmt(net)} sq ft`],["Adjusted siding area",`${fmt(adj)} sq ft`],["Siding squares",fmt(squares)],["Estimated pieces",String(pieces)]]); }
    case "baseboard-calculator": { const net=Math.max(0,pos(v.perimeter,"Perimeter")-nonneg(v.openings,"Openings")),adj=net*(1+pct(v.waste,"Waste allowance")),pieces=Math.ceil(adj/pos(v.stockLength,"Stock length")); return R(`${fmt(adj)} linear ft`,[["Net length",`${fmt(net)} ft`],["With waste",`${fmt(adj)} ft`],["Stock pieces",String(pieces)]]); }
    case "crown-molding-calculator": { const adj=pos(v.perimeter,"Perimeter")*(1+pct(v.waste,"Waste allowance")),pieces=Math.ceil(adj/pos(v.stockLength,"Stock length")); return R(`${fmt(adj)} linear ft`,[["With waste",`${fmt(adj)} ft`],["Stock pieces",String(pieces)]]); }
    case "roof-tile-calculator": { const area=pos(v.area,"Roof area"),cov=pos(v.tileCoverage,"Tile coverage"),adj=area*(1+pct(v.waste,"Waste allowance")),tiles=Math.ceil(adj/cov); return R(`${tiles} tiles`,[["Adjusted roof area",`${fmt(adj)} sq ft`],["Estimated tiles",String(tiles)]]); }
    default: throw new Error("This calculator is not configured.");
  }
}
